### ISSUE TITLE
Please add waiver to dataset doi: 10.5061/dryad.hqbzkh1cg

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1009]
**Request:** Adjust dataset to be waived, TKT approved.

We will have Cxore void the invoice

**Comment by LoriEP** [comment]
SF Case # 00001838

**Comment by sfisher** [comment]
I waived this by putting in payment type: "manual" and payment_id: "curator-waiver" since it looked like the other "waiver" values were for low-income countries (and this one didn't seem to apply).  There were some others waived as "manual" in the database for curator requests for unknown reasons. Probably good to know the reason since it may help to change what we put in.

It looks like currently we have these distinct values for payment_type.

dryad-v1
classic-dryad
journal-DEFERRED
waiver
journal-SUBSCRIPTION
unknown
stripe
institution
journal-PREPAID
manual
voucher
funder
msu

@ryscher You can correct if this is a problem.  We may also want to standardize the payment types with an enum or something if we want to limit to a standard list.
