### ISSUE TITLE
Corresponding author

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#1021]
I believe this is completed, though the original idea for how to do this is different than what we worked out to do.

What I did:

- Corresponding author is the one that has the same ORCID as the dataset owner.
- Email is required for this author to submit.
- When no author has the same orcid as the one that is the dataset owner then a new author is added when beginning to edit in the UI.
- Corresponding author cannot be deleted from authors in the UI.
- Lots of tests updated to have the required data to enable submissions since the test data didn't always meet our new criteria for corresponding author.
- Ryan looked at the UI and doesn't believe it will interfere with publisher updates or submissions.

--
Original information below in case we need to refer to it again later. I'll call this task done for now.

- [x] Denote corresponding author by default as the submitting author using wording in italics next to ORCID that says "Corresponding Author" on submission form (doesn't appear on published landing page)
- [ ] Add corresponding_author_id to stash_engine_resource
- [ ] Add methods for getting/setting corresponding author from a resource
- [ ] Ensure the API supports getting/setting corresponding author
- [ ] Update validation in the API/UI to generate an error if the corresponding author does not include an email. (Should emails now be optional for all other authors?)
- [ ] Update email processing to ensure all messages are sent to the corresponding author

**Comment by sfisher** [comment]
I need to check in with @ryscher for background on this one.

**Comment by sfisher** [comment]
I think we need to talk this through in our meeting.  I currently have something that matches ORCIDs between user and authors to get the corresponding author (dataset owner author).

I believe this is a case where we're going through contortions because ORCID doesn't give us emails.  Sometimes we can figure out the email address by matching between authors and the user record, but not always.

If we're doing this "corresponding author" because we don't have good user information for someone who logged in then maybe we should just demand it before allowing a submission if we can't figure it out from the authors?

Or is the corresponding author somehow different than the logged in user?  I thought in most cases (emails, etc) we're really wanting to email the user that logged in and that knows what is going on in Dryad. Or is corresponding different than that user?  IDK, there might be other use cases this doesn't fit?
