### ISSUE TITLE
New Tenant: University of Minnesota

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1029]
Logo from Lisa

**Comment by ryscher** [comment]
Note that I added RORs for all campuses, including the medical center and children's hospital, since they appear to be fully part of the system -- their websites all display the official UMN logo.

<img width="1172" alt="Screen Shot 2021-01-18 at 10 53 37 AM" src="https://user-images.githubusercontent.com/605143/104938457-1bf8b400-597d-11eb-8e51-b8f433c446d1.png">
<img width="1017" alt="Screen Shot 2021-01-18 at 10 54 23 AM" src="https://user-images.githubusercontent.com/605143/104938472-2450ef00-597d-11eb-8dab-0898788b503c.png">
