### ISSUE TITLE
Uploads to S3 -- Update Merritt/SWORD

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#1078]
Change the Merritt/SWORD process to use presigned URLs from the new S3 bucket, rather than files on the EFS volume.

Info about format for how staged files are stored.

- Normally it is `<resource_id>/<filename>`
- Software is `<resource_id>_sfw/<filename>`
- Supplemental info will be `<resource_id>_supp/<filename>`
- We don't want to create more buckets on dev . . . so each database or server (if it's a loopback address for database) has a special hash appended to the first before the resource_id.

Some tasks (may not be comprehensive):

- [x] When submitting to Merritt, use the manifest of urls method rather than the zip file method for everything.
- [x] Manifests are created off the list of files in the database (I believe).
- [x] For each user file that we put in the manifest we want to generate a pre-signed S3 URL to use.
- [x] The manifest also contains some xml files like mrt-datacite.xml, mrt-dataone-manifest.txt, mrt-oaidc.txt, stash-wrapper.xml.  The complete list of these generated files is in the code somewhere.
  - [x] Also host these files in S3 and generate presigned URLs for them.  They were previously written to a directory and exposed on our server somewhere for manifest submissions and this is why manifest submissions never worked from local development environments in the past.  This is why I think we want to change this--so that test/dev manifest submissions work from any machine rather than just an "official" server.
- [x] Probably want to delete "folder" of files from S3 once the OAI-PMH confirms that it made it into Merritt.   `landing_controller#patch` is where it's notified, though it does quite a bit in there.
- [ ] Ensure that 4-byte characters still work

**Comment by sfisher** [comment]
Moving these into a comment since old information

I've put test code in the branch `test-s3` for now and I think it will ease creation of presigned URLs and a bunch of other stuff you're working on.  I'll try to get a new branch together in the meantime called `s3-main` which can be our merge target for features we create until we are ready to release.

The photo below is a diff of the test branch vs main.  From below it seems like the files that will be most useful for you to see are the app_config.yml and credentials.yml (those will change accounts from test ones), documentation and stash_engine/lib/stash/s3/test.rb.  The test.rb contains a bunch of examples of how to work with files with the S3 Ruby gem provided by amazon and has examples of uploading, downloading, creating presigned urls and even an example of doing one with multiple parts (in case you want to know the innards of how to do it manually), though the gem will automatically do it.

I'll try to clean up a bit and do a first PR against the branch to bring in the configuration and correct libraries and other things from a new branch, but the test one might be useful in the meantime.

![Screen Shot 2021-01-29 at 10 12 21 AM](https://user-images.githubusercontent.com/105433/106311860-a7463500-621a-11eb-97eb-fb5ea10ab544.png)

**Comment by sfisher** [comment]
The rough demo now 1) calculates special prefixes for development to keep the "folder" names separate if development is running on a separate database or server (method `s3_dir_name(type: 'data')` in resource.rb model); 2) it writes completed uploads to the database table that tracks uploaded files when the S3 upload completes for each file.

This is all in the branch `test-s3-2` .

## How to create some test data for using with pre-signed uploads in Merritt manifest

1. Check out and run `test-s3-2` branch
2. Create a new dataset and fill in whatever metadata you like
3. At the point that you would normally upload data files, go to `/stash/test_uploads?id=<resource_id>` instead (by typing it into the URL).
4. Upload some files using the really rough and basic interface.  If the uploads complete and say they are complete then the  `success` callback fired on both the upload to S3 and the AJAX call that updates the database with the file info.
5. After you've uploaded what you want, you can go to another page such as `/stash/resources/<resource_id>/review` to review your submission.  You could submit here if you want (after we have the Merritt submission stuff fixed to only do manifest submissions and it creates presigned URLs for the manifest that it populates in).

You can look into the `stash_engine_file_uploads` and also look at the info in S3 and see that the files enumerated both places match.
