### ISSUE TITLE
Planning: Frictionless processing for large files

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#1091]
We don't want users to wait for a long time while large files are being processed by Frictionless.

- [ ] Determine the size limit for files to be processed in real-time.
- [ ] Determine how to indicate in the UI that processing is occurring in the background, and the user will be notified when it is complete.

**Comment by ahamelers** [comment]
> Determine the size limit for files to be processed in real-time.

Finding a hard size limit is a little difficult because it seems to partially depend on the number of errors—a smaller file with many errors will take longer to process than a larger file with no errors. I suggest to do this we use the frictionless "fail fast" option to "limit errors" to the first X number found (10? 20?)—this would require changing some wording to make clear when the error report is only partial, but I think it would be preferable as it would be faster for everyone.

**Comment by bryanmgee** [comment]
@ahamelers this is kind of tangential, but since there's discussion around Frictionless processing times, I had another submission with the data check stalling out for a small CSV file (short file name, so that wasn't the issue this time around unlike the last time). I think it might be because of the sheer number of columns (the data file, despite being small in size, has more columns than Excel can load). The file attached below was one of nine or so with the same issue; the author got other CSV files in their submission to upload, so it didn't seem like a bug with the entire submission. Thought y'all might want to look at this one too (I've never seen such "wide" file before, but it almost assuredly will happen again).

[bgt127_control.csv](https://github.com/CDL-Dryad/dryad-product-roadmap/files/10438555/bgt127_control.csv)

**Comment by ahamelers** [comment]
I've made up a document with a plan for the different areas of work needed around frictionless: https://docs.google.com/document/d/1_qlSH105VtS6Lchd5puknX3r1Bn5TyJGSoOx7p1Y6BQ/edit?usp=sharing
