### ISSUE TITLE
Address UTF-8 4 byte characters in S3 process

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1117]

**Comment by ryscher** [comment]
Documenting more, because it appears to be an issue with Merritt's handling of 4-byte characters in URLs that are provided as part of a manifest.

My reference character is the emoji "upside-down face":
- code point (hex) U+1F643
- code point (dec) 128579
- UTF-8 representation (hex) f09f9983
- UTF-8 representation (dec) [240, 159, 153, 131]

Notes:
- A file with this character in the filename can be transferred to and from S3 with no problems, using Dryad's S3 code. 
- The presigned URL that we generate and send in `manifest.checkm` properly encodes the 4 bytes. It starts with `https://dryad-s3-dev.s3.us-west-2.amazonaws.com/ec0f3980-525/data/images%F0%9F%99%83emo.jpeg`. This presigned URL resolves correctly.
- The generated metadata files for Merritt (in S3) also use the 4-byte form of the character, ` \xF0\x9F\x99\x83`
- After this file is ingested into Merritt, the Merritt UI displays the character as a question mark `?`. Clicking on the filename in the Merritt UI produces a URL that has the question mark encoded, including `images%253Femo.jpeg`
- See sample file, which is the first file in https://merritt-stage.cdlib.org/m/ark%253A%252F99999%252Ffk4447429x

**Comment by ryscher** [comment]
Merritt-stage has now been updated so these characters transfer correctly. I assume this update will make its way to Merritt-prod in the next few weeks.
