### ISSUE TITLE
IIT ISM SSO issues

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1142]
Unfortunately they did not give any further details beyond this attached screenshot. If this screenshot makes sense and we can proceed, great, if not, please let me know what I need to ask for in reply to understand the issue.
![Dryad Login_security problem](https://user-images.githubusercontent.com/25755963/109523221-f8d52000-7a63-11eb-92c8-4402490e4107.png)

**Comment by sfisher** [comment]
`Message rejected, was issued in the future`

I suspect this may be because their clock is set incorrectly and I believe that times may be critical in some SAML requests.  This would be the clock on their authentication system that we're talking to.  May also have to do with the time zone they have set, especially if they're using local time rather than UTC.

Also run NTP (network time protocol) to synchronize their clock with standard time.

I don't believe this is caused by our time, but by theirs since other people are all able to log in and I double-checked our time on our servers and it shows correct.  While we're using local time (PST), our timezone is set correctly so the time calculations should work.

**Comment by dlowenberg** [comment]
This is helpful, thank you Scott. What do you suggest I specifically ask them to check on? For translation sake it will need to be a brief request so I want to make sure I understand exactly what they should do.

**Comment by sfisher** [comment]
I'm honestly not an expert on Linux time, but the first step will be to run the `date` command at at the shell on their authentication machine.

It should show the correct time and date for the timezone it lists with the time.  It can be often be either the local time or UTC (formerly Greenwich Mean Time).  The critical thing is that it's correct, one way or another.

This is an example from our server.

```
$ date
Mon Mar  1 09:25:38 PST 2021
```

After that, how to fix it depends on the problem.  They may just need to set the time, or they may need to set the timezone or they might need to set both. Probably as long as the time displays correctly for the timezone listed then it will be ok.

The page at https://www.garron.me/en/linux/set-time-date-timezone-ntp-linux-shell-gnome-command-line.html has lots of examples of setting times and timezones.

At the bottom it also goes over how to set a configuration for NTP which is a utility that synchronizes to standard time in case their clock drifts off in the future.  It's not absolutely required if their clock stays in sync, but it's a good idea to use if you can because it will update and may prevent problems later.
