### ISSUE TITLE
Please update member tenant for Jonathan Pekar (0000-0003-0977-2886)

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1154]
**Request:**
Please update tenant to University of California, San Diego for Jonathan Pekar

Dataset doi: 10.5061/dryad.4f4qrfjbm

email addresses: jepekar@eng.ucsd.edu     ---primary email

 jepekar@ucsd.edu.    ---secondary email, this may not be an email associated with a Dryad account

**Comment by sfisher** [comment]
OK.  I updated his user account to ucsd so any future datasets will go on as UCSD.  We can't move his existing dataset that has already been submitted because it used a DataCite DOI and moving it to EZID registration (what UCSD uses) would either make it fail or require a new and different DataCite DOI and DOIs are supposed to be permanent.

This is all independent of the authors which can display whatever is required independently.

Updated his email address.  BTW, if people update their email address in ORCID and allow it to be read by the public or by partners of ORCID then I think it will automatically pick up changes from the ORCID updates into our database.  (Just a FYI if people want to change what email is associated with the ORCID.)

--Scott
