### ISSUE TITLE
Install application on Stage

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#117]
Application needs to be installed on stage.

Jim, marisa and I all get pieces together for servers, shibboleth, orcid and all the software installation.

**Comment by sfisher** [comment]
Daisie and Ryan really wanted the manual application install scripted, so spent some time scripting it in Ansible since that is what they're already using for their own stuff.  It was much more manual since some of the existing libraries choke when they don't have sudo access. https://github.com/CDL-Dryad/server-install

I thought maybe Jim could add some stuff to his puppet, but it seems they want to keep automated server provisioning separate from dependencies and installs of some things for the application.

**Comment by sfisher** [comment]
Also, it turns out that Jim hasn't gotten us database access for stage, yet, so that part is a prerequisite for the application to install and run from Capistrano.

**Comment by sfisher** [comment]
The database is now installed and most of the application works, with a few exceptions.

1.  We're still missing a crontab on the uc3-dryadsolr-stg server such as is on development which runs the harvester every 5 minutes.  @jimvanderveen can help with that.

2. The orcid logo and things are missing from the login screen.  Probably troubles with the asset pipeline (though it works on dev, IDK, why the difference).

3. When I try to submit, I'm getting RestClient::BadRequest: 400 Bad Request.  It's configured to use http://uc3-mrtsword-stg.cdlib.org:39001/mrtsword/collection/ucop_dash for this collection, but it seems like a problem on Merritt or our end.  I don't really see why it would be our end, but it's weird.  I think we'll be getting new collection(s) soon for this item from Merritt people.

other than that, I think stuff all works.  I was able to log in with ORCID and also with shibboleth from UCOP.
