### ISSUE TITLE
Dataset doi:10.5061/dryad.m905qfv0k is Published in admin mode, but appears as Embargoed in incognito mode

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#1177]
**Request:** 
Please release embargo on this dataset. Dataset Activity Log shows no history of Embargo however the public view shows this data as Embargoed.

Navigate to https://doi.org/10.5061/dryad.m905qfv0k while in incognito mode and see that data is Embargoed.

**Comment by ryscher** [comment]
This dataset had several problems, including a large tar file that was not going into Zenodo, and where the most recent version didn't transfer to Dryad completely. (This file was uploaded via URL, so possibly the author deleted the file from their webserver before it completely reached us.) After some discussion, we decided to keep all of the content in Dryad, since it is much larger than Zenodo typically wants.

This dataset is now viewable and downloadable.
