### ISSUE TITLE
Please associate Simone Carlo Surace's ORCID (0000-0001-9321-6481) with current email address

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1217]
**Bug description:**
Please migrate the account for Simone Carlo Surace

Past email addresses include: surace@pyl.unibe.ch, simone.surace@gmail.com
Current email address is: simone.surace@unibe.ch

**Comment by sfisher** [comment]
It looks like this is already done and they migrated their old account themselves correctly.

I updated the email address in their account to be their currently preferred one.

**Comment by jleighherzog** [comment]
Interesting. This user mentioned that they are unable to see/view their datasets after logging in. Are you able to view their account to confirm whether any submissions are there?

**Comment by sfisher** [comment]
It appears they have two accounts and neither seems to have datasets associated with it that they submitted, though they did successfully merge the empty accounts together on their own.

Is it possible that someone like a grad student assistant or a co-author submitted in the past rather than them?  Or do they have any other information about these datasets such as the names or DOIs that we can use to find them?

I searched by these email addresses and also by pieces of their name like "Simone" or "Surace" and don't see other accounts that look like they're the same person (though lots of people with a first name of Simone).  I also searched through author first and last names and don't really see anyone who I can identify as the same person there, either.

This search also doesn't bring it up as an author anywhere.  https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=Surace&sort=relevance&commit=Search

So any more info they can give might be useful. It also isn't anything I find on google that is at dryad if I put in a search like this.

`Simone Carlo Surace site:datadryad.org`

I'd also expect that it might show up at DataCite but don't see much from google there, either.

`site:datacite.org surace`

Maybe they began a dataset 2 or 3 years ago and never bothered to submit it? Even then, I believe a some piece of it would remain in our database.

**Comment by jleighherzog** [comment]
The author has provided the following information:
Article DOI: https://doi.org/10.1371/journal.pone.0142435
Dataset DOI: https://doi.org/10.5061/dryad.k3f5p (doesn't work, this is what's provided in the published article)
Are you able to find any record of the Dryad DOI?

**Comment by sfisher** [comment]
@ryscher Will probably need to investigate since this is before my time and was from the old Dryad system since it's from 2015.

**Comment by ryscher** [comment]
This item was submitted to the v1 system, but never published. The history is:
- submitted by user on 2014-12-09, and went into peer_review status
- on 2018-05-10, the system detected it had been in peer_review too long, and returned it to the submitter's control
- Dryad v2 launched without migrating this item, since it was too old

Although the user entered payment information into the v1 system, the payment was not applied, since the item was not published.

Should we migrate and publish it now?

**Comment by jleighherzog** [comment]
Can you migrate it and place it in "Submitted" status (do NOT publish) so that we can curate the data first?

**Comment by ryscher** [comment]
10.5061/dryad.k3f5p is now available for curation.

**Comment by jleighherzog** [comment]
Thank you!
