### ISSUE TITLE
Associate Daisuke Muramatsu's ORCID ID (0000-0001-8767-1488) with email address

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1247]
ORCID ID: 0000-0001-8767-1488

Current email: muramatsu.daisuke.a86@kyoto-u.jp
Previous email(s): muramatsu.daisuke.45z@st.kyoto-u.ac.jp; muramatsu.daisuke.a86@kyoto-u.jp

**Comment by sfisher** [comment]
Ok.  I updated this email address for their account.

I do not see any previous accounts from them.  I searched by their name and those other email addresses.  Also not coming up as an author in anything that has been published in Dryad in the past.  https://datadryad.org/search?utf8=%E2%9C%93&q=Daisuke+Muramatsu

If they believe this is incorrect, then it seems like we might need more information in order to find information about any previous accounts.
