### ISSUE TITLE
Add more spacing between "upload pending files" and "back to describe dataset"

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1264]
![Screen Shot 2021-05-06 at 2 06 19 PM](https://user-images.githubusercontent.com/25755963/117365579-59257b00-ae74-11eb-928d-61c51a94186e.png)

On stage/production there needs to be more spacing between the two buttons like how it appears on dev

**Comment by sfisher** [comment]
Hi Cassiano,

Most likely it is because the CSS changes are local to the React code and I'm not sure if Webpack really compiles the CSS there when it installs other things since we're using Sprockets for the CSS for everything else.

All the other CSS we have comes from Joel's "UI Library."

I think make these styles work the same as the rest will be the easiest way to fix.
- Add them to stash/stash_engine/ui-library/scss/_upload-file.scss .
- Compile the scss again like it says at https://github.com/CDL-Dryad/dryad-app/blob/d65cb22dd9a09a86f7ce41aedd09a92a773d9eaf/stash/stash_engine/ui-library/README.md  with `gulp build`.
- Then in the react code, just reference standard styles that come from the global general styles.  Just give them unique names that are similar to Joels "Block Object Modifier (BEM)" syntax.

The other option is to pre-compile the couple of small styles you have separately with Webpack, but I think it's easier to keep all styles in one place and served the same way right now.
