### ISSUE TITLE
Unable to edit from 'In Progress' status

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1265]
**Bug description:**
Both the submitting author and Dryad staff are unable to edit submission from 'In Progress' status. In the submitting author's view, the option to "Update" is greyed out (unavailable to select). 

Title: Evolutionary tradeoffs between male secondary sexual traits revealed by a phylogeny of the hyperdiverse tribe Eumaeini (Lepidoptera: Lycaenidae)
DOI: 10.5061/dryad.tqjq2bvz9

**Expected behavior:**
When a submission is 'In Progress', the author should be able to select the option to 'Update' to return to editing mode

**Comment by sfisher** [comment]
Hi @jleighherzog 

Can you be sure she is looking in the correct place?  The things I see about the dataset seem fine and she has four in-progress datasets that she has already begun editing and this one is one of them.

I think she is just looking in the wrong place.

This is an example of a line from the bottom table for *submitted* datasets that are already being edited.  It is grayed out and unavailable since it's already an updated version that is being edited.
![Screen Shot 2021-05-07 at 1 51 13 PM](https://user-images.githubusercontent.com/105433/117507658-3363a900-af3c-11eb-95c9-2220fcef0e97.png)

So instead it shows in the top *in progress* table like this.  She should be able to click *resume* to continue editing or *delete* to discard the in-progress version.
![Screen Shot 2021-05-07 at 1 51 04 PM](https://user-images.githubusercontent.com/105433/117507661-3494d600-af3c-11eb-95c4-f2c89307db59.png)

If there is some reason it doesn't show up for her or something else wrong in her interface, let me know, but I tested the query that show her datasets and it should show up correctly for her as long as she clicks *resume* instead of trying to click the grayed out *update* button.

**Comment by sfisher** [comment]
@jleighherzog If you'd like me to set this dataset so that you're the current editor instead of the user, let me know.

Once I set you as the current editor, you can go in and either make changes or click the button at the top of the screen to discard the changes they started.

**Comment by jleighherzog** [comment]
@sfisher : The author was able to submit and this dataset is now published. From the author: "For some strange reason, the update option became available again and I was able to submit the new data." Thanks for your help. I'll let Ari know this has been resolved.
