### ISSUE TITLE
Dev config updates to point to stage

### ISSUE THREAD

**Issue by marisastrong** [CDL-Dryad/dryad-product-roadmap#131]
Merritt will be eliminating it's dev environment and utilizing stage for testing.  Dryad dev will need to be configured to point to Merritt stage environment.  When this work is complete, inform Merritt so Merritt can begin to remove the dev environment.

I'm not sure exactly what this entails on the Dryad Dev environment so this ticket should be updated to include the details.

**Comment by sfisher** [comment]
On the dash side I believe this will be something like the tasks below.  We'll need to update both Dash2 and Dryad because both use the same Merritt-dev collections.  It would be something of a bonus if Merritt created separate collections for Dash2 vs Dryad dev.  Right now we're piling both into the same collections which mean things from Dash2 end up showing up on Dryad-dev and things from Dryad-dev end up showing up in Dash2-dev.  Not a huge, huge problem, but it would make things cleaner if they were different collections.

- [ ] Reconfigure the used campus endpoints to point to Merritt stage and with the correct collections, password, etc for sword submissions.
- [ ] Remove all old datasets that used to be on Merritt dev because those downloads will no longer work (notify Daisie and Ryan first).
- [ ] Reconfigure harvester.  It has to know which collections it is harvesting into SOLR (and updating state for) for which of our environments.
