### ISSUE TITLE
Dataset published in error DOI: 10.5061/dryad.x95x69pgj

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1348]
This dataset was published in error, please remove the published files. 
The submission needs to be returned to 'Author Action Required' status: 

Title: Data from: Annual and perennial Medicago show signatures of parallel adaptation to climate and soil in highly conserved genes
DOI: 10.5061/dryad.x95x69pgj

**Comment by sfisher** [comment]
Ok.  It is not published now and set to Author Action Required.

We cannot remove published items from Zenodo automatically, but it's manual on their side.

So I added an embargo until November (when I saw they originally had one) at Zenodo.

If it gets re-published again then it should remove the embargo at Zenodo, however, if the dataset gets rejected and never published. let us know since we'll need to email them and do a manual removal.
