### ISSUE TITLE
Unable to locate submission in database DOI: 10.5061/dryad.n2z34tmx5

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1406]
I've been working with the author of the submissions listed below. I'm unable to find a result for this submission when I search: 10.5061/dryad.n2z34tmx5 (previously I was able to view it). Additionally, both submissions have disappeared from her account view (previously, they were both available). 

Could you try to link these submissions to her account please? 

Author: Lyska Emerson
Email: lyska.emerson@hsc.utah.edu
ORCID ID: 0000-0002-2367-6578

Title: Data from: Structural variation and its potential impact on genome instability: novel discoveries in the EGFR landscape by long-read sequencing
DOI: 10.5061/dryad.n7kp793

Title: Partially phased EGFR landscapes
DOI: 10.5061/dryad.n2z34tmx5

FYI: My plan is to copy over the metadata provided in this dataset 10.5061/dryad.n2z34tmx5 and transfer it to 10.5061/dryad.n7kp793. So, if you reinstate both submissions, I'll be able to proceed.

**Comment by sfisher** [comment]
Hi @jleighherzog,

This user is using two different ORCID accounts for logging into Dryad.  A new account at https://orcid.org/0000-0002-2367-6578 and an old account at https://orcid.org/0000-0001-6413-8680 .  She should only really be using one account.

The first dataset is at https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=n7kp793&sort=relevance&all_advanced=1&commit=Search&utf8=%E2%9C%93 and at https://datadryad.org/stash/dataset/doi:10.5061/dryad.n7kp793 .  It looks like this is the one they note in their article at https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0226340 but it was never published and the curation status shows that author action is required for publication.

@ryscher This seems familiar.  Is this the one you needed to retrieve out of the old Dryad temporary storage because the author never published it, but began citing and referencing it anyway?

The other dataset does not exist as far as I'm aware (10.5061/dryad.n2z34tmx5).  Do you have any more information about what the author did or when it was started? It seems likely they didn't submit it from a long time ago or else they recently started the dataset and they (or someone else) deleted it before submission.  Only submitted versions are saved, so if the author deleted it or a curator reverted and there were no submitted copies then it is gone.

It is very unlikely that it just disappeared after submission since there is no longer a record of it by name, title or doi in either Dryad or in the Merritt system.  We have no way to delete anything from Merritt without putting a time-consuming manual request to them, so it's very unlikely that it disappeared spontaneously unless it was never really submitted to begin with.

**Comment by jleighherzog** [comment]
@ryscher : 

Could you kindly link this author's account with the ORCID ID below? She's confirmed this is the preferred ID.
Additionally, the submission below should also be migrated to this account, if possible. 

Author: Lyska Emerson
Email: lyska.emerson@hsc.utah.edu
ORCID ID: 0000-0002-2367-6578

Title: Data from: Structural variation and its potential impact on genome instability: novel discoveries in the EGFR landscape by long-read sequencing
DOI: 10.5061/dryad.n7kp793

**Comment by ryscher** [comment]
The author's account has been updated to link the ORCID and email. The dataset is now associated with this account.
