### ISSUE TITLE
Authors unable to add ORCID IDs to dataset (DOI: 10.5061/dryad.j9kd51cd5)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1433]
The authors of the dataset below receive an error message when attempting to add their ORCID IDs. 
Dr. Gibbs receives an error message that reads: “You’ve already added your Orchid to this dataset”. 

Title: Genomic signatures of inbreeding and mutation load in a threatened rattlesnake
DOI: 10.5061/dryad.j9kd51cd5

Dr. Gibbs: 0000-0001-7461-3393
Dr. Ochoa: 0000-0002-3271-3684 

Are you able to manually add these IDs on their behalf?

**Comment by sfisher** [comment]
I added the orcid for Dr Gibbs manually.  The other author already had the orcid set correctly.

Seems like something strange might have gone on and it looked like Dr. Gibbs was invited to add his ORCID twice and successfully added it but it hadn't updated his author information (maybe because of two invitations).  

It's updated now.
