### ISSUE TITLE
Unable to locate submission after using Force Edit feature (DOI: 10.5061/dryad.931zcrjkv)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1453]
**Bug description:**
Attempting to assist an author with their file upload, I was unable to access the submission "In Progress" so I selected the "Force Edit" feature. I noticed there were no files uploaded, so I selected the option to 'Cancel and Discard Changes'. Now, I'm now unable to locate the submission in our system. 

Title: Survival of calcareous and siliceous species on calcareous and siliceous soils over four years of reciprocal transplant experiments
DOI: 10.5061/dryad.931zcrjkv

Would you be able to find it and reinstate it? 

This has happened to me before when I attempted to exit from the Force Edit mode. Ideally, we should have the option to cancel out of that screen but, if it wasn't designed that way, let me know.

**Comment by jleighherzog** [comment]
Submission files attached.
[Nemer et al. ReadmeTemplate.txt](https://github.com/CDL-Dryad/dryad-product-roadmap/files/7122128/Nemer.et.al.ReadmeTemplate.txt)
[Data_Nemer et al..csv](https://github.com/CDL-Dryad/dryad-product-roadmap/files/7122129/Data_Nemer.et.al.csv)

**Comment by ryscher** [comment]
Sorry, the metadata is gone. That's why the Force Edit feature is labeled a "Dangerous Action". 

We can look at ways to make this process more error-proof, but it was designed as a last resort to fix a dataset when nothing else would work. If the feature is being used frequently, I would want to understand why so we could design a better process overall.
