### ISSUE TITLE
Associate Mark Kirkpatrick's ORCID ID (0000-0002-3791-2201) with the preferred email address

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1485]
Please associate Mark Kirkpatrick's ORCID ID with the preferred email address: 

ORCID ID: 0000-0002-3791-2201
Preferred email: kirkp@mail.utexas.edu
Other email address: kirkp@austin.utexas.edu

Additionally, can you transfer this submission to the user's Dryad account: 
Title: Heterogeneous histories of recombination suppression on stickleback sex chromosomes
DOI: 10.5061/dryad.jm63xsj7s

**Comment by sfisher** [comment]
Hi Jess,

There is something weird going on with this user and this request.  Please let me know what you believe is the correct thing to do after I explain.

The ORCID ID in the ticket (0000-0002-3791-2201) isn't Mark's ORCID, but is the ORCID for someone named Jason Sardell. https://orcid.org/orcid-search/search?searchQuery=0000-0002-3791-2201

Mark's ORCID is 0000-0002-0039-4172 .  See https://orcid.org/orcid-search/search?searchQuery=0000-0002-0039-4172 .

There are two datasets where he is an author:  https://datadryad.org/stash/dataset/doi:10.5061/dryad.jm63xsj7s which was submitted under Jason's account and https://datadryad.org/stash/dataset/doi:10.5061/dryad.6m905qg0d which was submitted under Mark's account.

His authorship information is also connected to Jason Sardell's ORCID acount, so he maybe logged in with Jason's account instead of his own.

I don't have a problem moving all these things to be under Mark's account if you believe he is the one that should really own all of them.  That ORCID is 0000-0002-0039-4172 .

I want to be sure this is really the right thing to do first. IDK why he's using Jason Sardell's account for things and wants us to put his own email on Jason's account.  I also want to be sure that if we fix the issues and put all the datasets into Mark's account (ORCID 0000-0002-0039-4172) that we're not causing a problem for Jason Sardell.

Let me know what you think is going on with these two users and what the right thing to do is.

**Comment by jleighherzog** [comment]
@sfisher : Thanks for your patience while I worked to sort this out on my end. 

Mark Kilpatrick has confirmed that it will be best to migrate this dataset to his account: 10.5061/dryad.jm63xsj7s. Then, we should have the correct ORCID ID associated with Mark who is the sole author listed for this dataset AND the invoice will be directed appropriately to Mark Kilpatrick for payment. FYI: Jason Sardell has been in the loop on our correspondence and is aware of these pending changes. 

Here's Mark Kilpatrick's ORCID ID: 0000-0002-0039-4172

Note: Is there any need to make edits to the other dataset you mentioned? 10.5061/dryad.6m905qg0d
The submitting author for this dataset is Sally Potter and, although Mark Kilpatrick is listed as a co-author, I don't think there are any issues to address there. 

Let me know whether you require any additional information.
