### ISSUE TITLE
Brainstorm fun: if you could refactor, re-think  any part of the Dryad system to strengthen/optimize what would those things be?

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1523]

**Comment by sfisher** [comment]
These are some things I could think of.

- The metadata entry page does updating with rails and the "save as you go" is a
  bit clunky.  We may want to refactor some of it into React or more
  javascript-focused technology.  However this would be a pretty big project and
  it's mostly working right now.
  - It might help us prepare for the future to work with the technology if we'll be using it for more pluggable metadata schemas from outside collaborators or domain-specific ones.
  - Maybe we could transform sections at a time.
  - We could start thinking about how we handle/store "Any metadata you want" if
    we are going that direction. How to store?  Is it searchable? How to go to datacite?
- We're using both webpack and sprockets (the asset pipeline) for managing things such
  as images, javascript.  It would be nice to move to only 1 system instead of
  managing two.  But a lot of annoying work.  Also useful for later upgrades to Rails 6
  or 7.
  - Related: we have warnings about the size of some of our libraries in webpack and
    it suggests they should be smaller.
- We have a bunch of old or problematic Zenodo transfers that are sitting around in our
  dashboard approx 400.  It would be nice to clean them up so it's easier to see
  when/if new things go wrong.  Also large transfers above hundreds of GB mostly
  fail, though some have gone through and we may need special handling for them.
- Curators said there are some people with problems uploading and they think it's a
  problem we need to look at, but that they haven't filed any tickets about it yet.
  This may be hard to troubleshoot since it works for curators and us.  May be
  dependent on network, firewalls or browsers or other local conditions for some
  people.
- When is Rails 5.2 end of life? I couldn't find good information, but once Rails 7 is
  fully released, I wouldn't be surprised to see it happen in 2022 sometime.
