### ISSUE TITLE
Withdraw 'In Progress' datasets which have not been previously submitted

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1636]
Please remove/withdraw the following datasets which are 'In Progress' and do not have a previous version to revert to. The reasoning is noted below each dataset.

- 10.5061/dryad.v41ns1rz3 and 10.5061/dryad.k98sf7m79	

The author has confirmed the dataset that should be retained is 10.5061/dryad.p2ngf1vr8.

-  10.5061/dryad.79cnp5hx5	

The author has decided to submit the data directly to Zenodo.

- 10.5068/D1XX0R

The author has informed us that they will not proceed with dataset submission.

- 10.5061/dryad.mw6m905zd, 10.5061/dryad.1vhhmgqvj, 10.5061/dryad.8pk0p2nq3, 10.5061/dryad.qbzkh18k4, 10.5061/dryad.4qrfj6qc9, 10.5061/dryad.4f4qrfjdw	

The author was experiencing issues uploading data files and will retain dataset 10.5061/dryad.mcvdnck2s.

- 10.5061/dryad.0vt4b8h0w	

The author has confirmed the dataset that should be retained is 10.5061/dryad.1rn8pk0vd.

- 10.5061/dryad.j3tx95xd

A duplicate dataset was published 10.5061/dryad.dv41ns20d.

**Comment by Ariana-Orona** [comment]
- 10.5061/dryad.9s4mw6mjf	

Author does not want to pay the DPC and would like to withdraw the dataset.

**Comment by sfisher** [comment]
This seems like a very weird ticket.  It seems like a lot of these are just abandoned datasets, which undoubtably we have a lot more of.  It seems like it might be a better use of our time not to work on this and to work on general cleanup instead of a bunch of one off special requests for something we should be doing another way.  (Think cattle, not pets.)

**Comment by ryscher** [comment]
We already have a "cattle management" process in place for these datasets. The task `remove_old_versions` runs monthly, and removes unsubmitted datasets that have been abandoned for more than a year. I'm closing this ticket, since the datasets mentioned above will be automatically cleaned within the next two months.
