### ISSUE TITLE
Dataset not populating 'Review and Submit' page - DOI: 10.5061/dryad.bg79cnpch

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1643]
Author unable to 'Submit' dataset as the 'Review and Submit' page does not populate. Can you please research this and allow the author to submit the dataset?

Title: Data from: "Lung evolution in vertebrates and the water-to-land transition"
DOI: 10.5061/dryad.bg79cnpch

**Comment by Ariana-Orona** [comment]
![image](https://user-images.githubusercontent.com/80363462/154130325-9bcccf8e-61d2-42a4-b296-6d6df898b553.png)
 
View does not change and has maintained the issue.

**Comment by sfisher** [comment]
This author uploaded 15,169 different files.  We only support lists of up to 1,000 files.  if they want a huge number of files then they would need to put them into containers such as `zip` or `tar.gz` files.  The number of files makes the review page take an extremely long time to load.  Even if it loaded, it wouldn't allow submission because the maximum number of files was exceeded.

We may be able to re-download all her files and re-upload as a large zip file, but that may take some time.

**Comment by Ariana-Orona** [comment]
@sfisher Got it, that's a lot! The author has resubmitted the files in a new dataset (10.5061/dryad.vdncjsxx1). The author mentioned that they would want to copy some of the information contained within the previous dataset (10.5061/dryad.bg79cnpch) so I will reach out to confirm what information they need and if we can withdraw 10.5061/dryad.bg79cnpch.

**Comment by Ariana-Orona** [comment]
@sfisher Author confirmed it is OK to delete this dataset. Can you please remove this 'In Progress' dataset as well?

**Comment by sfisher** [comment]
Thanks for letting me know, @Ariana-Orona .  I removed this dataset with the large number of files.

I also put a ticket in our backlog to disallow adding this many files earlier in the process (on upload page). We used to have that, but with an upload refactoring a year or so ago, the early check seems like it was removed and now it's not checking again until review/submission.
