### ISSUE TITLE
Dropbox URL upload not working

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1648]
User experiencing uploading data files via URL from Dropbox. The error states "URL cannot be downloaded, please link directly to data file" for each of the links below:

- https://www.dropbox.com/sh/nlib7p4nce5cuj6/AADaBa3phb3vnwcogLP1HJ7aa?dl=0&preview=G3-Max-Temp.zip
- https://www.dropbox.com/sh/nlib7p4nce5cuj6/AABO46gfEkTAzXEuNfFBNJAqa/G3-Max-Temp.zip?dl=0
- https://www.dropbox.com/sh/nlib7p4nce5cuj6/AADaBa3phb3vnwcogLP1HJ7aa?dl=0&preview=README.txt
- https://www.dropbox.com/sh/nlib7p4nce5cuj6/AAD6ApAImBhRrVSpuv3701ega/GLENS-Max-Temp.zip?dl=0

I can provide the Dropbox link the author provided and additional examples, if needed. Both Mariah and I attempted to upload via URL on Google Chrome.

**Comment by sfisher** [comment]
In order to get files from Dropbox they must download directly without user intervention and not show a web page.  If you go to a URL for a file and it doesn't start downloading (but shows an additional web page before allowing a download) then it isn't usable in our system.  These show a warning that a file is too big or else the file isn't found.

The links this user puts in result in the following (see screenshots):

![Screen Shot 2022-02-14 at 12 44 07 PM](https://user-images.githubusercontent.com/105433/153943722-ad7dfd74-9c6b-433c-84b1-e39b44895f0d.png)

![Screen Shot 2022-02-14 at 12 44 07 PM](https://user-images.githubusercontent.com/105433/153943847-dd2f63db-3d0b-459f-bd8a-0d21d1557477.png)

**Comment by sfisher** [comment]
How to fix may depend on the service and what each service does before allowing a download.  Unfortunately Google (and also it seems sometimes Dropbox) puts pages in before allowing downloads of files over a certain size.  For smaller files it may work, but not as much for larger ones (depending what the service does).  Users also need to be sure they're using the sharing URLs ("anyone with URL may download") for it to work and not just any URL from the file sharing service.  They usually have to get these by right-clicking on each file and getting the sharing URL from the dialog box.  It seems like of the file sharing services, Box may have caused us fewer problems.  Google gives "virus scan" warnings if attempting to download files over a certain size and maybe dropbox is doing something similar with these previews (or maybe the user just used the wrong URLs).

Sometimes we can get around some problems by updating our code to try to work around changes the services make, but they still don't allow direct downloads of all files and they don't particularly care about doing anything in a standard way since they only want to lock people to only use their service.

Standard HTTP servers (web servers) should almost always work since it's a standard protocol that doesn't change, so if someone can put the files on a web server in their lab or someplace and give URLs for files then that is the best route.  But they need to leave the files there when they submit the dataset since they're not downloading until they submit.  (They're just checked in the UI.)  This is similar to what we do with the FTP server and having users put files there.
