### ISSUE TITLE
Revert datasets back to most recent 'Published' version

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1649]
Can you please revert the following datasets back to their most recently 'Published' versions?  The authors have removed data files and/or metadata after requesting to remove their published datasets. I have already been in correspondence with them and neither has confirmed there are any concerns regarding the integrity of the data, ethical issues, or legal risks involved with the data. I cannot curate the revisions and request modifications due to this.

- 10.5061/dryad.mkkwh711p	
- 10.5061/dryad.rr4xgxd99

**Comment by sfisher** [comment]
Hi Ariana-Orona

Can you clarify what you'd like me to do for 10.5061/dryad.mkkwh711p ?  I looked at all 4 versions and it looks like all 4 versions have the same files which are `Draft.docx` and `statistics.docx` .

I'm able to view it ( https://datadryad.org/stash/dataset/doi:10.5061/dryad.mkkwh711p ) and edit it (from https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=mkkwh711p&sort=relevance&all_advanced=1&commit=Search&utf8=%E2%9C%93&tenant=&editor_id=&curation_status= ) without issues.  If you have more info about what needs to be changed, it would help me since I don't see missing files or a problem editing it right now.

---
For 10.5061/dryad.rr4xgxd99, version 4 had the files, version 5 removed them and I downloaded and re-uploaded the files again in version 6.  That version should appear as the latest version you can edit/curate with the files back.

**Comment by Ariana-Orona** [comment]
@sfisher thanks so much! I added the metadata from the most recently published version 10.5061/dryad.mkkwh711p so this is good to go.
