### ISSUE TITLE
Revert to published version (DOI: 10.5061/dryad.sqv9s4n25)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1665]
Can you return this dataset to the original published version that was approved for publication on 08/18/2020? Additionally, can you remove the journal information? It seems the related manuscript was rejected and the journal should not be associated with this dataset or responsible for the data publication charge. 

Title: Megakaryocytes
DOI: 10.5061/dryad.sqv9s4n25

The author has edited and/or wiped the metadata and files from the existing, unpublished version so I'm unable to publish it in its current form. 

If you have any questions, let me know.

**Comment by ryscher** [comment]
Reset version 2 to be publicly visible, since that version was published and should have remained. Put the current version in AAR status, since the author tried to forcibly remove all content.

The dataset should be fine as-is now, but if future edits are desired, a new version will need to be created that contains the metadata and data file from version 2.

**Comment by ryscher** [comment]
This dataset went through some crazy changes, as the original author tried to delete the content. We had settled on having the later versions in AAR, but those were later withdrawn by automated processes, resulting in the data being unavailable. So I manually removed the bad versions.
