### ISSUE TITLE
ESA accept notifications and auto status update 

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1737]
For this dataset: **10.5061/dryad.w3r2280sz** we received a notification of acceptance from the editorial office via Helpdesk and we were required to manually update the status from 'Private for Peer Review' to 'Curation'.  

Because the titles listed below are integrated (Ecological Society of America) shouldn't the PPR status of these submissions auto-update when a system-generated notification of acceptance is received? 

> Ecological Applications
> Ecological Monographs
> Ecology
> Ecosphere

**Comment by ryscher** [comment]
Manuscript number attached to dataset: 21-0521
Manuscript number provided by journal: EAP21-0521.R1

Dryad is "smart" enough to ignore the version number ".R1", but we don't attempt to guess the prefix for each journal. We expect users to enter the same manuscript number that the journal gives us.

Also, the article was accepted January 5th, but we didn't receive the dataset until May 8th, so the submitter should not have chosen "peer review". In the v1 system, we had a mechanism to prevent this from happening, but we didn't include that mechanism in the current system since it's a rare occurrance. And it would not have worked in this case anyway due to the manuscript number mismatch.
