### ISSUE TITLE
Transfer ownership of dataset to submitting author's account (DOI: 10.5061/dryad.269126c)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1741]
Please associate this published dataset: 

> Title: Data from: Association genetics of growth and adaptive traits in loblolly pine (Pinus taeda L.) using whole-exome-discovered polymorphisms
> DOI: 10.5061/dryad.269126c

With the submitting author's Dryad account: 
> Name: Zhengyang Wang
> ORCID ID: 0000-0001-5023-3759
> Email address associated with ORCID ID: mengmeng.lu@ucalgary.ca
> Preferred email address for Dryad profile: mengmeng.lu3510@gmail.com

(Q: Can the emails be different? Does the Dryad profile email need to match the one associated with the ORCID ID? This is the request I received from the author: 

"I linked this ORCID with my work email: **mengmeng.lu@ucalgary.ca**

However, in my problematic dataset, I might use another email: **mengmeng.lu3510@gmail.com**

Can you combine my two datasets and only retain **mengmeng.lu3510@gmail.com** (please delete another email **@ucalgary.ca)**?"

**Comment by sfisher** [comment]
Hi Jess,

I looked at these users and what they're asking for is a littleconfusing to me.

There are three users involved here in what they mention:

```
first user
id: 31264
name: Mengmeng Lu
email: mengmeng.lu3510@gmail.com
orcid: (none since this is an old user who never migrated their account)

second user
id: 51679
name: Mengmeng Lu
email: (added) mengmeng.lu3510@gmail.com
orcid: 0000-0001-5023-3759

third user
id: 82206
name: Zhengyan Wang
email: ?
orcid: 0000-0003-3244-1954
```

I transferred the dataset they mention from the first user to the second user. (That first user hasn't logged in or migrated their account since 2019).

I added the preferred email address to our user record for the second account.

I'm not sure where the third user comes into it which is the only user with the name of Zhengyan Wang that I could find.  I think that user has a couple of other datasets.

The *user* information isn't used for much on public pages.  It's mostly used for us to track who has logged in and is using the system and their permissions.  Most *users* only have a name and orcid and ORCID doesn't always give us emails for a user.  The email privacy can be set in the ORCID system to public, private or only shared with trusted 3rd parties (which we are).

*Authors* are people that are entered for a dataset and they are completely separate from *users*.  *Most authors are not users* of our system. All the main *author* information but ORCID can be changed directly by editing the metadata in their dataset.

One *author* gets their ORCID set to be the same as the main *user*'s ORCID.  That *author* is the "corresponding author."  We send emails to that *author* email address unless it's missing and then falls back to the *user* orcid email (if we have it). We require an email address for that author on submission so we can send emails and so that people can contact an author for anything that needs to happen with the dataset.

They should be able to change the public author information to display whatever they want for this *author*.  We only allow one email address per author.

However it will still have an orcid, so someone could look up that user on the ORCID system and see a name.  Whether they want to expose any email address on the ORCID system is completely up to them.  (We don't expose this email if we have it except for pre-filling it for one of the authors where it can be changed).

If they want to have an untraceable contact for a dataset, the easiest way might be for them to create a fake ORCID account with a different name and not to expose the email address on ORCID.  They could log in with the fake ORCID account and then we could transfer the secret dataset to the ORCID account with bad information.  This all flies in the face of the purpose of ORCID (associating a person's research work) and is very weird for openness and accountability of research work, but there may be political or other reasons that someone might want to keep their authorship private.
