### ISSUE TITLE
Filename filtering

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#175]
The current system allows virtually any characters in a filename. This is potentially dangerous, as some characters will cause problems when the file is used in other repositories, browsers, and partner software.

For example, Dryad has had problems in the past with some web browsers not allowing downloads of files whose names contain a comma. And even though the current system allows upload of files whose names contain an asterisk, most browsers will replace the asterisk when the file is downloaded.

We should develop a list of restricted characters, and when a file is being uploaded with a restricted character, force the user to change the name (or notify them that the name will be changed automatically).

**Comment by briri** [comment]
Since we're dealing with a mix of conflicts between valid characters for a URI, valid characters for different browsers and potentially valid characters on various file systems I think we should simplify things.

For example can we make a rule to only accept: 
- Alpha numeric
- dashes
- underscores
- spaces
- periods

I'm not sure how many files would be in violation of these rules. We could display the 'converted' filename in a textbox and a note that the filename was adjusted. The user could then edit the filename (but still restricted to the above characters).

What do you think @ryscher @sfisher and @dlowenberg? I'm not sure if this would put too much burden on the user
