### ISSUE TITLE
Must add resource_id to the curation activity log and track versions

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#176]
We need to track the resource_id (essentially the version) because public display should only work for submitted versions (to Merritt) that also have embargoed or published states.

This is a per-version thing.  Someone may have a version which is public (submitted to Merritt and published by curators) and they may be working on a version of the same dataset that hasn't been published or submitted to Merritt).

We solved some of the state complexities by locking curation state changes while a Merritt state is anything but 'submitted' (to merritt).

The current table of stash_engine_curation_activities is probably ok except it should belong to resource (the version) rather than the identifier (the dataset).  We can probably get rid of the extra "display" table so long as we have queries that ignore the extra "Status Unchanged" states because we're usually looking for a final state for an identifier (dataset) or the final state for a resource (version).

**Comment by briri** [comment]
Removed old `stash_engine_identifier_state` and replaced with a method on `StashEngine::Resource` that retrivies the curation status if the Merrit state is 'submitted' otherwise it reports 'Unsubmitted' as the status.

Added a `resource_id` to the `stash_engine_curation_activities` table and updated methods on `StahEngine::Identifier` and `StashEngineResource` to work with the new table structure

Added 2 rake tasks: 1 removes orphaned records from `stash_engine_curation_activities` and the other seeds the `resource_id` and adds a record for any Resource not having a corresponding CurationActivity

**Comment by briri** [comment]
spoke with @sfisher and we are going to table this one for now. Its a larger can of worms than original thought.
