### ISSUE TITLE
Investigate routing of UCSB submissions

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1803]
This submission wasn't auto-assigned to our UCSB curator, Renata Curty: **10.25349/D92C9C**
She manually assigned it to herself and then I assigned the revised dataset to her.

Was the incorrect tenant selected upon submission and, therefore, auto-routing wasn't activated?

**Comment by sfisher** [comment]
Hi @jleighherzog ,

I traced through the code that makes these changes and re-assigns curators step by step.  I couldn't see how any logic that would've made it skip re-assigning Renata after that latest submission from the original user (based on the values in the database).

The ucsb tenant looked correct and I don't believe was changed.

I'm not sure if this was ever a dataset that had something manually changed in the database since that might mean the data was somehow different than what I'm looking at now.

If there are other examples of this happening, I might be able to find something that is common to all of them, but I currently don't see how it would've been skipped to reassign the correct curator.
