### ISSUE TITLE
De-activate curator account

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1817]
Curator Iman Nematollahi's last day was June 12. Please proceed with the offboarding procedure.

**Comment by ryscher** [comment]
All technical accounts are reset/deactivated. Some notes:
- On the Curator VE, there is a dataset in C:\DryadData\inematollahi — I left this in place, since the dataset is AAR, so the eventual curator will probably want the files.
- On the FTP server, I cleaned up several abandoned folders relating to datasets that Iman had finished processing. I know we don't have an FTP expert leave often, but it is best if the curators can remove such files before they leave, to reduce the chance of mistakes.
- Files still on the FTP server that were previously being managed by Iman, and should now be managed by someone else:
    - MHahn — doi:10.5061/dryad.51c59zw8g — AAR
    - RHuganir — doi:10.5061/dryad.ttdz08m0b — Curation
    - RMadhura — doi:10.7272/Q69S1P9G — Iman uploaded the files to Dryad, but the submitter is working on a new version, so the files may still be needed.
