### ISSUE TITLE
Additional storage space in virtual environment (PRIORITY)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1824]
With more traffic in the virtual environment, there's a need to increase the storage space. Curators run out of storage space more frequently which can halt their work on larger datasets. Unfortunately, I don't have a recommendation as to how much more space is required. Your best estimate/guess is also mine. :) 

_Note: We are working to set up a weekly schedule to remove files._

**Comment by ryscher** [comment]
When I did the last rebuild, I cleaned a lot of temp files out of the directories owned by former curators. Hopefully, this will provide enough space, but let me know if you still run into space issues.

**Comment by ryscher** [comment]
Moving this back to the backlog, because the curators determined they would like another 2TB. I think this would be best as an additional disk, so it can be managed separately from the primary Windows disk. This would allow us to exclude it from backups (it would only hold temporary data files), and if needed we could expand/replace it more easily.

**Comment by jleighherzog** [comment]
@ryscher : VE might also need increased speed. Amelia will discuss w/you today.

**Comment by ryscher** [comment]
VE is running low on memory due to curators leaving apps open; primarily browsers and image viewers. Windows makes it too easy to leave things running. Amelia will discuss whether curators can close more things down, but curation is more difficult if the curators need to constantly close out of apps and set them up again when they return. Ryan will investigate increasing the memory available on the machine.

**Comment by ryscher** [comment]
Upgraded the machine that runs the VE from t3a.large (2 CPU, 8GB RAM) to r6a.xlarge (4 CPU, 32GB RAM). Added a new 2TB data disk as drive D. The data disk is formatted with a GPT partition, so it can be expanded beyond 2TB if needed in the future.
