### ISSUE TITLE
Published dataset auto-withdrawn

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1842]
This dataset was published on 3/21/2021: 

> Title: Perceptual restoration fails to recover unconscious processing for smooth eye movements after occipital stroke
> DOI: 10.6078/D1W69T

The author submitted a new version on 4/28/2022, which was auto-assigned
The submission was auto-withdrawn on 5/2/2022: "status updated via API call"; it's currently unavailable online
Then, an acceptance notice received on 6/22/2022 but that isn't reflected in the Activity Log. 

Questions: 
1) Why was this submission withdrawn? I can't find any related communication. 
2) Can we revisit the logic/workflow rules to ensure that datasets having a 'published' status are not auto-withdrawn? 
3) To whom was it assigned when it was resubmitted on 4/28/2022? 
4) Depending on why this submission was withdrawn, it might be best to return it to the previous 'Published' status

**Comment by sfisher** [comment]
Hi Jess,

I don't know as much about the journal API integrations as much as Ryan, but to answer your questions as much as I can:

1. Why was this submission withdrawn? I can't find any related communication.

It looks to me like eLife has an API account for managing the submissions that they sponsor.  This submission was sponsored by eLife and it appears they chose to withdraw it.  I don't know their reasoning since this appears to have been done from the API by their API account.  I don't see any code or script withdrawing this from our side and looks like the only path for withdrawing the way they did was through eLife updating the status in the API for this item.  I think it was done by the eLife API account and not by us (whether is was a correct or buggy decision on their part, IDK).

2. Can we revisit the logic/workflow rules to ensure that datasets having a 'published' status are not auto-withdrawn?

Sure, I think. (?) We should wait until Ryan is back since he understands this workflow and how it interacts wtih eLife publishing better.  I'm not clear if this should've ever been published or if it was supposed to be private until the article was published or withdrawn.  I'm not super clear how this worked from the beginning of the flow.

3. To whom was it assigned when it was resubmitted on 4/28/2022?

I believe it was reassigned to the Dryad System.  I believe the only previous curator in the list was Mariah Kenney who is not currently listed as a curator anymore.  There is some code which tries to find another curator when curators no longer exist.  We can look and see if there is some problem and it did something wrong.

4. Depending on why this submission was withdrawn, it might be best to return it to the previous 'Published' status

This may be true.  IDK if eLife would want to pay to sponsor it if they withdrew it on purpose. Though apparently they changed their minds later?  Or maybe they have bugs in their code and withdrew it in error?

I don't have any way of logging into salesforce to see what the referenced ticket says or if it provides better context.  (I tried the user/pwd we have configured and it doesn't let me in to look at anything so I really have no idea if SalesForce is enlightening or just causes more confusion.)

When Ryan is back, I think he'll have a better understanding of the process and what went wrong or happened.  If we need to act on it sooner, we can take actions needed or can try to trace the whole workflow manually.

**Comment by ryscher** [comment]
1. This was withdrawn due to an action taken in the eLife manuscript processing system. As Scott said, it's a little difficult to tell exactly what happened because not all of it was in our system, but here's my best guess: It looks like the author originally created the dataset using the Dryad interface, then subsequently created a new version through the eLife manuscript system. When they were creating the new version, they probably tried to remove the initial version from the eLife interface, which caused the "Withdrawn" status.
2. I'm adding an extra guard in Dryad to prevent the journal API from withdrawing previously-published items.
3. The curator was automatically changed to Ari, since Mariah was was no longer a curator at that time. I assume Ari didn't notice it because it was only in that status for a couple of days before it was shuffled into "Withdrawn" status. I'm updating Dryad to include the curator's name in the note for the future.
4. I have returned the second version to "Curation" status and assigned to Ari. I believe this the author did intend make a new version. It does look like they made quite a few changes from the original submission.
