### ISSUE TITLE
Please investigate “Journal” metadata field settings

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1850]
1. At the top of the first page of the Dryad submission form, if the 'a published article' option is selected AND there's a journal name and DOI present, an error sometimes appears on the final page of the form with a request to fill in the manuscript number. If the DOI is entered in both fields (the ms number field and the DOI field) then I'm able to submit without an issue. Only 1 link to the article DOI is available in the Related Works section (that's a good thing). I've come across this issue 3 times. Here's 1 example: 10.5061/dryad.tb2rbp01v
2. Invoice was created for dataset 10.5061/dryad.m905qfv2x in error, as the journal name was entered correctly and the journal is a sponsoring title. Additionally, the journal appears to have been selected from the drop-down list correctly. Can you investigate why this happened? Datasets related to the noted journal should still be sponsored.
3. Journal names must be selected from the drop-down even if the case and spelling match. Is it possible for our system to automatically link the correct journal name if it is included in our drop-down list without manual selection?

Item (1) is user-facing.
Items (2) and (3) result in queries that are received and resolved by CxORE and HelpDesk.

**Comment by sfisher** [comment]
Here is some info

1. Entered ticket #1858 
2. From what I can see at https://datadryad.org/stash/journals "Frontiers in Immunology" does not have a payment plan with us.  It is a known journal that autocompletes (and did correctly autocomplete and receive an ISSN in this case).  However our database doesn't show any payment plan arrangement for this journal. IDK if that is correct or incorrect and needs to be updated.  I know Ryan was trying to get all the payment plan information in one place so there weren't confusing multiple sources of information but 🤷 
3. I think this is known and people are encouraged to complete from the list or correct if they didn't (it shows question mark). #1859

**Comment by Ariana-Orona** [comment]
@sfisher I must have included that DOI in error. Here is the one I meant to reference for #2 [10.5061/dryad.gmsbcc2q6](https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=%2210.5061%2Fdryad.gmsbcc2q6%09%22&sort=relevance&commit=Search&utf8=%E2%9C%93)

**Comment by sfisher** [comment]
For number 2, it appears to me that the journal name wasn't correctly filled or did not have an ISSN correctly associated when it was published on May 25th and so an invoice was created since there was no ISSN match. https://datadryad.org/stash/ds_admin/activity_log/83871?utf8=%E2%9C%93  There is a note in version 7 that the journal name was corrected after publication in version 6.

This was likely entered incorrectly or the same problem as the (3) above because the journal wasn't selected from the autocomplete.  We don't keep historical information about every journal version change, since it is only associated with the dataset rather than every version in the "internal data" table.

Unfortunately, once an invoice has been issued, we don't automatically void it if something else is changed post-publication, so this is a manual operation to void an index after publication.  It also may not make sense to void long-settled invoices (for example some author moves from a non-sponsoring to sponsoring university and makes an edit long after publication).

**Comment by Ariana-Orona** [comment]
Here is another example.

It appears that, although the journal was included correctly, an invoice was still created, DOI: 10.5061/dryad.n02v6wx0n. The invoice was created on 06/06, which is the same date noted in the activity log next to "Publication Name." It may be so that the journal name was included after the invoice was created, but I wanted to bring this for your review just in case.
