### ISSUE TITLE
Unable to lift embargo on dataset DOI: (10.5061/dryad.dr7sqvb1r)

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1861]
Author has requested that we lift the embargo on dataset 10.5061/dryad.dr7sqvb1r because the related article has been published. Multiple curation team members have attempted and have been unable to change the status to "Published." 

Can you please investigate this issue and let us know how to lift the embargo? Previously, we would select the date, however, this is no longer an option that is available to us when selecting "Published" as the dataset status.

**Comment by sfisher** [comment]
I've manually published this one which was a chore.

It turns out that the journal "blackout" setting make it always reset to embargoed, which Ryan seemed to put that logic in there on purpose (IDK why and I don't understand so much about blackout settings for a journal).

Anyway, after some fun little games, I got it to publish by changing things manually and put in another ticket for Ryan to look at about blackout to be sure the logic is really correct.

**Comment by Ariana-Orona** [comment]
@sfisher Thank you for your help with this! Sorry to hear it was a pain. Would you like us to obtain more examples while we wait for Ryan to return? I have been able to lift the embargo on some datasets, so it was strange I was not able to with this dataset.

**Comment by sfisher** [comment]
I think I saw why it happened.  I believe it only happens with journals with a certain setting at the journal level in the database when I traced through the code.  Most other datasets can be published ok if they aren't associated with a journal with that setting.  So I'll double check with Ryan if that setting is really necessary and preventing publication was intended (since the code seems like it might have been).
