### ISSUE TITLE
Resend activation notification for Dryad email account

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1869]
PRIORITY PLEASE: 
These users are unable to access their Dryad email account. They mention that the link to activate their account expired (within 48hrs of receipt) and they didn't activate in time. I've updated the user management settings to provide them with curator access and edited their profiles to include their Dryad email address. When the select "forgot password", they're directed to contact the admin. I don't find any options to reset. 

Ambika S.
[Ambika@datadryad.org](mailto:Ambika@datadryad.org)
0000-0001-5426-3517

Kailasha Purushothaman
[Kailasha@datadryad.org](mailto:Kailasha@datadryad.org)
0000-0001-8581-8458

**Comment by sfisher** [comment]
Hi @jleighherzog

It sounds like these users need to work with ORCiD if they have forgotten their passwords or are unable to log in at ORCiD.

We do not handle passwords or login aside from Sending people to ORCiD for login and then getting a response from ORCiD that indicates if the login was authorized and obtaining a small amount of information such as the user's ORCiD ID and name.  We don't even get email addresses from ORCiD most of the time unless the user authorizes to release their email to partners or the public from their ORCiD account.

I verified in our database that they logged in to ORCiD (and our system) on the 12th.  In order to log in again they need to log in to ORCiD.  They can try logging directly into ORCiD if they want to try that first for simplicity. Once they are able to log into ORCiD then the exact same login should work for our system.  If they can't get their ORCiD login to work or reset their passwords there then they should contact the ORCiD support.

This similar to the relationship between sites that accept Google or Facebook logins. If you forget your Google or Facebook password, you need to work it out with Google or Facebook and not other sites that may allow you to use that login as a convenience.

**Comment by jleighherzog** [comment]
@sfisher : Thanks for that explanation, Scott. The issue isn't the ORCID ID but the Dryad Gmail email account that they're unable to access.

**Comment by sfisher** [comment]
OH, Sorry!  I misunderstood.

**Comment by ryscher** [comment]
I reset the passwords for the Google accounts.
