### ISSUE TITLE
Move Dryad-CDL folder set to Dryad shared drive

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#1879]
Ryan to move important folder of !! everything !! (https://drive.google.com/drive/folders/1tqy2hFBPDmPheI8yIv0_d1ixKIH6tPgV?usp=sharing) to Dryad Shared Drive (https://drive.google.com/drive/u/0/folders/0AGRSVFPkI06iUk9PVA)  out of Trisha's personal drive

**Comment by ryscher** [comment]
These files can only be moved by their respective owners. This issue with ownership is why Trisha created the Shared Drive, and asked people to move their documents, but apparently the files in this folder were not prioritized.

I propose: 
- I will move the files I own.
- I will contact Jenn and John about migrating the files they own.
- When Daniella is offboarded, her files will be transferred to a Dryad account and can be moved then.
- There are a handful of files owned by the accounts of former Dryad staff, using their non-Dryad accounts (e.g., Jennifer Lin). These documents will need to be copied into new documents to be placed in the new Drive.

**Comment by marisastrong** [comment]
Do I have access to the Dryad Shared Drive?

**Comment by ryscher** [comment]
I have found another way to transfer the documents in bulk, but they will be converted to Microsoft Office format instead of Google format, and they will lose any edit history. 

@marisastrong It looks like you're not currently on the Shared Drive. I can add you when we get these documents sorted out.

**Comment by ryscher** [comment]
Since John Chodacki had ownership of a higher level folder, we asked him to try moving the folder into the Shared Drive. This still failed, but with a different error message: "Folders can't be moved into shared drives yet".

Since the error message implies that Google will eventually allow folders to be moved, we will leave the folder as-is for now, and try again in the future. We may recommend that people stop adding new files to this folder to prevent the issue from becoming worse.
