### ISSUE TITLE
Curators unable to access the virtual environment

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1891]
When attempting to log into the virtual environment, multiple curators receive the following error messages:

![image](https://user-images.githubusercontent.com/80363462/180046813-bbba3098-55ce-4737-a39d-c4a58c06b596.png)

Can you please investigate this and let me know if we need to change anything to log in?

**Comment by jleighherzog** [comment]
Thanks for prioritizing this! It's a critical one.

**Comment by sfisher** [comment]
I get a similar thing: "We couldn't connect to the remote PC because of a licensing error. If this keeps happening, contact your network administrator for assistance.  Error code: 0x101."

I was able to reboot the machine from the AWS web console, but it didn't change the problem.  I tried to connect through Remote Desktop from the Amazon control panel to the Administrator account but I don't have the correct credentials to do anything and can't get in under my own account.

@ryscher If you know what might be going on that would be helpful.  I saw some complicated instructions for resetting the instance, but am a afraid I might break something else so I'd rather get someone who knows the password to log in.
