### ISSUE TITLE
Unable to update ORCID for corresponding author

### ISSUE THREAD

**Issue by Ariana-Orona** [CDL-Dryad/dryad-product-roadmap#1894]
I received a query in HelpDesk requesting assistance in updating the ORCIDs listed on the dataset landing page (10.5061/dryad.7h44j0zx7).

The ORCID that was included for the corresponding author, Diana, was incorrect and related to their co-author, Adriana. To amend this, I placed Adriana's name in the field with the related ORCID because I could not remove the 'corresponding author' and effectively resend the ORCID links. 

A few questions:
- Was the ORCID connected in error because Adriana is the submitting author?
- ^ Related to the above: Will the ORCID connected to the submitting author automatically link to the corresponding author on the dataset landing page? My concern is that a different author is listed in the 'corresponding author' field and the ORCID does not link correctly.
- Does changing the corresponding author change the owner?
- If so, does this affect other info (sponsorship, etc)?

Solution:
Allow admin to remove/resend ORCID links, as needed.
Allow admin to remove the 'corresponding author' and update author information, as needed.

**Comment by sfisher** [comment]
Hi @Ariana-Orona ,

I put in https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1895 about this.  In some cases the invitation links are no longer showing up for curators.

To answer your question, the corresponding author is the same as the author who logged in to the system (submitting author) as indicated by the ORCID.  The only way to really change an orcid (for the non-submitting/corresponding author) is to have author do the verifying workflow (which makes them log in to ORCID to verify their account but doesn't create new accounts in our system).

It appears that this dataset is correct now.

This is the sequence I saw with this dataset and the versions:

Version 1: Adrianna logged in and is the corresponding author.

Version 2: Both Adrianna and Dianna have the same ORCID of Adrianna's.  This can happen if a user receives an invitation and logs into ORCID under someone else's account (such as if Dianna gave Adrianna her invitation or if they were both on the same computer and Adrianna was logged in and used Dianna's invitation).

An orcid might also mismatch if someone changes the author information in our UI so that it doesn't match the ORCID anymore.  The submitting/corresponding author can't remove themselves from the dataset since they're in charge of it.  If we need to move the owner then we'd need to do it manually and the new owner would also have to log in to have an account to transfer the dataset to.

Version 3: It looks like Adrianna, Francesca and Diana all have the correct orcids now for their names so they must've used their invitations to update their orcid information correctly.

That other ticket is for restoring the invitation links for curators to see which dropped out of the UI in some cases now.
