### ISSUE TITLE
Add Tenant: Northwestern University

### ISSUE THREAD

**Issue by marisastrong** [CDL-Dryad/dryad-product-roadmap#1917]
**Tenant name:** 
Northwestern University

**Logo location:** 
Logos will be sent via email to @ryscher and @sfisher 

**Contacts to receive submission notices:** 
Chris Diaz
Digital Publishing Librarian
Northwestern University Libraries
[chris-diaz@northwestern.edu](mailto:chris-diaz@northwestern.edu)

**Shibboleth info, if not in InCommon:**
Shib_Identity_Provider: urn:mace:incommon:northwestern.edu

Tasks:
- [x] add config to dryad-config repo
- [x] add logo to dryad-app repo
- [x] deploy and test on stage (institution should log in to verify working as expected)
- [x] update tenant_id for users in the database who have emails with the institutional domain name

**Comment by sfisher** [comment]
Hi @marisastrong and @mariapraetzellis .  I'm not sure who is communicating with Northwestern on this, but I've deployed the changes on our stage system (dryad-stg.cdlib.org) and they should be able to test the shibboleth 2nd factor login there. 

Since stage uses the ORCID sandbox, then they can't use their standard (production) orcid they have to register for a fake orcid (if they don't have one already) on the ORCID sandbox in order to test the full login process.

**Comment by marisastrong** [comment]
Chris Diaz at Northwestern has confirmed SSO authentication is working in stage.

**Comment by sfisher** [comment]
Great!  We'll release to production tomorrow.
