### ISSUE TITLE
Update to Curation Stats: add a column of data "PPR to Curation"

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1932]
I think it would be useful to add a column of data "PPR to Curation" which captures the total number of submissions that move from 'Private for Peer Review' status to 'Curation' status each day. 

The stat for 'total submissions' includes datasets received in PPR and Submitted statuses. Datasets released from PPR status are NOT included in this total and I think it's useful to identify those submissions, separately. Although, these previously PPR submissions might be included in another category like "Datasets to be Curated" but that column would also included datasets that were revised and/or versioned. 

An overwhelming number of datasets are received in PPR status (vs submitted), it would be interesting to track how many submissions in PPR are released and reach the queue for curation.

**Comment by ryscher** [comment]
@jleighherzog Although the requested stat of "PPR to Curation" seems relatively straightforward, I want to provide some context before we finalize this. Data that was in a PPR status can transition to Submitted, Curation, or Withdrawn. Below are the circumstances that cause these transitions:

PPR to Curation:
- Often a dataset is Submitted, goes through an initial round of curation, and the submitter selects PPR during a round of revision. These dataset will briefly pass through PPR to show that PPR is requested, but they automatically return to Curation status, because we don't want to stop the curation process once it has started.
- Sometimes a curator pulls an item out of PPR -- why? in response to helpdesk queries??

PPR to Submitted:
- All of these transitions are caused by a notification from a journal of article acceptance

PPR to Withdrawn:
- Some are the result of a helpdesk request prompted by the PPR reminder emails
- Most are caused by a journal notification of article rejection

Give that context, does it still make sense to have statistics for the transition "PPR to Curation"? Or do we need some more complex definition to track the transitions you're interested in?

**Comment by ryscher** [comment]
Created a pull request to add the specific "PPR to Curation" statistic described here. Jess will evaluate the other possible transitions described above and determine whether more tickets are necessary.
