### ISSUE TITLE
Remove file from published version (DOI: 10.5061/dryad.n8pk0p2w0)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1955]
Please remove this file that's included in the first version published on August 18, 2021: "SmallerFolders.7z"

From the author: _Can you please ensure that the prior version of the updated folder "SmallerFolders.7z" cannot be accessed via the ‘Data Files’ section?  Data in this folder contained limited sensitive information that had been incompletely removed from the previous version of the dataset._

**Comment by sfisher** [comment]
Hi @jleighherzog ,

We cannot go back and remove files from previous versions since it ruins consistency for the version history chain and each version relies on previous ones.

The best way to fix this will be to have the author re-submit and re-publish another version with the corrected files the way they like them to appear (maybe just remove that one file, resubmit and re-publish if that's all they need changed).  Then we can remove the earlier version they don't like from being publicly accessible and viewable.  It will have a different publication date, which IMO is also appropriate since they amended their dataset later (re-publishing it with changes).  Though if the date is needed we can technically falsify it to pretend that it never changed.

When looking at this dataset in an incognito window (what the public sees) there is only the one published version, so removing it will remove the dataset from view entirely, which I don't think is what the user is looking for.  They also submitted (but didn't publish) two versions after the published version, but I still see a "SmallerFolders.7z" file in there and IDK if it still contains data they don't like or if they already amended it and that is what their additional 2 versions are about.

Anyway, LMK when the user get the dataset files the way they like them and re-publishes and we can remove the previously published version from view and access by the public.

**Comment by jleighherzog** [comment]
@sfisher : Updated version has been published. Please remove previous data files published on August 18th.

**Comment by sfisher** [comment]
Thank you @jleighherzog .  I've removed the previously published version from view.  It looks good to me!
