### ISSUE TITLE
Revert to previously published version (DOI: 10.5061/dryad.1jwstqjws)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#1956]
In an effort to remove a published data submission, the author submitted a new version and deleted most of the metadata. Can you revert this submission to the previously published version and update the status in the Dryad Admin site to 'Published'? 

If you need more information, please let me know.

**Comment by sfisher** [comment]
I've reset the Metadata to match the previous version, but cannot change any files or the copy in Merritt easily.  If the files are not as they like then they'll need to make those changes again.

This might have been a non-problem, anyway, unless they were planning on publishing it again since they were the only ones who see an unpublished version where they destroyed things and the public doesn't see any changes until they re-publish.

**Comment by jleighherzog** [comment]
@sfisher : I can't seem to find this dataset in our repository when I search on the DOI: 10.5061/dryad.1jwstqjws

**Comment by sfisher** [comment]
There was a consistency problem which is fixed now.  It's available at https://datadryad.org/stash/ds_admin?utf8=%E2%9C%93&q=1jwstqjws&sort=relevance
