### ISSUE TITLE
Sort funders by NIH institute

### ISSUE THREAD

**Issue by gibsonjen** [CDL-Dryad/dryad-product-roadmap#1964]
**Problem description, and links to relevant helpdesk tickets:**

As part of NIH GREI (plan section 3.4.4), we're required to support the following use case: As a funder from a specific NIH institute or in general, I want to find datasets we have funded, so that I can report on compliance with policies, and track impact of research funding and usage of data.

**Describe the solution you'd like:**

Daniella suggested we add the ability to sort by each NIH institute, in a new funder facet search page (ticket 1963). Jen wonders if we won't need to create the ability to sort by every funder?

**Additional context:**

We have until October at least to do this. Possibly longer - check w Jen as needed

**Comment by sfisher** [comment]
I'm not sure what all this needs to entail.  It sounds like this might be more than just facets in the search of published items.  I made a mockup of my guess of what might meet the requirements, some based on talking with Maria and others but this is only a guess and some of the language also implies we might need to expose this to a different kind of user for NIH or some other user-type or role.  I'm not quite sure.

![funder_information](https://user-images.githubusercontent.com/105433/194381750-0519d528-6941-41cb-aa81-9e254add53d4.png)

![funder-report](https://user-images.githubusercontent.com/105433/194381754-5cbb7285-162d-4e25-ae2d-a9a8df4d3125.svg)

**Comment by sfisher** [comment]
We've talked over the basic wireframes I created with the following pieces of feedback:

- Date types would be "Initial submission" and "Published" instead
- Add another date column on the end for an "Embargo date" which I think is the date something went into am embargoed state (where it shows metadata but not files).  I believe this is not the embargo expiration date (or is it)?
- Title isn't shown as a link but it is a link to get a view of the dataset landing page.

**Comment by sfisher** [comment]
Lots of detailed tasks for this one:

- [ ] CSS changes for layout of advanced filter panel
- [ ] Advanced filter panel
  - [ ] Autocomplete from FundRef for filtering
  - [ ] Date type and range choosing
  - [ ] Partner tenant limit
- [ ] Mega-query to assemble info from different tables and different versions of the dataset
  - [ ] Allow adding additional WHERE clauses for limits in flexible way
  - [ ] Allow sorting
  - [ ] Allow paging
  - [ ] Ensure no SQL injection
- [ ] Table of results
  - [ ] Sortable columns
  - [ ] Hook filters to query and add conditions
  - [ ] Display row of results & reasonable formatting for things like dates
  - [ ] Link to landing pages from title
- [ ] Paging
- [ ] Special case handling
  - [ ] NIH and special aggregated institutions queries for all sub-institutions if selected
  - [ ] If someone at the tenant level is viewing then remove "tenant" drop down and force filter to only show that one tenant.  (Is this how we want to do, or do we need to base query on author affiliations and promiscuous viewing of all datasets and any author that says they are from their institution?).
- [ ] CSV output
  - [ ] Output all rows rather than paged
  - [ ] For same filters shown
