### ISSUE TITLE
Error removing multiple files quickly

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1971]
This issue has probably been around for years after the file upload was redone in React.

If you click remove on one file and quickly click it on additional files before the first request finishes then one of the files isn't removed from the list but is removed from the database.

Then additional attempts to remove the file from the list fail. Refreshing the entire page shows the correct state.

**Comment by ahamelers** [comment]
There are a couple major issues I can see with the way removing files works, which together are causing this bug:

- only one 'removingIndex' is set in state at a time for the full file list, but multiple files can be removed at once
- the removal operations are index based instead of ID based, but because multiple files can be removed before the first removal is complete, the list length and indexes can change mid-removal

I presumed that we still want to allow the removal of files simultaneously instead of sequentially, so I've fixed this by relying on created IDs instead of indexes, and by moving the removal state change to the individual file level. My fix relies on changes in (https://github.com/CDL-Dryad/dryad-app/pull/969)[pull request 969], so I'll wait for that to be merged before creating another pull request for this.

Also, while you remove a file the tabular data check notice says something about the file being too big to check, which is unrelated to this bug, but also weird (I've fixed this, too).
