### ISSUE TITLE
Add Tenant: US Fish & Wildlife Service

### ISSUE THREAD

**Issue by mariapraetzellis** [CDL-Dryad/dryad-product-roadmap#1975]
**Tenant name:** US Fish & Wildlife Service

**Logo location:** 

**Contacts to receive submission notices:** 

**Shibboleth info, if not in [InCommon](https://incommon.org/community-organizations/):** They are restricting access via IP range. Maria has the range info and will share it with @sfisher. 

Tasks:
- [x] add config to dryad-config repo
- [x] add logo to dryad-app repo
- [x] deploy and test on stage (institution should log in to verify working as expected)
- [ ] update tenant_id for users in the database who have emails with the institutional domain name
- [x] add institution's name to the Dryad website

**Comment by sfisher** [comment]
@mariapraetzellis I've updated this so that it should work from these IP ranges.  They should try to test on https://dryad-stg.cdlib.org if they like (note that the stage server uses ORCID sandbox which do not use the same credentials as production ORCID, but they can register for a new test account on the ORCID sandbox).

![Screen Shot 2022-09-26 at 1 00 44 PM](https://user-images.githubusercontent.com/105433/192369283-151a4283-4b61-402e-908e-b42b1c055132.png)
![Screen Shot 2022-09-26 at 1 01 57 PM](https://user-images.githubusercontent.com/105433/192369292-1b861552-dd1f-4abe-98c2-8252203fa2c8.png)

**Comment by mariapraetzellis** [comment]
They tested and confirmed that all is working as expected. Thanks @sfisher
