### ISSUE TITLE
Specific Institute/Center for NIH Funding-UI Data Entry Changes

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#1993]
Related to some other tickets in the backlog.

Jen has expressed that we need to capture the specific Institutes/Centers for NIH funders and that "NIH" itself isn't specific enough for our needs.  Sub-areas of NIH are at https://www.nih.gov/about-nih/what-we-do/nih-almanac/nih-organization

Currently the metadata entry page autocompletes based on CrossRef funder registry which I believe has the broad NIH value, also.

We need to verify that CrossRef has all the funders needed or we may need to start a new project to move them to Research Organization Registry instead (ROR).

Run idea of how to get specifics rather than just NIH by Maria. (This may be just be a message to let them know they need to select a more specific institute or maybe something else if you both decide it makes sense.)

- Implementation of limitation/prompting in the UI for NIH.
- Some kinds of tests (Jest perhaps since this is React code)

**Comment by ahamelers** [comment]
Possibly not the most efficient method, but I looked each of the list at https://www.nih.gov/about-nih/what-we-do/nih-almanac/nih-organization up at https://search.crossref.org/funding and they are all there.

With that in mind, I'd suggest just removing the broad NIH from the list of available options—particularly since I can find no evidence that they allocate any grants through the NIH itself (https://report.nih.gov/award/index.cfm#tabic)

What do you think @sfisher , @mariapraetzellis ?

**Comment by ahamelers** [comment]
We've talked over this and decided using an optgroup might be a good solution

**Comment by ahamelers** [comment]
The solution discussed will not work, and there are multiple ways to attack the problems found. Needs more discussion.

- The component uses downshift's combobox, which is not a select but an unordered list, so optgroup cannot be used
- The look/function of an optgroup can be recreated with a nested list, but combobox does not support nested lists (relies on unnested list indexes for functionality)

Solutions in order of difficulty:
1. Add functionality to change list content when clicked. I.e., one list with NIH, then when NIH is clicked the list changes to the child institutes. Needs design/content discussion
2. Make changes needed to combobox to force functionality of nested lists (lots of changes to functions highlighting and changing aria settings currently based on single level indexes)
3. Build own component instead of using combobox

**Comment by ahamelers** [comment]
Wireframes for some potential solutions: https://docs.google.com/document/d/1LsdbTVEdfX025cCiGbSKV1hoHNrRLnMAjTwyAjEvwLc/

**Comment by ahamelers** [comment]
Mockup from John and UX team: https://li0zj8.axshare.com/#id=83pspo&p=nih_institute_selector

**Comment by ahamelers** [comment]
@mariapraetzellis @sfisher @ryscher 

Because CrossRef doesn't group the NIH institutes in any way itself, we need to group them, and we can create our own list of shorter names + acronyms. However I'm not sure that the names proposed in the mockup are the best options, or what the submitter would be looking for. Any thoughts?
