### ISSUE TITLE
Unable to submit dataset because funding field won't accept entry (DOI: 10.5061/dryad.g1jwstqtq)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2012]
I've attempted to enter funding information for this dataset but it's not accepting any entry. I've deleted the field, added a new one, and selected "N/A" from the drop-down menu but nothing sticks. I receive the error message below despite all attempts. 

This one has no 'placeholders' so it's sitting open on my desktop.

![Screen Shot 2022-09-28 at 11 18 38 AM](https://user-images.githubusercontent.com/76497320/192834076-ba2678e9-0757-45a5-b7e5-c367ddbc20fe.png)

**Comment by bryanmgee** [comment]
@jleighherzog Interesting to see an issue with funders pop up for you too. I've had what I thought were just one-off glitches with the funding box as well before that I didn't bring up because they didn't occur consistently. 

One that I still have in curation matched to 'N/A' but gave me that same message when I removed the Research Facility (same as author affiliation) and tabbed to save, which then went to the funding box; I fixed it by removing the RF but not tabbing, and it accepted that without issue. 

The other one was where I was splitting up multiple awards from one grant org and wanted them all listed sequentially, so I added all of the awards as new entries and then deleted the original one at the top, and the system acted like there were no funders even though there were at least 10 entries. I think I worked around that one by copy + pasting each entry one line up so that I didn't have to 'remove' any funders.

**Comment by ahamelers** [comment]
I was able to recreate this problem locally. The issue is that there is a blank 'sponsor' contributor in the database for this dataset, appearing as the first 'contributor' result. This check in the code, that triggers the funder error, doesn't seem to successfully be filtering to only 'funder' type contributors.

```ruby
if (@resource.contributors.blank? || @resource.contributors.first.contributor_name.blank?) &&
           @resource.identifier.created_at > funder_require_date &&
           @resource.identifier.pub_state == 'unpublished'
```

I'll get a little more information to decide whether the best way to fix it is fixing the filter, or stopping the creation of the blank  sponsor in the database.
