### ISSUE TITLE
Simultaneous receipt of payment and refund (DOI: 10.5061/dryad.6hdr7sr41)

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2038]
It seems the author received a notification of a refund and a charge for payment simultaneously. Would you mind looking into the matter, please? See image attached. We have no record of a request or confirmation to void the invoice on our end. 

Invoice #0707C482-0001
DOI: 10.5061/dryad.6hdr7sr41
SF#: 17233

![image002](https://user-images.githubusercontent.com/76497320/194338990-fd41ab2f-5e15-4d95-8a8b-22ca2a71ec7f.png)

**Comment by ryscher** [comment]
I'm a little stumped on this one. Here is what I know so far:
- 8/15 -- invoice 0707C482-0001 -- sent to Yuki Kitahara
- 9/14 -- original due date
- 9/15 -- automatic reminder
- 9/29 -- automatic reminder
- 9/30 12:52:57pm -- payment receipt 1205-1010 -- Sven van Teeffelen
- 9/30 12:52:56pm -- refund receipt 3262-4580
- Invoice is still "incomplete", and does not seem to be attached to the
  attempted payment.
- The payment is "refund pending". Customer has an email from Stripe stating
  that they need more information to process the refund.
- Payment was initiated by ACH.
- Refund was issued one second after payment.
  - Does this mean the ACH failed?
  - Or was it because the Stripe user who tried to pay was different than the Stripe user who was invoiced?
- In SF 00017233, customer states that payment was made by University of Montreal.
  - Is there a problem with the university's ACH account?

**Comment by jleighherzog** [comment]
@ryscher : So, we can't confirm whether payment was submitted and received?

**Comment by ryscher** [comment]
Payment was attempted, but not received.

**Comment by ryscher** [comment]
Our Stripe contractor says this is likely due to a bug that Stripe is working on. Can we ask for payment to be made a different way?

**Comment by ryscher** [comment]
I'm going to mark this closed, assuming that @jleighherzog is handling communication with the researcher.
