### ISSUE TITLE
Provide Dryad Admin access to Royal Society contacts

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2051]
Please provide appropriate access to the following Royal Society contacts: 

> Amie Mustill
> amie.mustill@royalsociety.org
> 
> Phil Hurst
> Phil.Hurst@royalsociety.org

Amie and Phil should have access to view and export the CSV file for all RSOS-related journal titles: 
1. Biology Letters
2. Interface Focus
3. Journal of the Royal Society Interface
4. Open Biology
5. Philosophical Transactions of the Royal Society A
6. Philosophical Transactions of the Royal Society B
7. Proceedings of the Royal Society A
8. Proceedings of the Royal Society B
9. Royal Society Open Science

If you have questions, please let me know.

**Comment by ryscher** [comment]
Terminology note: The "Tenant Administrator" role applies to a tenant (aka institution). For journals like this, we don't have an interface to manage them; they must be managed directly in the database. Can we agree to call them "Journal Administrator"?

**Comment by jleighherzog** [comment]
@ryscher : Ah, okay. There is no "Journal Administrator" user role. Do we need to create one? I agree that the name of the role makes sense.

**Comment by ryscher** [comment]
There is no explict "Journal Administrator" role in the user interface, but we manage that role internally in our database. For example, go to the User Management page and look up Dale Chah. His account has a normal "user" role, but in the box that describes his role, there is an icon of a page, which you can click to see that he administers all of the journals that use EJP. 

We had to separate it out this way, because it's possible for a single user to have both a tenant-based role and roles associated with a random assortment of journals. So far, we have not needed to make an interface for managing the journal roles, but it sounds like we may want one in the near future.

**Comment by ahamelers** [comment]
@jleighherzog Hi Jess, there's no user with Amie's email address currently in the system. Are they the user with the ORCID 0000-0001-7763-5985 ?

**Comment by jleighherzog** [comment]
Yes, Amie's ORCID ID is: 0000-0001-7763-5985. 
Her email address is: amie.mustill@royalsociety.org

**Comment by ahamelers** [comment]
Okay, both the requested users have been given admin access to the Royal Society journal organization and I've added Amie's address to her user account. Thanks!
