### ISSUE TITLE
PRIORITY: Generate invoice for DOI: 10.5061/dryad.pzgmsbcnv

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2053]
The author of this submission contacted us to inform that an invoice still has not been received for the published dataset: "I still haven't received my invoice. It is already quite urgent because the financial year is coming to an end."

Please include order number "1221200181" in the invoice.

Are you able to generate one? The author has also provided this order form from the University. 

[verso_30971.pdf](https://github.com/CDL-Dryad/dryad-product-roadmap/files/9794885/verso_30971.pdf)

**Comment by ryscher** [comment]
Sent invoice 29F86F53-0001. I added the order number to the invoice after it was generated, but it is not in the email sent with the invoice.

The root problem was that the invoicing system was selecting an incorrect author to receive the invoice. It was accidentally selecting authors that had a blank email, rather than the submitting author, who had an actual email. This problem is corrected in https://github.com/CDL-Dryad/dryad-app/pull/982
