### ISSUE TITLE
Rationalize publication date

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#208]
We have publication dates sprinkled around for display.  Some of them are calculated off embargoes or other dates with crazy fallbacks to other fields.

I think we should always use the one publication_date that is in resource (I believe) and search through and fix our display and remove any unneeded methods and extra fields or tables (like embargo).

Suppress pub dates where the dataset hasn't been published before (or doesn't have a set one for embargo).

**Comment by briri** [comment]
@dlowenberg while working on this cleanup I ran across some workflow questions/issues that were discussed on Slack last week. In an attempt to resolve those issues and simplify the UI experience I've made the following changes.Let me know if the workflow in the screenshots below seems like it will work. If so I'll go ahead and deploy:

<img width="1275" alt="screen shot 2019-03-04 at 9 43 54 am" src="https://user-images.githubusercontent.com/1204467/53752079-93dd9400-3e62-11e9-80ef-7e0d8164d156.png">
Updated the Admin page so that each row has only one pencil icon for updating status/notes/publication date

<img width="778" alt="screen shot 2019-03-04 at 9 44 22 am" src="https://user-images.githubusercontent.com/1204467/53752145-b2dc2600-3e62-11e9-9cc1-d944bb6e1529.png">
Removed the 'published' and 'embargoed' selections and replaced with a 'complete' status

<img width="782" alt="screen shot 2019-03-04 at 9 44 33 am" src="https://user-images.githubusercontent.com/1204467/53752174-cbe4d700-3e62-11e9-85b8-df1b81ad3908.png">
If the user selects 'complete' the publication date appears and they can set it. If they select today or a date in the past, the dataset gets published immediately. If they set to a future date then the item is 'embargoed' until that date. If they do not provide a date then the dataset is embargoed indefinitely.

A job will run daily that publishes dataset's on their publication date.

If the user goes in and changes the status from 'complete' to something else (e.g. if they completed it accidentally) the publication date gets blanked out.

Once an item is published it cannot be edited (same behavior as when the item in 'In Progress' in Merritt.
