### ISSUE TITLE
Investigate auto-assignment fail for DOI: 10.5061/dryad.dbrv15f2h

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2087]
I've come across two datasets that were _not_ appropriately auto-assigned to the previous handling curator upon resubmission. 

10.5061/dryad.dbrv15f2h (manually assigned 10/31)
10.5061/dryad.2547d7wnt (manually assigned 10/24)

Can you please investigate?

**Comment by ryscher** [comment]
10.5061/dryad.dbrv15f2h -- Version 12 was withdrawn by curator, but was never in curation status, so a curator was not "assigned" until the manual assignment in version 14. 

10.5061/dryad.2547d7wnt -- This was due to an older bug, where the system put in the curation note before actually assigning the curator, and sometimes assigning the curator would fail. This has been fixed.
