### ISSUE TITLE
Questions from U Washington's privacy office

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2143]
**Background**
U Washington is a new institutional member. Their Privacy Office has asked us to compete a non-trivial Data Processing agreement. See https://privacy.uw.edu/design/agreements/dpa/

Jenny Muilenburg is the library contact I'm working with to determine whether this is even possible (new to her as well). Here is what she wrote when I queried for detail:

> Let me try to get more information – we were under the impression that since Dryad works with shibboleth authentication that we’d need to have this complete, but maybe that’s not the case. I agree that it seems like overkill, given what Dryad does, but I’m just following (convoluted, academic) procedure 😉 (And I’m glad you were spared the video – it’s short but dry!)

**Request**
She has now come back with a specific set of questions from the Privacy office. Could you please provide answers?

> 1. How would users connect with Dryad using Orcid?
> 2. Is there a reason why users are required to connect via Orcid rather than UW’s SSO?
> 3. What information must users provide to use Orcid and what information would Dryad have access to via Orcid?
> 4. Will any students be accessing Dryad via Orcid?

@ryscher @mariapraetzellis @jleighherzog

**Comment by mark02139** [comment]
@ryscher , Donna is asking if any progress has been made on answering these queries.

**Comment by ryscher** [comment]
I believe Maria is putting together a document.

**Comment by mark02139** [comment]
@mariapraetzellis , I've just received an email from Jenny Mullenburg at U Washington, which reads:
"Thanks. I’m getting concerned that we won’t have this up and running by January 23, which is when the NIH requirements go into effect, so anything you or I can do to help move it along would be great."

Could we please prioritize this?

**Comment by mariapraetzellis** [comment]
@mark02139 . Here are the answers to UWs questions. Let me know if they have any follow-up questions. 

1. How would users connect with Dryad using Orcid?
UW users will first log into Dryad via UW SSO to verify that they have the necessary credentials to access the account. After this step, users will log into Dryad via ORCID.

2. Is there a reason why users are required to connect via Orcid rather than UW’s SSO?
Dryad uses ORCID to authenticate and identify each researcher regardless of their route of entry to Dryad. Not all Dryad partners or users have SSO systems. When datasets are published in Dryad, they will appear in the user’s ORCID profile along with articles and other works. Logging in via ORCID allows Dryad to get validated ORCID IDs for all users and send submission metadata back to ORCID upon publication of a dataset. 

3. What information must users provide to use Orcid and what information would Dryad have access to via Orcid?
ORCID requires a first name and primary email account to create an ORCID profile. Dryad will have access to this information via ORCID. Upon creating an ORCID account, users define their visibility settings which determines who can see new items added to their records.
Here is a screenshot of the ORCID visibility settings:
<img width="377" alt="Create your ORCID iD" src="https://user-images.githubusercontent.com/27511575/206298242-aa322536-52b0-4d29-a414-ae700ad9661a.png">

4. Will any students be accessing Dryad via Orcid?
Yes, all UW students utilizing Dryad will access the application via ORCID.

**Comment by mark02139** [comment]
Thank you!
