### ISSUE TITLE
System does not recognize presence of large data file (DOI: 10.5061/dryad.rfj6q57dz)

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2152]
**Title**: Decreased but diverse activity of cortical and thalamic neurons in consciousness-impairing rodent absence seizures
**DOI**: 10.5061/dryad.rfj6q57dz 

In the queue list, the dataset displays as being only 139 MB in size, but a 17 GB .dat file is included in two of the three versions. Individually clicking on this file returns the "We're sorry, but something went wrong." error message; individually clicking all other files downloads as normal. Clicking the 'Download Dataset' button downloads all files except the .dat file.

**Comment by sfisher** [comment]
I appears that this user held two different browser windows and pages open for the submission and uploaded the file *after* they already submitting the dataset.  We prevent this from happening when people try to navigate to any page of an already submitted dataset.

Uploading after submission isn't going to work or save someone time.  All files must be present in submission at the time of submission.  It was added to our database at 2022-11-15 17:58:01 but the submission took place nearly a day earlier at 2022-11-14 14:17:48 . They can't submit while they're about to do a large upload or in the process of doing a large upload if they want their file to be intact.

Probably the only way they were able to accomplish this was by opening two pages and not navigating or refreshing the upload page and it was a very stale page.  If any page refreshes it will note that the item has already been submitted and lock the user out from further actions on the submitted version.  We can look at additional logic to lock out just the upload process/progress on this page, though this is the first user to do this in about 5 years as far as I have seen.

Unfortunately, this file does not exist in our S3 storage because the buckets in our temporary storage are removed when a successful submission takes place (the submitted version which didn't contain this file was successful and the file was added after submission).

I believe it's probably not available and the user will need to re-upload and we will have to remove the mal-uploaded file from the version history.  There may be a way we can search our S3 bucket to see if the file ever showed up someplace temporary, but I don't have a lot of hope that it will be the case.
