### ISSUE TITLE
PRIORITY: Investigate dataset history and citation info

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2166]
I'm hoping you can help solve some mysteries concerning this published dataset: 

> Clark, David et al. (2022), Highly-replicated soil, topography and vegetation sampling across an old-growth tropical rain forest landscape, Dryad, Dataset, https://doi.org/10.5061/dryad.tqjq2bw23

1) How is it possible that there are articles from 2000, 2006, 2018, etc that cite this data submission which was originally received and accepted for publication in 2022? 
2) The Activity Log recorded that an accept decision was received but I can't find a record of that email notification in the Gmail account. Can you find the historical journal info for this data submission? I'm not confident that it's actually associated with _Ecology_ (the journal confirmed they don't have a record of it).

**Comment by ryscher** [comment]
1. These datasets contain the articles in their list of Related Works. When we list
an article in Related Works, that reference is carried into Datacite as a
citation, regardless of whether the article explicitly includes the dataset in
its reference list. We do this because publishers have historically excluded
data from their reference lists, which has prevented getting accurate counts in
the past.

In the particular example above (https://doi.org/10.5061/dryad.tqjq2bw23), as
well as (https://doi.org/10.5061/dryad.q2bvq83gb), the researcher has taken a
very broad view of "related" articles, and articles are included that are older
than Dryad itself. Obviously, it's possible that the data is equally old, and
the articles truly do reference the data.

**Comment by ryscher** [comment]
2. This is difficult to determine, since the manuscript number was removed from the dataset, and we do not keep a history of  the fields in Internal Data. I do see that the dataset is listed as a reference in this published letter: https://doi.org/10.1002/bes2.2020

We have recently improved our logging for automatic workflow notes, based on #2142, so hopefully these problems will be easier to untangle in the future.
