### ISSUE TITLE
Notify user when withdrawing dataset

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2168]
(split off from #2142)

When a dataset is in PPR and an associated article is rejected, we automatically move the dataset to `withdrawn` status. 

Create a notification for these situations which lets the author know their submission was auto-withdrawn based on a decision from the journal and offer the option to reinstate and publish their data as a standalone publication.

**Comment by ryscher** [comment]
@jleighherzog Do you want to supply text for this message?

**Comment by jleighherzog** [comment]
@ryscher : Draft text below. Can you add merge fields for the text in **bold**? 
_________________________________________
Dear [**FIRST NAME LAST NAME**], 

We have received a notification from the journal that your manuscript was not approved for publication. Therefore, we have withdrawn your related Dryad data submission (**DOI: XXXXXXX**). 

If you plan to submit to an alternate journal for consideration or if you would like to proceed to publish your dataset as a standalone publication, we can reinstate your submission at any time.

Please let us know if you have any questions. 

Kind regards,
The Dryad Team

**Comment by ryscher** [comment]
@ahamelers Sounds like you completed this as part of another ticket, right?

**Comment by ahamelers** [comment]
@ryscher Yes, it was a checkbox in #2195 ! The text of the email provided there was different, though. Do we know which is preferred? @jleighherzog ?

**Comment by ahamelers** [comment]
@jleighherzog The text of the withdrawn email is here:

https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2195#issuecomment-1376254833

Is this linked text, or the text in this ticket, preferred?

**Comment by jleighherzog** [comment]
I believe these are two different requests. 

1. This ticket is meant to implement a notification for submissions that are **auto**-withdrawn -- triggered by a notification from the journal. 

2. Ticket #2195 is for submissions that are withdrawn/removed from 'In Progress' status as a result of regular 'clean up' OR withdrawn manually by a curator. 

If you need just one template for both situations, use this: 

> Dear [FIRST NAME LAST NAME],
> 
> Your data submission has been withdrawn from the Dryad platform
> 
> Title: 
> DOI: 
> 
> If you would like to reinstate your submission, at any time, please contact the Dryad Helpdesk at [help@datadryad.org](mailto:help@datadryad.org).
> 
> Please contact us know if you have any questions.
> 
> The Dryad Team

**Comment by ahamelers** [comment]
Thanks Jess!

@ryscher is the system able to tell the difference between these 2 different withdrawal scenarios and send different emails? I might need an intro to how journal triggers work!

**Comment by ryscher** [comment]
We could definitely separate the two types of emails.

When we get a notification from a journal, the status change is handled in `Manuscript.update_existing_dataset_status`. It creates a new `CurationStatus`, and the the email is auto-triggered from there.

**Comment by jleighherzog** [comment]
Cool, that'll work! In that case, the draft email in this ticket would be appropriate to use when submissions are auto-withdrawn based on journal 'reject' notifications.

**Comment by ahamelers** [comment]
Great, thanks for clearing that up for me, you two! I'll do this in this next sprint.

**Comment by ahamelers** [comment]
Changed a small bit to include the email address (see below). I think we could also include the journal name, instead of the text 'the journal'—would that be preferred? @jleighherzog 

---

<p>Dear <%= @user_name %>,</p>

<p>We have received a notification from the journal that your manuscript was not approved for publication. Therefore, we have withdrawn your related Dryad data submission:</p>

<p>
Title: <%= @resource.title %><br/>
DOI: <%= @resource.identifier_str %>
</p>

<p>If you plan to submit to an alternate journal for consideration, or if you would like to proceed to publish your dataset as a standalone publication, we can reinstate your submission at any time.</p>

<p>Please contact the Dryad Helpdesk at <a href="mailto:<%= @helpdesk_email %>"><%= @helpdesk_email %></a> if you have any questions.</p>

<p>Kind regards,<br/>
The Dryad Team</p>

**Comment by jleighherzog** [comment]
@ahamelers: Yes, the actual journal name is preferred (vs "journal"), if possible! 

FYI: I just submitted a ticket to address redundant or duplicate [Internal Data](https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2321#issue-1593953548). Mentioning this because if there are two journal titles and their ISSNs listed in the internal data, whatever is input into the 'journal title' field of the metadata should be the one to reference. Not sure how the system will be able to decipher if there are multiple journals (we check the Internal Data section at curation but we are humans that make mistakes) :)
