### ISSUE TITLE
NIH and institute report by mid January

### ISSUE THREAD

**Issue by gibsonjen** [CDL-Dryad/dryad-product-roadmap#2175]
Spoke to Ishwar (the program manager for the GREI program at NIH) today and asked him how we get feedback on our dashboard for funders and NIH institutes. He asked to see what kind of data we have so far. So.... may I please have access to the relevant dashboard, or get a report on what datasets we have in association with NIH funding and including all the metadata that's available from the dashboard? By mid Jan? Shout if I'm not making sense. Thank you!

**Comment by sfisher** [comment]
Hi @gibsonjen and @mariapraetzellis ,

Does the [funder report](https://datadryad.org/stash/ds_admin_funders?action=index&commit=Submit&controller=stash_engine%2Fadmin_dataset_funders&date_type=initial&end_date=&funder_id=http%3A%2F%2Fdx.doi.org%2F10.13039%2F100000002&funder_name=National+Institutes+of+Health&page=1&page_size=100&start_date=&tenant=) meet the needs for what you want?

It should give you a big list if you click the [Get Comma Separated Values (CSV) for import into Excel](https://datadryad.org/stash/ds_admin_funders?action=index&commit=Submit&controller=stash_engine%2Fadmin_dataset_funders&date_type=initial&end_date=&format=csv&funder_id=http%3A%2F%2Fdx.doi.org%2F10.13039%2F100000002&funder_name=National+Institutes+of+Health&page=1&page_size=100&start_date=&tenant=) on the bottom.

Let us know if there is something more specific we can do to satisfy this.

**Comment by mark02139** [comment]
@sfisher , three quick questions:

1. There are null values in the 'Award' column; is that expected?
2. There are null values in the 'First submitted' column. That seems like a bug (?)
3. How often will this report be updated, and where can I find it?

@gibsonjen

**Comment by sfisher** [comment]
> @sfisher , three quick questions:
> 
> 1. There are null values in the 'Award' column; is that expected?

Yes.  I believe that it's still not a hard requirement for an award to be filled.  We can look at adding that as a feature.  Also, realize that the report shows all items (even unpublished or unsubmitted) so items with publication dates have been published.

> 2. There are null values in the 'First submitted' column. That seems like a bug (?)

Not for things that haven't been submitted.  This report shows those also.  You'll also see things like blank titles where people start filling something and don't submit a dataset.  I see a some places where the "first submitted" is blank and it is because something has been withdrawn or removed after being published.  We can examine why, yet unpublishing is a rather nasty business that seems to be happening a lot more in the last 6 months for reasons that aren't clear to me.  I'd really like to understand why people keep trying to stuff the genie back in the bottle and maybe we can prevent them from letting it out in the first place, which I think is a better solution.

We can look into that and perhaps improve it, but I don't believe it impacts the items that are published.  LMK if you see otherwise.  Items with publication dates are published.

> 3. How often will this report be updated, and where can I find it?

It comes directly from the database.  It is updated when you look at it.  It is available under "Admin > Dataset funders".  I believe Audrey is moving some UI elements around so it might be under the "DatasetS" menu in the future.

It's a very general report at the moment, so you'll need to use the limits and filter to the data you would like to see and know what you'd like out of it.  (Partner institution if applicable, Funder--"National Institutes of Health", Date type, Date range).  Click the "Get CSV" link at the bottom to export it to that format and it will include all pages of data rather than just the page shown on the screen.

> @gibsonjen
