### ISSUE TITLE
Constrain autocomplete/text entry lists

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2193]
From evaluation done in #1931

![DMPTool screenshot](https://user-images.githubusercontent.com/1749394/207695251-0bd5e02c-2620-4830-8781-297835030513.png)

The DMPTool has found they have much less junk entries since implementing their check and we would like these benefits for ourselves!

For funders particularly, we could also consider replacing forcing the text entry and selection of "N/A" (complicated) with a checkbox to indicate there is no funding—potentially more user friendly

**Comment by ahamelers** [comment]
I have done a few other tasks:

- Moved the "N/A" funder selection to a separate input as proposed
- Did sentence casing on the form labels

I'm working on simplifying the autocomplete element to use a basic html datalist, instead of the fiddly, hard to style downshift combobox, and adding an "error" and a checkbox if the item isn't selected from the list

I'd also like to propose that in cases where the user exits the input box without selecting from the list, but the text entered by the user already *exact matches an item in the list*, we just select the correct ID from the list for them rather than showing the error/"I cannot find my [x] in the list"

**Comment by ahamelers** [comment]
I recommend we do not release this without doing some user testing, perhaps just having it tested by @jleighherzog  and @bryanmgee, since the checking and editing of these fields is one of the tasks of the curators

**Comment by jleighherzog** [comment]
@ahamelers : 
1) When the red text box appears and I return my cursor to the "Granting Organization" field and click in the field, the drop-down menu doesn't automatically expand. I think it might be confusing for author to know what list we're referring to. 
2)Suggestion: update the text to read, "Please select an entry from the drop-down list in the field above, or check the box below" OR "Please select an organization from the drop-down list in the field above, or check the box below"
3) Possible to create a rule that if "NA", "N/A", "None", etc. are typed into the field that the checkbox for "No funding received" is automatically selected? Otherwise, the Funding heading will be published with whatever text was input. Not a big deal because curators can make the edit. 
4) When "No funding received" is selected the final page lists the Funding heading with "Not applicable*" - why the asterisk?

**Comment by ahamelers** [comment]
> @ahamelers :
> 
>     1. When the red text box appears and I return my cursor to the "Granting Organization" field and click in the field, the drop-down menu doesn't automatically expand. I think it might be confusing for author to know what list we're referring to. To better help them navigate, can that menu be expanded as text is being entered AND when users return to the field?

Yes, this goes counter to the way the population of the list worked previously, but now should be a pretty easy change to make! Great suggestion

>        Suggestion: update the text to read, "Please select an entry from the drop-down list in the field above, or check the box below" OR "Please select an organization from the drop-down list in the field above, or check the box below"

I will see what options are for text changes here—this dropdown/checkbox component is reusable and reused for, for example, the author's ROR institution, so it needs to work for multiple things or with the full label text.

> 
>     2. Possible to create a rule that if "NA", "N/A", "None", etc. are typed into the field that the checkbox for "No funding received" is automatically selected? Otherwise, the Funding heading will be published with whatever text was input. Not a big deal because curators can make the edit.

We can do this, but it might be hard to come up with a full list of text choices to do this for—the need to try to type a specific string (and then then select the string from the dropdown) to indicate no funding is exactly what I'm trying to get away from with the checkbox! Is there another solution that might work better? Should I move the 'No funding' checkbox to the top to make it more prominent?

> 
>     3. When "No funding received" is selected the final page lists the Funding heading with "Not applicable*" - why the asterisk? I assume it's an indicator that no match was made, similar to other metadata fields.

This I have no idea about, the 'No funding received' checkbox _should_ be working, on the database side, just the same as typing & selecting 'N/A' worked previously. I'll check this, thanks!

**Comment by jleighherzog** [comment]
@ahamelers : 
Q: Should I move the 'No funding' checkbox to the top to make it more prominent? 
A: No, I like this option! It can help make the display of n/a more consistent upon publication, allow authors to see the alternative option when they don't have funding, and maybe we can pull reporting on it, if necessary.

**Comment by ahamelers** [comment]
@jleighherzog 

1. I've made the change to re-open the list when the input is clicked while it still has results from the previous search
    1. Text is now "Please type above to search and select from the dropdown list, or check the box below"
2. Have not made any changes re typing "None" etc.—can curators make a note of how often they see and correct something like this (and the phrases typed in such cases) so we can evaluate the need and potential improvements in future?
3. I think I've fixed this, although I've never actually been able to recreate it!

I will find out which server to push these updates to and let you know.

**Comment by bryanmgee** [comment]
@ahamelers 

I think the current version looks good! One question I had that is tangential and could be another ticket/pull, is how easy it would be to add some linked reference directly to the page indicating that affiliations pull from ROR and grant orgs from CrossRef? One of the things we run into often is that the affiliation is given in another language and only matches if translated into English; we also run into issues with state school systems regarding how campuses are delineated (e.g., University of California, Berkeley vs. University of California-Berkeley vs. University of California–Berkeley, etc. etc.). ROR is too new for most researchers to have any idea about it b/c it doesn't impact them in any way normally.

In the old system, I think people probably didn't notice or care as much about not having matched their affiliation because there wasn't a giant red box, but similar to how we get a fair number of emails from authors who think the Frictionless report prevents them from submitting, I'm concerned that authors will have a bad knee-jerk reaction and think our system is broken or poorly populated when they presumably copy and paste in an affiliation that doesn't match precisely either because of language or punctuation. Some I presume will just select "I couldn't find my institution even though a match exists," but others I suspect will intentionally seek us out to air their grievances like they do with Frictionless and a few other aspects. If they know to look it up in ROR / CrossRef, whose direct searches are better at providing all of the possible spellings/combinations than our system drop-down, that might head off some issues. 

Not prohibitive to immediate release of these new features, which are great, but wanted to check.

**Comment by jleighherzog** [comment]
Thanks, @ahamelers. I also agree with @bryanmgee's recommendation above and hope that we can find a way to provide additional guidance on our submission pages to eliminate confusion and encourage authors to share more complete metadata without overwhelming the page(s). Could be something as small as adding a hyperlink to the source for the drop-down menus "Granting Organization (list populated by [FundRef](https://search.crossref.org/funding))"
