### ISSUE TITLE
"Download dataset" zip file mixing up files from different resubmissions

### ISSUE THREAD

**Issue by Savannahbutler** [CDL-Dryad/dryad-product-roadmap#2199]
DOI: 10.5061/dryad.h9w0vt4n7, title: "Data from: Predicting primate-parasite associations with exponential random graph models". 
Using the "Download dataset" button, the old README file (1.81 kB) from December 14th is being pulled into the zip file. Two curators reported the downloaded zip file contained only the old README file, while my zip file contained both old and new (13.51 kB) READMEs. All other files are correct. Screenshots attached from both my download as well as Jess's attempt. 

<img width="558" alt="Screenshot 2023-01-02 at 10 04 04 AM" src="https://user-images.githubusercontent.com/114602548/210257875-22c793e0-6d2f-4b1e-8d63-6ad87a7c6f47.png">

![image](https://user-images.githubusercontent.com/114602548/210257887-37805f59-c213-45c2-b548-449b6531551c.png)

**Comment by Savannahbutler** [comment]
Please note that another curator (Kailasha) is experiencing similar issues with another dataset: 10.5061/dryad.nk98sf7wq. She has included the following text: "The total number of files for download and the number of files in the "Upload files" editing page (excluding the 2 Zenodo files) is 8 but whenever I download there are 9 files (author deleted the old version "weta_genotypes"). Even though the author deleted it it still shows up. Can someone download the files and let me know if they are experiencing the same issue? I even tried to upload all the files from my end (but I didn't submit it) and I noticed something different. There was a duplicate file. I have attached the screenshot."

![Duplicate](https://user-images.githubusercontent.com/114602548/211124385-bfbc1ff9-25f7-4566-95f0-6e8c58d9370a.png)

**Comment by Savannahbutler** [comment]
A third dataset is showing the same issue: 10.5061/dryad.fbg79cnw1 

The README file from December 2021 is downloading into the zip folder of the most recent (January 2023) files.

**Comment by Savannahbutler** [comment]
Another dataset with dual README download: 10.5061/dryad.c59zw3rc6

**Comment by sfisher** [comment]
Thanks for the info.  After a long time looking thorough all the old versions, this looks like it only happens when a file varies in case but is otherwise exactly the same as another file that already exists from a previous version and then one of the files is deleted.

![Screen Shot 2023-01-20 at 2 34 38 PM](https://user-images.githubusercontent.com/105433/213819323-eab9ba94-6ab1-4dc2-b4f3-f01962173c79.png)


![Screen Shot 2023-01-20 at 2 35 14 PM](https://user-images.githubusercontent.com/105433/213819345-cd2859f9-f045-4ced-ba12-9c8774ab14cf.png)

![Screen Shot 2023-01-20 at 2 38 40 PM](https://user-images.githubusercontent.com/105433/213819348-2f7ec7ee-21ea-4f02-8576-f7c7e11e1764.png)

It is also very confusing if people upload filenames that only vary in case since both files can be put into the zip file, but the user's filesystem may or may not handle it once it's unzipped. (Linux/Unix allows filenames that vary in case, but MacOS doesn't and I don't think Windows does, either).  When it is unzipped then the later file may overwrite the earlier file that already exists if the file system doesn't handle it.

These zips sometimes have both files in it, but whether it shows up that way when unzipped depends on the user's computer.

![Screenshot from 2023-01-19 16-34-48](https://user-images.githubusercontent.com/105433/213819659-9b60cf06-d0ac-4fa9-a7fe-4416684451f6.png)

I've manually corrected the extra file in the published versions for these datasets and have added #2235 to  change this.

**Comment by jleighherzog** [comment]
@sfisher Another example: 
If you go into editing mode, it looks like there are three copies of the README, same name, same size. But when you look at the file viewer on the landing page and download it, there's only one: https://datadryad.org/stash/dataset/doi:10.5061/dryad.4tmpg4ff7
