### ISSUE TITLE
Monthly fee waiver report

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2209]
Please prepare a monthly fee waiver report to capture the following: 
- Title
- DOI
- Date 'Submitted'
- Journal (publicationName)
- Author Institution
- Current status
- Reason (from drop-down menu)
- Other (write-in reasons)

**Comment by ryscher** [comment]
@jleighherzog Most of this is available in the [shopping cart reports](https://github.com/datadryad/journal-payments/tree/main/shoppingcart). 

The shopping cart reports cover all items that are approved by curators, in the course of a month (published or embargoed). Are you envisioning this report to be the same? Since you included Current status, I'm wondering whether you have some other criteria in mind for including items in this report.

Otherwise, the fields that would need to be added to the shopping cart report are:
- Journal name (currently ISSN is listed when a journal is paying, but not otherwise)
- Reason

**Comment by ryscher** [comment]
I discussed with Jess, and she agreed that we can augment the shopping cart reports to include journal name, reason, and "other" reason

**Comment by ryscher** [comment]
When I previously commented on this ticket, I was looking at an older report. So https://github.com/CDL-Dryad/dryad-app/pull/1108 adds the CurrentStatus, but the other fields were already present.
