### ISSUE TITLE
Bug: System changed 'Published' dataset to 'In Progress' on its own, sent automated email

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2211]
We received a [Helpdesk query](https://dryad.lightning.force.com/lightning/r/5003h00000XtgzIAAR/view) from an author who got an automatic notification of an 'In Progress' dataset, for a dataset that was already published. Indeed, in her dashboard, one dataset shows as being 'In Progress' because it is being edited by a curator. However, if you look carefully, the dataset listed under 'In Progress' ("Raw data...") is not the one listed as being edited under 'Submitted' ("Effects of...").

![dryad_status](https://user-images.githubusercontent.com/113212676/211085137-0e50e12e-b91a-4eb7-921a-e6fb92b01014.png)

I went into the system about 15 minutes after this email and checked the author's datasets; both display as 'Published'

![Screen Shot 2023-01-06 at 9 43 52 AM](https://user-images.githubusercontent.com/113212676/211085285-261dabd2-16b7-496c-8b8a-0d625b9da9c3.png)

There is no dataset listed as 'In Progress' for this author or for the curator who handled both of the author's datasets (Joe)

![Screen Shot 2023-01-06 at 9 44 23 AM](https://user-images.githubusercontent.com/113212676/211085415-d6d21811-6b5e-4210-861b-c8c4ba322e63.png)
![Screen Shot 2023-01-06 at 9 44 09 AM](https://user-images.githubusercontent.com/113212676/211085416-7bdb2851-bead-41b3-b95c-8e60a6e5f005.png)

Examination of the Activity Log shows two things: (1) that the dataset was not removed from editing by the curator within the short time between email intake and my investigation of the issue; and (2) that the dataset is still 'In Progress,' despite not appearing as such in any search, but there is no curator affixed to the action; instead, it's the system that put it there and then sent the automated email.

![Screen Shot 2023-01-06 at 9 43 42 AM](https://user-images.githubusercontent.com/113212676/211085459-9bd65752-7bb2-45e8-b8a6-cf39ace5a2bc.png)

Unclear what happened here – I suspect that forcibly editing the dataset is the "quick fix" to the problem, but since the system shouldn't send any more automated emails, I haven't done anything with it in the hopes that we can figure out if this is a more pervasive bug.

**Comment by sfisher** [comment]
This is likely the result of crazy-clicking and or starting 2 new versions at the exact same moment.  If you examine version 7 there are two different versions of version 7 (resource_ids: 213323 and 213324) and they were both created at 01/02/2023 08:22:32 UTC .

Normally it's not possible to do this since as long as a version is already created it simply loads the existing version (or locks out editing).  However with some machine-gun clicking it's maybe possible to start creating another version before the first version has finished creation yet.

213323 was indeed still in progress, so makes sense that it was notified that it was in progress.  I deleted that additional version of version 7 now.

Added #2212 .
