### ISSUE TITLE
Journal import URLs not working

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2231]
We have been receiving reports at the helpdesk that the URLs journals are giving to their authors are no longer pre-filling the correct metadata.

An example, with actual manuscript number replaced to maintain pre-acceptance anonymity:
http://datadryad.org/submit?journalID=BEHECO&manu=BEHECO-2021-XXXX

Even when the manuscript number is replaced with one that has associated metadata in our database, the metadata is not pre-filled in the submission form.

**Comment by ryscher** [comment]
(Reported by @bryanmgee, @jleighherzog )

**Comment by jleighherzog** [comment]
This is an important ticket to address because it impacts our integrated journal titles. In my conversations with publishers like ACSESS and Pensoft, they want to ensure an easy, seamless submission process for their authors and this feature helps provide that. It will also reduce queries received re: broken links from the authors or journal offices.

**Comment by jleighherzog** [comment]
Related to https://github.com/CDL-Dryad/dryad-product-roadmap/issues/1815#issue-1266626217

**Comment by ahamelers** [comment]
See also #2337
