### ISSUE TITLE
PRIORITY: Return published dataset to PPR (10.5061/dryad.ttdz08m1r)

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2242]
The author asked for the dataset to be returned to PPR to honor a media embargo for the associated manuscript.

Title: Data from: Largest-known fossil penguin provides insight into the early evolution of sphenisciform body size and flipper anatomy
DOI: 10.5061/dryad.ttdz08m1r

**Comment by sfisher** [comment]
Ok, this is unpublished.  https://datadryad.org/stash/dataset/doi:10.5061/dryad.ttdz08m1r

**Comment by bryanmgee** [comment]
@sfisher Not sure if maybe something didn't fully clear the system? I see in the Activity Log that the last status update is back into PPR, but on the admin dashboard, it's still listed as 'In Progress,' which is what it was before.

![Screen Shot 2023-01-31 at 7 53 15 PM](https://user-images.githubusercontent.com/113212676/215941455-1084b3db-70b2-4fba-98c7-407cc99076e3.png)
![Screen Shot 2023-01-31 at 7 53 00 PM](https://user-images.githubusercontent.com/113212676/215941456-711702f8-a02e-412d-ba2a-74ba42f93ae4.png)

**Comment by sfisher** [comment]
Hi @bryanmgee 

There are two versions of this dataset, which is confusing.  The published one was version 5 (resource id 215964) which seems to be set correctly into private for peer review again.

Version 6 (resource id 216980) is a new version that the author had already begun editing before and never submitted or completed edits on.  Anything someone starts editing but never finishes is always "in progress" because they have in-progress edits they haven't completed.  However, peer review is still set on that version, even though it still has incomplete edits going on by the user that have never been submitted.

"peer review" state is orthogonal to normal workflow states and it isn't really a state in the same way, but just a flag on the version.  Things can both be "in progress" and also flagged for peer review at the same time.  If it gets submitted then I believe it should show a workflow/curation state showing that it's waiting around for for peer review then.

If you want to get rid of the edits that the user has started (but possibly abandoned) you can do one of a few things: 1) Ask the user to click the "delete" link for the the dataset in the "In progress" section of their "My datasets" page or 2) Click "Forcibly edit dataset" at the bottom of the Activity log page for the dataset and then click the "Cancel and Discard Changes" button which removes the in-progress edit to the dataset which you've taken over from them.

I'm hesitant to delete a user's work since I may be destroying something meaningful that they've put in to edit another version of the dataset.  If you feel it's fine to delete the user's in-progress edit then feel free to remove it (as mentioned above) or let me know and I can remove it for you.

I hope this makes sense.

--Scott

**Comment by bryanmgee** [comment]
@sfisher Thanks, the author told me they just went into the dataset to see if there was a way that they could force it back into PPR on their own, so no issues here with hijacking their dataset and canceling it out.
