### ISSUE TITLE
Update needed to 'at a glance' view on Curation Stats page

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2262]
Priority: Low 
Impact: Curation management

There is a small update needed to the snapshot that was updated (see [this ticket](https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2179#issue-1498276931))

The top row should, most likely, always be greater than zero. Can you review? This should capture all new, unclaimed submissions. 

![image](https://user-images.githubusercontent.com/76497320/216408639-fa646286-19f2-4e3e-b17d-437fe88fb8ff.png)

**Comment by ahamelers** [comment]
See also #2721

**Comment by ahamelers** [comment]
https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2721#issuecomment-1679113131

**Comment by ahamelers** [comment]
@bryanmgee can you tell me more specifically what's wrong with these numbers? if I do a manual count, these seem correct.

**Comment by bryanmgee** [comment]
So if I take a count right now, it says 172 datasets currently available for curation and 128 datasets in Submitted that are not claimed. I read 170 in Submitted status; of those 27 were previously published (Versioned), and another 7 are claimed but not previously published and still in Submitted. There are then 39 datasets in Curation. So the 'unclaimed in Submitted' should be 136 (that +8 discrepancy is small enough to make me think perhaps it is just a short time lag in that box's stats). In the least inclusive concept of "available for curation," it is only unclaimed, never previously published in Submitted (128) + Curation (39), which gives 167; again, small enough (-5) to possibly be a time lag. However, that isn't a great approximation of "The Queue" – anything in Submitted or Curation is in our ballpark (not all versioned datasets are only them adding the article DOI or something else that's easy), so really it should be 209 (everything in Submitted + everything in Curation), and that discrepancy seems high enough to not be a short time lag (especially because I've been in a meeting for the past hour, so curation volume is low).

**Comment by ahamelers** [comment]
Okay, after testing this, I think there is some kind of conflict between the time being requested by code on the server, and the time being recorded in the database. These stats include by default a check for resources updated before "now"—but what is "now" seems to be incorrect, depending on where the request is made from. The simplest solution is to remove this time check as it's not actually necessary for the query, just a placeholder for the 72 hours check.

**Comment by ahamelers** [comment]
I fixed this (tested on dev) by declaring UTC time all over the place. Also made the phrasing a little less weird/verbose

<img width="495" alt="Screenshot 2023-08-18 at 13 15 22" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/1749394/b5919214-9fe6-4c56-8244-de2712803b88">
