### ISSUE TITLE
Restrict obviously bad dataset titles

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2270]
"Raw Data for Figure 1" is completely useless. We need to institute some basic rules for validation of dataset titles.

A simple start would be to define a dictionary of words that have no meaning, such as prepositions, articles, numbers, "data", "dryad", "figure", names of the authors, etc. Remove these from the title and determine how many meaningful words remain. If there aren't enough meaningful words, force the user to improve their title.

(We could go the other extreme and use some machine learning techniques, but I doubt it would be better than the simple approach.)

**Comment by jleighherzog** [comment]
@bryanmgee : Populate a list of words here? 
- Raw
- Data
- Dataset
- Figures
- Figure
- Table
- Tables
- flag HTML syntax <i> </i>
- underscores (__)
- File
- S1
- Supplemental

**Comment by jleighherzog** [comment]
Thoughts on pre-populating the **Dataset title** field with: "Data from:" _**except**_ when "other or not applicable" is selected as a submission type? We could make it editable/removable. My thought is, it might help guide authors as to what to input.

**Comment by ryscher** [comment]
We previously added "Data from:" when Dryad enforced a connection between the data and a primary article. We stopped adding it when we relaxed the requirements, so authors could provide a better description of the data itself, rather than only describing the article. I think preferences vary by community, so we will never make everyone happy. I would want to get broad user feedback before we changed that decision again.

**Comment by jleighherzog** [comment]
@ryscher : Can we proceed with the list above? Any other suggestion to add?

**Comment by ryscher** [comment]
- I'm fine to proceed with the filtering list above. 
- I do not think we should add "Data from:" when importing an article title, unless we have some evidence that the community wants it

**Comment by bryanmgee** [comment]
We can/should get some community feedback, but the pretext that we don't enforce it now so that authors provide more data-specific titles is also not working – of the authors who submit good titles, 85% are submitting their verbatim manuscript/article title, which is not data-specific or necessarily even good for a dataset. Same issue with the Abstracts, which are overwhelmingly just that from the associated study. We can start refusing to accept this, but we will then be sending back even more datasets for even more issues, and this would also require training most curators on how to recognize a verbatim manuscript title when we don't have an associated Related Work to cross-reference.

**Comment by ahamelers** [comment]
@bryanmgee that makes a lot of sense to me and I do think we need a larger conversation about the metadata and the purpose of different elements (to me, particularly the abstract) and how and whether they should be imported—I think many of these idiosyncrasies stem from Dryad's history of originally _only_ allowing datasets attached to articles and not in fact publishing them as separate entities. But for the purposes of this ticket, which is specifically about the title, I don't think ensuring the dataset title is distinct from an article title is in fact super valuable. You would know better than me but I can imagine in many cases the same title could equally describe both article and dataset, and adding 'Data from:' to the title, due to the citation already containing '[Dataset]', is not really adding anything.

**Comment by bryanmgee** [comment]
Well, so this is my point – on balance, I do not think that manuscript or article titles tell you anything useful about the type of data that are in a dataset. Let's look at the oldest unclaimed datasets in the queue right now:

- Initial conditions combine with sensory evidence to induce decision-related dynamics in premotor cortex
- Evolution of chemosensory and detoxification gene families across herbivorous Drosophilidae 
- Complex Polyploids: Origins, Genomic Composition, and Role of Introgressed Alleles
- Electron microscopy images of thalamus from acutely hydrogen sulfide poisoned mice
- SAMC Model Inputs from: Predicting dispersal and conflict risk for wolf recolonization in Colorado

The first three are perfectly fine article titles but do nothing to indicate what they actually contain as a dataset. One of the other two (#4) is not the MS title, which is why it is the clearest about what it contains - microscopy images. #5 is useful only because they have used a more specific form of the "Data for/form" format to specify what they have provided. If they removed that and only had their MS/article title, I would have zero clue what kind of data they have for wolf recolonization.

This comes around also with respect to the search function and discoverability – I keep getting mixed messages on whether we want/need to improve that because some people say, well, these are mostly associated with an article anyway, but that does nothing for datasets that are not associated with one and runs directly counter to how we have always approached curation. When people search, they are searching for something like "bison observation data North America," not whatever convoluted buzzwordy title an associated MS (and a dataset titled identically) will have (e.g., "Decadal demographics of charismatic North American megafauna in the Great Plains Region"). I have a HD case right now where an author is coming up with nothing even though she is using useful keywords because those do not match titles!

**Comment by ryscher** [comment]
We decided to move forward with the quick and easy detection that was originally described in this ticket. The larger discussion is moved into #2753.
