### ISSUE TITLE
Is it really supposed to lock users out while in curation?

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2282]
It seems like if a dataset has been published (or maybe just curated once before), then another submission locks the user out from making any more edits and it goes into a weird limbo "curation" state in the "My Datasets."  Is this how it's supposed to work? (No one was currently editing the dataset).

Steps:

1. Create a dataset and submit it.
2. Curate the dataset and then publish it.
3. Edit the dataset again as a user and submit it again.
4. It then goes into a weird state of "curation" in the "My datasets" and doesn't allow updates, say if a user wanted to tweak another thing before curation.  (This doesn't seem right to me.)
![Screen Shot 2023-02-07 at 4 29 27 PM](https://user-images.githubusercontent.com/105433/217399185-010bd242-9aec-4a85-a1da-a5f86c42d07f.png)
  - User isn't able to edit their own dataset if they would like to make any additional changes, even after it has gone through the submission process (it's not in the top "in progress" area and can't be edited).
  - The only way to edit it again is from the curation dashboard which they don't have access to
![Screen Shot 2023-02-07 at 4 30 32 PM](https://user-images.githubusercontent.com/105433/217399345-a827cede-0177-4cd3-965d-5a54254d2019.png)

Is is really supposed to completely lock them out of editing the whole time a dataset gets reset to a "curation" status (which happens automatically)?  I would think it should only really lock them out if someone else is currently editing, not because it's in a curator's queue.

**Comment by ryscher** [comment]
That's how it is currently designed. Note that it is difficult to tell when a curator is actively working on a dataset, because they may have downloaded the files without opening the metadata for editing. We didn't want the researcher to change out files while a curator was looking at them. 

@jleighherzog, thoughts on whether the researchers should be locked out until a curator has a chance to look at the dataset?

**Comment by sfisher** [comment]
OK.  I didn't realize that.  If I was a user, I'd be quite frustrated if I wanted to make changes and was locked out from making changes for an extended period of time.  Part of it is that things get automatically set to curation automatically, even if they're not really being actively curated that day.  I know this is better recently, yet in the past people might be locked out for weeks or longer.

But maybe this is no longer a big issue with shorter queue times or researchers maybe don't really care about making edits to their datasets unless someone else tells them to.

**Comment by jleighherzog** [comment]
@ryscher @sfisher  The process Scott outlined is for versioned data submissions (previously curated & published). Once resubmitted by the author, the dataset should return to us in "Submitted" status. But, based on what you're saying, looks like it's not working properly. 

Note, revised submissions (previously curated but _**not**_ published) are received back to us in 'Curation' status. Which, isn't preferred, in my opinion, because that status should be reserved for _active_ curation. 

This is something I've wanted to change for a while but I need to know more about why it was set up this way. If we make a change so that all versioned submissions are received in 'Submitted' status, it would/should allow authors to make edits up until it's claimed for 'Curation' status. At that time, it should lock users out so that there's no overlap in efforts between authors and curators. Does that make sense? 

Here's some text from our workflow documentation: 
a) Search for author-versioned datasets requiring action (datasets previously published by you): 
1. Go to the Dryad Admin Site
2. In the Curator field, select your name from the drop-down menu
3. In the Status field, select “Submitted” from the drop-down menu

b) To search for author-revised datasets that you had previously placed in “Author Action Required” status and are now submitted and require curation: 
1. Go to the Dryad Admin Site
2. In the Curator field, select your name from the drop-down menu
3. In the Status field, select “Curation” from the drop-down menu

**Comment by ryscher** [comment]
I looked through the old tickets, and the most recent I found was  #1556, which requested that new versions go to 'Submitted' status. Which was not what I remembered. So I did some testing, and this is what I found....

- When dataset is first submitted --> Submitted
- When dataset is versioned by submitter after some initial curation --> Curation
- When dataset is versioned by submitter after being published --> Submitted
- When dataset is versioned by submitter after publish, version, curation, AAR --> Curation

So I think this is what Jess wants, correct? And Scott's original observation may have been affected because he was submitting from an account that also had curation privileges?

**Comment by jleighherzog** [comment]
I'm going to check in with the team on the workflow for these paths. So, before making any changes, let me collect their feedback on this. 

What I'm thinking is this: _everything_ returns to the queue in 'Submitted' status and is auto-assigned to the handling curator _OR_ re-assigned to a new curator, in rotation, if the previous handling curator is no longer with Dryad. 

When dataset is first submitted --> Submitted
When dataset is versioned by submitter after some initial curation and AAR --> Submitted
When dataset is versioned by submitter after being published --> Submitted
When dataset is versioned by submitter after publish, version, curation, AAR --> Submitted

**Comment by ryscher** [comment]
Closing, since this has been fixed by subsequent tickets, including #2510.
