### ISSUE TITLE
Investigate frictionless logs for error types

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2305]
We have historical log data for things processed by frictionless over the past year or two in our database.

Can we look at this data and figure out something meaningful?

- Are certain errors more common?  Are they useful?
- Is there a correlation between field of study and the errors we see? (or some other factor)
- Are people in general really ignoring these errors or are they hung up and afraid to submit?
- Is there way we can get additional insight?

**Comment by ahamelers** [comment]
A zip file provided by @bryanmgee with "bad" error types! https://drive.google.com/file/d/1LlPC9JiXWtLV0msHm90cx2AoQWOHlPM0/view?usp=share_link

**Comment by sfisher** [comment]
I uploaded these tabular data types to development. at https://dryad-dev.cdlib.org/stash/dataset/doi:10.5072/FK2G164B18 and saw what the tabular data checker produced.

The things I notice:

- A number of cases where the header for rows/columns doesn't start on the first line.  Is there a way for the tool to find the real header row better?  Or do we want to force users to indicate which row their column headings are on?

- Some data is missing in some rows that is present in most or all other rows.

- Some people using for layout and presentation of varied data and results rather than as consistent tabular data.

- Giant combined cell of text at first which gives header errors.

---
Discussion

We might be able to use something different such as an AI tool to give better results since it might be able to glean more context and make better suggestions.  It might also give really bad "intelligent" suggestions (based on my experiences with ChatGPT and others that talk confidently about things that they clearly don't understand).  The LLMs seem to be expert mansplainers from all the content they've picked up on the internet and also from having a facade slapped on over the top for a confident, chatty interaction style.

We might be able to give people some checkbox to indicate that their data isn't consistent tabular data and they might be using Excel or CSV formats for data that doesn't follow a consistent pattern with tabular representation. That way they don't go through the worry of feeling sad by having their data structure linted.  Or better yet, we can give better context about what checking is and that they need to decide for themselves whether a suggestion is a good one or not.

We might be able to force people to tell us which row is their header row to get better results since many of these problems are about finding the correct header row (or people having some heads, subheads, etc).  We might be able to programmatically detect it in some way that does better than their default tool (or it seems like this would be something that Frictionless would want to improve and should be part of the tool).

I disagree that these checks are useless and in an ideal world, people shouldn't be randomly missing headers or pieces of data without explanation (when that can be a real problem).  A missing heading might mean the contents of the cells below are unclear (just like not indicating units for a measurement is bad and you don't want to use the wrong unit and make the Mars rover crash because you did).  Missing data may often mean that you were not careful in data collection or entry and something is missing. Maybe your data hasn't been double-checked,  proofread or of the quality that it could be.

The process is also similar to doing a spell or grammar check on a document that you are going to turn in. If you have personal names or other things that are similar to standard words, then the spell checker is probably going to flag them and you need to use your own judgment if a problem exists and what to do about it. The check isn't always brilliant and insightful in all respects, but it still serves a review purpose and helps catch some mistakes.

All of spell checking, linting and tabular data check tools are just a way to *possibly* catch common problems and to get people to re-evaluate their work to be sure they do not fall into common traps or have some obvious and common classes of problems.

We might also come up with (or find online) best practices for presenting tabular data (and especially machine readable data).  There may be recommendations about where people expect headers, that missing or inconsistent values should be indicated in a certain way, etc.

---

Details of what I found below:

case5_det1_7200_5600_det2_6800_4500.xlsx
  - Is this really tabular data? Maybe some sections are but it doesn't seem to repeat.
  - There are different sections with different information and a few calculations
    and presentation of results at the bottom.

Fig2_Current_Kv7_Data_IM.csv, Formatting report: Fig2_Current_Kv7_Data_WT.csv,
  - The user doesn't put headers in one row like normal, but has header and subheaders in
    two rows.

FigS1_RT-qPCR_Data_Cq_Values
  - Another using several layers of headings with some cells skipped in the top level

Smith2023E_E.csv
  - Randomly missing data for some items "No Fish" with some "No Fish" rows having data and some not -- at random.  Says that it is expected to be an integer (since all around it are).

Supp_material_7.5_CRRP4_metric_AST_2017.csv
  - Large number of "commented" beginning lines that don't have values where the main
    table below has them.
  - Only some items have a filled value for heat_index_set_id in celsius

Supplemental_-_All_data_sets.csv
  - Couldn't be read, IDK why

Supplemental_Table_7_020623.xlsx
  - Lots of errors reported because the top cell is a giant combined one with text in it.
  - Flagged as blank headers.

**Comment by bryanmgee** [comment]
@sfisher I think some wires might have gotten crossed; these files were more related to #2405, which was trying to find examples of tabular data (or data in a tabular file format anyway) that would be acceptable to publish because any empty cells are not actual errors or ambiguous in interpretation but that get flagged by Frictionless. I thought that for this one (2305) that there was some record of all of the reports ever generated by Frictionless that could be mined in terms of what "errors" it throws most often, and we could combine these two different things to figure out a good way forward

**Comment by ahamelers** [comment]
Here's the README Bryan included for these files:

---

# Tabular data sampler platter for Audrey
Last updated: 2023/04/12
Compiled by: Bryan Gee

## Sample tabular datasets for Audrey.xlsx
I put five sheets in this Excel file, mostly before I found some real-life examples, but these capture some things that aren't fully reflected in the empirical examples.
* Sample Dataset 1: Clinical trial data where there are randomly different numbers of participants in a given trial
* Sample Dataset 2: An auto-generated output from an analytical instrument that contains successive header rows of metadata that are in all of the output files
* Sample Dataset 3: The use of columns to separate different tables/dataframes within a given sheet
* Sample Dataset 4: The use of a second row for units; no value may be provided when there are no units (conceivably this could be just for the first column, which is often 'ID', 'Trial', etc.)
* Sample Dataset 5: Summary statistics included somewhere in a dataframe, often separated by a empty row (alternatively in columns adjacent to the dataframe where cells below the summary table are treated as 'empty')

## Empirical files
The remaining datasets are listed by their provided filename and would all be acceptable for publication (well for me anyway). If you're on Mac, I included the DOI for the dataset in the 'Comments' metadata section of the file description. The one exception is **OTC Dryad Upload.xlsx**. I included this one because we (me and Laura) have noticed that sometimes Frictionless passes Excel files that clearly have a lot of empty cells, and I just happened to have to re-upload this one on behalf of the author and saw that it passed after the previous version "failed." Most if not all of these datasets were published.

**Comment by ahamelers** [comment]
I've made a huge table of all frictionless errors.

- There are a total of 10 error types ever found in our data files
- By far the most numerous is the Type error—when a column is identified by frictionless as a particular data type but then contains content that is not that data type
- An order of magnitude after that are the pretty self explanatory missing-cell, blank-row, and blank-label errors, followed another order of magnitude by duplicate-label and extra-cell errors

I do not foresee any difficulty in writing a guide to help users resolve these most common errors types.

```
error	count
Type Error	2989157
Missing Cell	911326
Blank Row	330096
Blank Label	213007
Duplicate Label	74909
Extra Cell	51738
Schema Error	1137
Source Error	338
Encoding Error	31
Format Error	4
```

- The schema and source errors all seem to be from JSON files, which we no longer run through frictionless
- The 31 encoding errors are all where the data source file contained invalid bytes not matching the stated encoding 
- The 4 "format errors" are all when an Excel document was missing a sheet 1 (probably it wasn't actually an Excel document)

**Comment by ahamelers** [comment]
All type error messages: [type_errors.csv.zip](https://github.com/CDL-Dryad/dryad-product-roadmap/files/12718389/type_errors.csv.zip)
