### ISSUE TITLE
API support request

### ISSUE THREAD

**Issue by sarahklippincott** [CDL-Dryad/dryad-product-roadmap#2319]
I have a tech support question from a user about search in Stash and the API.

- Does our frontend search (https://datadryad.org/search) support Boolean terms, specifically OR? The user is (unsuccessfully) attempting to query two ROR IDs ("(https://ror.org/00f7hpc57) OR (https://ror.org/0030f2a11)").
- Same question as above but for the API--can you search multiple ROR IDs with a single call?
- Can we query publication date via the API? The user is interested in pulling time spans with a defined end (e.g. published records in 2019, 2020, 2021).

**Comment by ryscher** [comment]
Dryad does not currently support "OR" in searches. The best way to get the desired results is to perform the search with each ROR separately and combine the results.

In Dryad's API, there is a feature that will search for all datasets associated with a member "tenant", including all of the ROR identifiers that are associated with that tenant. Note that this search is only available for Dryad member organizations.

The search API does not allow queries by publication date. Currently, it supports search by the last modification date. This allows API users to process all of Dryad's existing content, filtering it in any way they want (e.g., by publication date), Then at a later time the users can identify only the datasets that have changed since the last processing date, without having to process the entire history again.

More details on the search API are available here:
https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/apis/search.md
