### ISSUE TITLE
Update CI tools for new GitHub structure

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#24]
(changed description) We need to get Travis.ci working with both the dryad and the stash repositories in github to run tests on those repos.

**Comment by sfisher** [comment]
The Stash repository has had running tests for a while.

I spent a bunch of time getting the dryad tests to run (which uses rspec to run Capybara to automate Chrome to run through tests).

It was fairly painful to get these test working again because of changes in our login and also the way we spread things across three repositories (2 for code and 1 for config).

In case it's helpful for future problems, stuff I had to do:

- added explicit code to do rake db:migrate which caused failures without since we're not currently tracking schema.rb file in the dryad repo.
- modify the configs in .config_travis
- duplicate some of the app_config test environment to the real app_config because in travis it uses the fake one and when running from a local dev machine it uses the real one and doesn't overwrite the real config with the fake one.
- code changes to work around errors created if there is no shibboleth tenant to display in a list
- moving the value for the default tenant when clicking the "not a partner" into the app_config and using that in code rather than a hard coding (bad me).
- fixing some weirdnesses in the tests that stopped parsing the yml file used by geoblacklight and needed a special flag after Daisie's new environment came into the config.  (needed a true flag to recognize aliases after that.)

It turned out to hard debug some of the problems because they were caused by interactions between environments.

The three PRs for these show tests passing now for dryad repo on travis.ci. Also, works in a local environment where there may be additional tenants besides the 'localhost' testing one.
