### ISSUE TITLE
Highlight difference between PPR and immediate publication for users

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2509]
**Problem description, and links to relevant helpdesk tickets:**

Authors often miss the options at the end of the form for PPR and payment.

**Describe the solution you'd like:**

"Offer PPR 'Yes'/'No' checkboxes
Relocate question to separate page within the submission form (or completely new page that includes all confirmation/acknowledgements for payment, license, species or human data, etc. "

**Additional context:**
Instead of an opt-in checkbox, offer option to opt-In or opt-out -- confirming whether curation can begin or if the author prefers to wait for the peer review process to complete. This will reduce accidental publication and/or confusion with authors and journal offices which can damage reputation and relationships. If we can make the submission form more dynamic, the PPR option can be offered upfront if the options for "a manuscript in progress" or "a published article" are selected. For journal titles that have PPR auto-enabled, authors will not be able to de-select the PPR checkbox. 

NOTE: For this ticket, change PPR checkbox to radio buttons. Reorganize and redesign full submission wizard at a later date.

**Comment by jleighherzog** [comment]
"or for 6 months in cases where we do not know your related article's status" - this line seems problematic because nothing actually happens at the 6-month mark except for the first reminder that is sent to the author. The way this is worded makes it seem like we'll release it to the queue for curation after it's been in PPR for 6 months. 

Consider: 
By choosing this option, your dataset will be kept private during your related article's peer review process. Your submission will not be evaluated by curators or published until you choose to release your submission from this status by deselecting this checkbox. While your article is in peer review, your Dryad data files can be shared with collaborators and/or the journal using a private URL that will be provided upon successful submission. 

Please feel free to rework the wording!

**Comment by ahamelers** [comment]
Currently it says this, which I find even more confusing around the 6 month stuff:

> By choosing this option, your dataset will be private during your related article's peer review period. You will have access to a private dataset download URL to be shared with collaborators or the journal. Your dataset will not enter curation or be published. Because we may not have the status of your related article, the default for this period is six months. Please [email us](mailto:help@datadryad.org) or uncheck this box at any point if your dataset is ready to enter curation.

I like your solution to just get rid of the time thing entirely. Do we really also want to get rid of the email suggestion as well?

**Comment by ahamelers** [comment]
I'm going to open a new issue for rewording this @jleighherzog 🙂

**Comment by jleighherzog** [comment]
Ok, please include a link to the new issue here! I'll review it ASAP. I like the email us option.
