### ISSUE TITLE
SUNY authors report missing some datasets

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2518]
### Bug description:

7 DOIs that were previously included in the authors report for SUNY (2019-2022) are no longer appearing in the report results, 6 seem from the author affiliations like they still should be included:

```
10.5061/dryad.0zpc866tt  # This one is probably reasonably excluded
10.5061/dryad.15dv41nwr
10.5061/dryad.63xsj3v0m
10.5061/dryad.k0p2ngfb1
10.5061/dryad.ngf1vhhx7
10.5061/dryad.p8cz8w9m6
10.5061/dryad.zw3r2285g
```

### Steps to reproduce:

Run the report from https://github.com/CDL-Dryad/dryad-app/blob/main/documentation/reports.md#authors-at-an-institution-report-from-sql for this list of ROR IDs

```
"https://ror.org/01q1z8k08",
"https://ror.org/008rmbt77",
"https://ror.org/05ms04m92",
"https://ror.org/0306aeb62",
"https://ror.org/02n1c7856",
"https://ror.org/057trrr89",
"https://ror.org/02rrhsz92",
"https://ror.org/00qv0tw17",
"https://ror.org/05vrs0r17",
"https://ror.org/03g1q6c06",
"https://ror.org/02r3ym141",
"https://ror.org/033zmj163",
"https://ror.org/000fxgx19",
"https://ror.org/040kfrw16",
"https://ror.org/05a4pj207",
"https://ror.org/02v9m6h26",
"https://ror.org/02d4maz67",
"https://ror.org/03j3dv688",
"https://ror.org/01597g643",
"https://ror.org/032qgrc76",
"https://ror.org/05qghxh33",
"https://ror.org/012zs8222",
"https://ror.org/01y64my43",
"https://ror.org/0041qmd21"
```

### Expected behavior:

All relevant DOIs would be included.

**Comment by sfisher** [comment]
I'm not sure of any previous report where they were included since I don't know how that report was generated, yet it appears to me that most of these probably were never included since the affiliations don't seem to have been entered correctly.

You can try a query like this to see all author affiliations across all versions of a dataset (replace the identifier_id) in the query below:

```
SELECT res.id as resource_id, res.created_at resource_created, resource_id, affil.*
  FROM stash_engine_identifiers ids
	JOIN stash_engine_resources res
      ON ids.id = res.identifier_id
    JOIN stash_engine_authors auth
      ON res.id = auth.resource_id
    JOIN dcs_affiliations_authors aff_auth
      ON auth.id = aff_auth.author_id
    JOIN dcs_affiliations affil
      ON aff_auth.affiliation_id = affil.id
  WHERE ids.identifier = '10.5061/dryad.zw3r2285g'
  ORDER BY res.id;
```

Results for this query are below.  Sorry I chopped off the header row by mistake on some of the screen shots, but it's the last column.  You'll see that the SUNY institutions were not entered correct for most of them (there are * on the name) and the ROR affiliation wasn't entered.

![Image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/105433/63364170-37c1-476d-8095-cf3e861b7a26)


![Image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/105433/efa4bb8e-10b5-48ee-867e-46de2b8625c6)


![Image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/105433/b76cf23d-5c0a-491a-9cd3-68edbd25cfd2)


![Image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/105433/8243879e-a2e9-412c-808c-34fe44293d56)


![Image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/105433/61262301-3516-4c33-b87f-b795dcc35ca4)


![Image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/105433/06f5bd18-1913-4ec2-802b-e5e35272ac39)

---

The one exception to this is `10.5061/dryad.k0p2ngfb1` where it appears that a SUNY school was belatedly entered correctly in the last version (resource_id: 226421).

![Image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/105433/fa365d62-bd18-45f3-81ff-baf1a2884c74)

The "authors at an institution report" above gives lots of information such as author names, university names and created and publication dates so it only works with the first version that was embargoed (metadata released to the world) or published.

if we use the something besides the first released version then the publication date will be wrong and later than the real first publication date and I don't think we want to show a subsequent re-publication date as the publication date.

It looks like this one was first published with missing data about this affiliation (in resource_id 226368) before being republished again later.

If all we need is a list of DOIs that are affiliated by authors with an institution in some way across all versions, whether published or not (and without all the extra data about other stuff in the query), then it could probably be a lot simpler query.

FROM the query above in this comment, change the `SELECT` to `SELECT DISTINCT ids.identifier` and change the WHERE to 'WHERE affil.ror_ID IN ( <list of items> )` and remove the ORDER By.

**Comment by ahamelers** [comment]
I'm not sure how the previous report was generated! From Donna I read that SUNY "was sent" the report in 2022. Maybe @ryscher knows more? https://docs.google.com/spreadsheets/d/1QNsiZxAp8RQQoP3OaP7y95z4czgqGt0ggBowg9f54zk/edit?usp=sharing

**Comment by sfisher** [comment]
It may have matched free text names for anything with SUNY or "State University of New York" or some other random string matches.

In any case, I've updated these entries without correct RORs to have the names that look like the right ones from ROR and to put in the ROR ids.

```
UPDATE dcs_affiliations
SET long_name = 'University at Buffalo, State University of New York',
    ror_id = 'https://ror.org/01y64my43'
WHERE id IN (39020, 39874, 16746, 10579);
    
UPDATE dcs_affiliations
SET long_name = 'Stony Brook Medicine',
    ror_id = 'https://ror.org/01882y777'
WHERE id IN (15639);

UPDATE dcs_affiliations
SET long_name = 'SUNY Buffalo State University',
    ror_id = 'https://ror.org/05ms04m92'
WHERE id IN (26992, 33913);

UPDATE dcs_affiliations
SET long_name = 'SUNY Upstate Medical University',
    ror_id = 'https://ror.org/040kfrw16'
WHERE id IN (11647);
```

The first one clearly also seemed off since `Consorci Institut D'Investigacions Biomediques August Pi I Sunyer` (the only author affiliation) doesn't seem to have anything to do with SUNY.  Though someone's last name contains SUNY (`Sunyer`) so almost certainly this was a match based on text-only.

**Comment by ryscher** [comment]
Catching up to this.... the extra report was extracted from the shopping cart reports, so it was essentially someone going through a bunch of historical deposits with a string match for "SUNY"
