### ISSUE TITLE
Change corresponding author

### ISSUE THREAD

**Issue by rcurty** [CDL-Dryad/dryad-product-roadmap#2530]
Not a bug, but a request from the depositor. 
Please change the corresponding author for this deposit
10.25349/D9N327 to Rachel Segalman. Audra should be listed as the second author. 
Thanks!

**Comment by sfisher** [comment]
I'd want to check that this is what the author really wants before proceeding since the author order and "corresponding author" are unrelated concepts.

- The corresponding author is the one who is submitting the dataset and working with curators and they can be in any position in the author order.
- The author order can be set and adjusted by the user (or curators) by clicking and dragging the drag handles next to the author "cards."  Just click on the 3 lines next to it and drag to the position you like. Alternately you can use keyboard by tabbing to the item and pressing enter and using keyboard arrows.

### one order
![Screenshot 2023-05-18 at 3 42 43 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/105433/076d3b4d-567e-4cfb-8f0f-b831affb1c33)
### another order after draggin
![Screenshot 2023-05-18 at 3 42 59 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/105433/2e783b34-f95f-4669-80a6-320da02c6de2)

**Comment by rcurty** [comment]
She is a graduate student depositing on behalf of her group and asked not to be the corresponding author in Dryad since she won't be the best person to answer more in-depth questions about the data. I have noticed this is a common practice (students serving as depositors for PIs), and a check box so that the depositor can select different roles for contributors could be a nice feature in the future. Does Rachel Segalman have an account yet?

**Comment by rcurty** [comment]
She is a graduate student depositing on behalf of her group and asked not to be the corresponding author in Dryad since she won't be the best person to answer more in-depth questions about the data. I have noticed this is a common practice (students serving as depositors for PIs), and a check box so that the depositor can select different roles for contributors could be a nice feature in the future. Does Rachel Segalman have an account yet?

**Comment by sfisher** [comment]
This makes lots of sense.

Rachel Segalman had an account so I updated the information to make her the contributing author.

It looks to me like the author order is currently:

Rachel Segalman, My Nguyen, Glenn Fredrickson, Songi Han and Audra DeStafano--so I think that the author ordering part is correct.

Let me know if you see any issues with it.

**Comment by rcurty** [comment]
Thanks!
