### ISSUE TITLE
Clean recent Merritt errors

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2547]
Determine what happened to these datasets and how best to recover

- doi:10.5061/dryad.t76hdr85g
- doi:10.5061/dryad.d51c5b07r

**Comment by sfisher** [comment]
These are now submitted.  They turned out to be DataCite::Mapping errors for empty subjects.

This was a big puzzle to figure out since the only error in the submission was "Value cannot be empty or nil" (no idea what value or where it was coming from).

But then I search the server logs for this same error and saw it was coming from `datacite/mapping/subject.rb` in the stack trace.

Removed empty subject from the keywords and from the linking table and resubmitted and they went through.
