### ISSUE TITLE
Access data files through S3 directly

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2637]
Update data file access module to obtain presigned URLs directly from AWS. (Does not apply to ZIP files)

- [x] ❗ Ensure that Dryad application has the access needed to create presigned URLs for anything in the buckets
  - Get access to development environments (including local ones if possible for development buckets)
  - Reuse existing  access credentials in our configuration?
- [x] Refactor S3 wrapping library to allow bucket to be changed (with new) and tests updated.
- [x] Method to calculate the correct string to obtain file with forward delta versioning of files that Merritt uses.
- [X] Create method to generate presigned URLs for file IDs for data files
- [x] Update downloads to use new presigned URLs
- [x] Update API to use new presigned URLs
- [x] Testing for new functions
- [x] Testing known problem cases (that Merritt may be treating idiosyncratically) such as characters like `% # <space>` and stuff like non-english characters.
- [x] Add workaround for differences in Merritt and Dryad version tracking (verifying files exists and walk back through history to find file if not present)

See https://docs.google.com/document/d/1lFGCXtiuHc0AwWXu4F_MXAwpKlIKk2gvziilrvX1q4I/edit?usp=sharing

**Comment by ryscher** [comment]
Dependent on #2782

**Comment by sfisher** [comment]
We hit a snag with this since Merritt doesn't honor when we ask to add a new file to a version if a file with the same SHA-256 exists in any other older version.  In that case it simply considers it a pointer to the other file.

I don't see a great way around this issue unless maybe we get the SHA-256 for all the files that exist in Merritt and put them into our database.  :-/

We need to discuss.
