### ISSUE TITLE
Download dataset button not working; version error

### ISSUE THREAD

**Issue by lauradryad** [CDL-Dryad/dryad-product-roadmap#2648]
**Bug description:** In the dataset https://doi.org/10.5061/dryad.2rbnzs7qq, the download data is not working. This happened before in [issue #2400](https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2400). Unfortunately, I published this one before I realized. 

**Steps to reproduce:** Click the 'download dataset' button; it spins for a second and then does nothing. 

**Expected behavior:** Latest version should download.

**Comment by sfisher** [comment]
Hi @lauradryad .  Are you still seeing problems downloading this dataset?  When I try downloading it took a long time to assemble the dataset into a zip file since it's very large at almost 50GB, but I was able to begin a download.

I didn't download the whole thing since I didn't want to wait 2+ hours for the full download, but it was transferring the zip file before I canceled.  I'm not sure if you have any more information about behavior when you attempted a download.

I also examined the database to be sure all data was consistent between the stored versions in Merritt and our database and it all appeared correct and consistent.

I'm not seeing the problem you mention, but if you can give a bit more information to replicate the problem then I can look into it further.
