### ISSUE TITLE
Funders with N/A cause submission to fail

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#2661]
It doesn't happen often, but I've seen a few of these over the past while.

People (or the form) for funders put N/A in the `contributor_name`.  This causes the submission to fail DataCite integrity checks because the `contributor_type` is not set and it is required.

Can we consider leaving N/A out entirely and not adding a record in the DataCite data if this is selected?  If not, we will need to add code to ignore N/A values and not attempt adding to the datacite.xml.  Or perhaps the placeholder cruft belongs elsewhere, IDK.

**Comment by ahamelers** [comment]
Sounds good to me! I left the "N/A" in because that's what the previous requirement was and there were tests/checks around it, but it would be simple enough to either mark "no funding" a different way and remove those tests, or to check and stop "N/A" funders from being sent to datacite at the send point.

**Comment by ahamelers** [comment]
@sfisher , looking at the code, even the N/A funders should have contributor_type="funder" set, and only things with contributor_type="funder" are being sent as funders to DataCite. So I'm not sure where this problem is stemming from—but we should probably be excluding the N/A funders from being sent to Datacite anyway, right?

**Comment by sfisher** [comment]
Yeah, I don't think DataCite would want to display N/A as a funder even if the other metadata was OK.  :-)
