### ISSUE TITLE
Pub Updater suggesting to match and replace existing article DOI

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2667]
Priority: Low

Revisit Pub Updater configuration. In the examples attached, Pub Updater is attempting to match and replace an existing article DOI with a link to a preprint: 

![Screen Shot 2023-07-19 at 8 21 05 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/ef293135-6b74-46aa-9be4-f270a7df6aab)

![Screen Shot 2023-07-19 at 8 21 31 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/7e09bf62-f49a-4cf0-8e72-9ee86daa30ee)

**Comment by ryscher** [comment]
First pass workaround is to choose "Reject" for all of these. 

As for updates to the PubUpdater, should we auto-reject any suggestion when the dataset already has any relationship to an article DOI? Or only when there is a primary_article DOI?

**Comment by sfisher** [comment]
I've started working through this, yet this ticket brings up some questions.

- I'm not certain that we always have reliable information about what kind of work something is or if it is truly related.  I found there is a "type" which sometimes seems to be set to "journal-article" in crossref and sometimes it's something else (like "posted-content").  Maybe that gives a clue, but I wouldn't count on it always being right since CrossRef's data is all over the place in reliability.
- Honestly, it's useful for a human to make a good decision about stuff rather than accepting whatever CrossRef happens to have and lots of the things that it brings up are just based on similar titles and authors rather than having any linking information between datasets.  GIGO (Garbage In, Garbage Out and humans need to use some judgment.)
- It seems to me that there is a larger question this brings up and it feels to me that the design of simply accepting and *overwriting data* or *not* is too simplistic for what the *implicit* requirements are around this feature.  Maybe we can get better requirements rather than the piecemeal approach since it seems like tinkering around the edges isn't making anyone happy.
  - I don't know if people need to choose to overwrite *each* individual field?
  - Or maybe there should be additional buttons like *add primary article DOi* or *add preprint* or *others*? that *don't* overwrite any data and just add the relationship without overwriting?
  - Maybe something else?
