### ISSUE TITLE
Investigate harvesting from Clarivate

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2673]
Follow up on helpdesk issue related to Clarivate's use of Dryad data and respond to the researcher appropriately.

**Comment by bryanmgee** [comment]
@ryscher [SF 25882](https://dryad.lightning.force.com/lightning/r/Case/5003h00000dV58XAAS/view), author followed up with Clarivate's response to her about this: 

"Our investigation has determined that some Dryad datasets are being registered under a DOI prefix associated with UC Davis, rather than Dryad. While we include all datasets bearing DOI prefixes associated with Dryad as part of our coverage of the repository, we were unaware that some UC Davis datasets are also Dryad datasets. We will communicate with Dryad to determine how best to include all such content, including these missing records."

**Comment by ryscher** [comment]
Final response can go to the author via https://dryad.lightning.force.com/lightning/r/Case/5003h00000dV58XAAS/view

**Comment by sfisher** [comment]
All the datasets will be DataCite datasets soon, though some of these older ones will have a different prefix.  I know Maria G. is going to be investigating whether these DOI shoulders from campuses were ONLY used for Dryad or if they have other uses in the library on on campuses, also.  It makes a difference on whether she transfers the whole shoulder to DataCite or only some identifiers.

If they're used exclusively by Dryad then we can supply a list of the shoulders to Clarivate and they will additionally be DataCite managed identifiers soon.

**Comment by ryscher** [comment]
Steve is following up.
