### ISSUE TITLE
Forwarding when search has one result

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2676]
Previously, there was functionality to forward users to the landing page when a search resulted in a single result. This behavior appears to have changed. Ways to achieve a single result:
- Enter a data DOI in the search box
- Search for "Data-driven bioregionalization: A seascape-scale study of macrobenthic"
- Follow the Dryad link in the LinkOut resources for this article: https://pubmed.ncbi.nlm.nih.gov/37147850/

**Comment by ahamelers** [comment]
Previous issue: #2037
PR: https://github.com/CDL-Dryad/dryad-app/pull/1235

**Comment by ahamelers** [comment]
I think I have fixed the linkout/discover issue. I can't find evidence that single search results have otherwise been automatically forwarded (although this would be a great feature to add!), and I can't see an obvious way to do this—it would require hitching in somewhere between the SOLR search and results page to try to forward the result, which with our current setup seems to be a complicated geo/blacklight question

**Comment by ryscher** [comment]
Ok, let's revisit this after we determine the future of Geoblacklight.

**Comment by ahamelers** [comment]
I didn't say I wouldn't figure it out!
