### ISSUE TITLE
Remove "README.md missing" pop-up from submission form

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2679]
**Priority**: medium
**Impact**: Authors (confusion), Curators (Helpdesk queries)

When authors upload a README file in a format other than .md, a pop-up window appears on the final page of the submission form. This causes author confusion, increases queries to Helpdesk, and stalls the submission process. 

Can we remove this pop-up if/when a README **is** included, regardless of format? The pop-up message is misleading because a README file in .md format _is not_ required for publication. 

Let me know if you have any thoughts/suggestions/questions about this request. 

![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/cde05506-a759-448d-93e9-b2d0200a8026)

**Comment by ahamelers** [comment]
@jleighherzog We have a multi-step README user experience improvement project in progress, currently in the hands of the CDL UX team. This includes steps to make the README in markdown format absolutely mandatory, but also much more seamless (and with less of an emphasis on "why choose markdown as a format", more of an emphasis on "why have a README at all", since the UX team has discovered we really need to go back to basics with this). 

The next step will be to actually display the README on the landing page for each dataset, at which point any dataset that does not have a README in markdown format will suffer a bit. So even in the interim, we really do want to encourage users to upload a markdown README; therefore I do not think this change is a good idea for now.

**Comment by jleighherzog** [comment]
@ahamelers : Thanks for the update. I'll close this ticket.
