### ISSUE TITLE
AGU ceasing agreement effective Aug 1

### ISSUE THREAD

**Issue by mark02139** [CDL-Dryad/dryad-product-roadmap#2685]
**Problem description, and links to relevant helpdesk tickets:**
Maria informs me that AGU will not be renewing its agreement with Dryad, effective August 1st.
They are on the deferred plan, billed quarterly.

**Describe the solution you'd like:** 
For their final quarterly invoice for calendar Q3 (Jul-Sep), we need to count only submissions made in July for invoicing purposes.

@ryscher @ahamelers

**Comment by ryscher** [comment]
Updated settings for AGU journals. All authors from now forward will need to pay the DPC. 

I'm going to keep this ticket open, because we will need to do a little special handling when we run the quarterly reports to ensure AGU gets the proper bill for July.

**Comment by ryscher** [comment]
To run the Q3 report, I took these steps:
- reviewed the base shopping cart reports and converted "deferred" items for AGU to the "tiered" plan
- made a copy of the `shopping_cart_report_2023-Q3.csv` report that removed all datasets that were listed as an AGU journal, but paid by some other method (because they were submitted after the effective date)
- temporarily re-instated the payment plan so the tiered report calculation would have the correct payment information `update stash_engine_journals set payment_plan_type='TIERED' where sponsor_id =42;`
- ran the tiered processor as normal
- removed the temporary payment plan `update stash_engine_journals set payment_plan_type=null where sponsor_id =42;`
-
