### ISSUE TITLE
Create feedback survey on submission process and link to survey after successful submission

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2699]
Work on this with @sarahklippincott

- [ ] Create feedback/"rate my experience" survey for submission process
- [ ] Include "sign up for future testing/allow us to contact you about this feedback" form option(s)
- [ ] Link to survey on site and in email after successful submission

From #2670

**Comment by ryscher** [comment]
@jleighherzog There have been several surveys under discussion, which is why we have a meeting scheduled Sept 18 to coordinate. The survey described in this ticket was developed by Audrey and Sarah for the purpose of getting feedback on the internals of the submission system, and it is currently live. When we meet on the 18th, we can discuss how best to align with the broader survey that you are proposing.

**Comment by jleighherzog** [comment]
Thanks for clarifying, @ryscher
