### ISSUE TITLE
Proposed changes to Curation Stats page

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2721]
![Screenshot 2023-08-08 at 9 19 06 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/f8be0d1a-eb6d-4158-b796-5cb815af615c)

Proposed updates to the [Curation Stats](https://datadryad.org/stash/curation_stats) page

**Date** = Keep. Consider updating the timestamp from UTC to EST to improve accuracy. 

**Curated** = Remove. This is a total that can be easily calculated by combining "PPR to Curation" + "Curation to Published"

**Queue size** = Calculation is incorrect. The count should include all datasets currently in ‘Submitted’ status and ‘Curation’ status at the moment the calculation is captured. Could be out of sync because of the UTC time stamp. For example, curation on Saturday is reflected in Friday stats. See ticket #2528. _Note: Revised datasets are placed in automatically placed in 'Curation' status; update requested in this ticket #2510_ 

**New** = Calculation is incorrect, let's revisit during our weekly Dev + Curators meeting

**New to Submitted** = Calculation is incorrect, let's revisit during our weekly Dev + Curators meeting

**New to PPR** = Keep

**PPR to Curation** = Keep

**Curation to AAR** = Keep

**Curation to Published** = Keep

**Embargoed** = Remove. There are so few datasets that enter this status because only a few society titles have an auto-embargo process in place. [Alliance of Crop, Soil, and Environmental Science Societies (ACSESS)]

**Withdrawn** = Keep

**Author revised** = Keep. The calculation should be checked to ensure it's correct. See notes for 'author versioned' below.

**Author versioned** = Calculation is incorrect. For example, 47 datasets were recorded for Aug 1, but we estimate only a handful of submissions are versioned per day (~5-10).

**Comment by jleighherzog** [comment]
See related ticket https://github.com/CDL-Dryad/dryad-product-roadmap/issues/2705#issue-1830292720 that outlines discrepancies.

**Comment by bryanmgee** [comment]
Proposed/revised definitions for what should be tracked in each metric:

Queue size = all datasets currently in Submitted (regardless of whether they were previously published or embargoed) or Curation status

New = probably can be removed as a sum of New to Submitted and New to PPR (ala Jess suggesting to remove 'Curated')

New to Submitted = number of datasets submitted without PPR for the first time, should therefore _not_ include author resubmitting a dataset already submitted without PPR or anything that has previously been published or embargoed

New to PPR = number of datasets submitted with PPR for the first time, should not "double-count" when a dataset is updated and resubmitted but kept in PPR

PPR to Curation = I think we can discard this one, going from PPR to Curation is not part of the normal workflow because that would require a curator to remove it from that status and would likely occur only if an author emailed HD and was having a lot of technical problems figuring out how to remove from PPR (which should be even easier with the new interface)

Curation to AAR = number of datasets that changed from Curation to AAR on that day; should be some kind of measure that may already be in place to not double-count within a certain timeframe (e.g., 24 hours) if a dataset is repeatedly sent from Curation to AAR and then returned by the author

Curation to Published = number of datasets that changed from Curation to Published on that day

Embargoed: remove

Withdrawn = number of datasets that changed from any status to Withdrawn (both manual or via API)

Author revised = number of datasets that changed from Action Required to Curation

Author versioned = number of datasets that changed from Published or Embargoed to Submitted

**Comment by bryanmgee** [comment]
Oh also, for that real-time stat box at the top, this is what the stats should be:

- Line 1: self-explanatory
- Line 2: should be equivalent to Queue Size but tracked in real-time
- Line 3: line 2, but time-restricted

These are also not calculating right, which is at least not related to timestamping since these should be updating in real-time and thus can be groundtruthed in real-time, but it's unclear if this is a system lag in calculating the stats or if there is something off in the formula (unknown to me whether they are linked to the daily Curation Stats reported metrics)

![Screen Shot 2023-08-15 at 8 14 05 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/113212676/6aa1e3d3-790b-482d-a7f5-aad7386c4b9e)

**Comment by ahamelers** [comment]
> Curated = Remove. This is a total that can be easily calculated by combining "PPR to Curation" + "Curation to Published"

This is tracking things that were curated, which is not these two columns. As the description says: "The number of datasets processed that day (meaning the status changed from 'curation' to 'action_required', 'embargoed', or 'published')"

Are you sure you want it removed?

**Comment by bryanmgee** [comment]
Jess might have mistyped the original formula – the Curated column should be **Curation to AAR** + **Curation to Published**; since we're fine keeping both of those, I think Curated can be removed.

**Comment by ahamelers** [comment]
Proposal for dealing with times: #2733

**Comment by ahamelers** [comment]
> Embargoed = Remove. There are so few datasets that enter this status because only a few society titles have an auto-embargo process in place. [Alliance of Crop, Soil, and Environmental Science Societies (ACSESS)]

If you are getting rid of this, you will not be able to add the remaining curation-to-action and curation-to-published columns to truly reach the 'curated' total, which includes these as well. I see there were only 3 in the last month but that would be 3 you'd miss. Should we fold these into the curation-to-published column?

**Comment by ahamelers** [comment]
> PPR to Curation = I think we can discard this one, going from PPR to Curation is not part of the normal workflow because that would require a curator to remove it from that status and would likely occur only if an author emailed HD and was having a lot of technical problems figuring out how to remove from PPR (which should be even easier with the new interface)

Apparently this isn't quite like the other checks, it's not looking for direct changes from ppr to curation:
```
    # The number of previously PPR datasets that entered Curation that day
    # Note that this is intended to be more inclusive than other transitions. It includes
    # any dataset entering Curation status that was in PPR more recently than it was in a
    # prior curation status.
```

**Comment by bryanmgee** [comment]
Re: Embargoed – I think it's fine to fold into Curation to Published; auto-embargoes are now rare, and custom embargoes have always been exceedingly rare; sample size is too small to attempt to detect any trends, which there shouldn't really be (if there are, they would specific to the few journals that support auto-embargoes, and we could get that data another way).

Re: PPR to Curation: interesting to know – this makes more sense after Ryan and I deduced that New to Submitted only counts datasets that were submitted on a given day and that have never been in PPR previously. So they are not overlapping but not necessarily fully complementary either since one involves an author action as the latest action and the other involves a curator action as the latest action. Could we add a column that is PPR to Submitted? I think it is still important for curation to get an idea of how many datasets were first submitted without PPR on a given day, whether they were previously in PPR or not.

**Comment by ahamelers** [comment]
Would it make sense to change PPR to Curation to PPR to Submitted? I think everything goes from 'PPR' through 'submitted' to get to 'curation' anyway

**Comment by bryanmgee** [comment]
That's fine with me!
