### ISSUE TITLE
Update README template

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#2726]
The curators are working on edits to the current README template (https://docs.google.com/document/d/1_Lg3xtLFwFbOI697bIuBPPLpQKqYLJ5I7j8UXVlXyIQ/edit)

**Comment by ahamelers** [comment]
@bryanmgee @jleighherzog @lauradryad 

[Good notes from Scott on the README pull request 
](https://github.com/CDL-Dryad/dryad-app/pull/1306#issuecomment-1678235383)
> Thank you for doing all this, @ahamelers .
> 
> It looks really beautiful and is so much better than our old process and you've put a ton of great work into this.
> 
> Filling in the extra README made me wonder how annoyed I would be if I was an author and I needed to re-fill the _title_ (maybe we could pre-fill if no readme exists yet) and also the related works.
> 
> I also found myself questioning inclusion of all the related works. I found myself thinking that maybe we should put a link to the DOI or Dryad URL in the readme so someone could get all the rich and up-to-date metadata on the live site in case they lost track of where they got the data files from but I wasn't sure it needed repeating in there.
> 
> I also wasn't sure how much some of the stuff overlaps with what they've already filled. Like I can see people just putting in the abstract for "give a brief summary" section (whether that is meant to be that way or not).
> 
> I think these are all metadata questions and maybe I'm not the right person to answer them so I might be completely off base. However, as a user if I interpret the readme as filling in information I've already entered and I have to retype it all again, then I'd be annoyed.

**Comment by ahamelers** [comment]
> Usage Notes: this would be useful, but it's used quite variably and sometimes could slot into the Code/Software section of the README and other times would not line up

Based on the UX testing feedback, we're getting rid of the separate Usage notes now that the README will be required (for submissions after this release it will only appear if someone has already put stuff there before the release). The thinking was, based on the instructions for the Usage notes and the README, it is content they are meant to put in the README and is entirely duplicative. Let me know if you disagree—if there is some reason for a separate Usage notes it will need to be really differentiated for our confused users.

**Comment by bryanmgee** [comment]
No, I like that, we get a lot of garbage in the Usage Notes right now

**Comment by jleighherzog** [comment]
Re: Methods
Do we remove it from the README because it's already captured in the metadata?

**Comment by ahamelers** [comment]
> Re: Methods Do we remove it from the README because it's already captured in the metadata?

As far as I am aware, currently the README template does not ask for Methods.

**Comment by jleighherzog** [comment]
@bryanmgee @lauradryad @ryscher @ahamelers 

Met with Bryan and Laura, we have the following suggestions/requests: 
1) Keep template as-is. We'll revisit based on feedback/HD messages received. 
2) Keep Methods section on dataset landing page; good to have for those submissions that don't have scholarly outputs
3) Possible to auto-transfer the title into the template? Often we ask authors to update their titles because they are insufficient (e.g. "Raw Data"). If it's not auto-updated or generated, it's another check for the curators to perform.
4) Possible to auto-populate and include DOI and citation in the README file? 
5) Q: Remove README from landing page. We anticipate there will be formatting issues and readability concerns, curators will _need_ to heavily copyedit the README text **because** it will be displayed front and center on the landing page. Sometimes these README files can be a giant wall of text that will bury the other metadata fields and (Funding, etc.)
6) Q: Should there be a "Beta" label and/or feedback button for this feature? A link? 

Will these blue boxes be rollout out too? Will this box disappear upon publication of the dataset? 
![Screenshot 2023-08-25 at 6 47 11 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/02ee4c25-ea7f-4e90-8648-9ad7e8e5d7b1)

**Comment by jleighherzog** [comment]
Example of how a README might display on the landing page: 

[README.md](https://github.com/CDL-Dryad/dryad-product-roadmap/files/12443980/README.md)

**Comment by ahamelers** [comment]
>     3. Possible to auto-transfer the title into the template? Often we ask authors to update their titles because they are insufficient (e.g. "Raw Data"). If it's not auto-updated or generated, it's another check for the curators to perform.
> 
>     4. Possible to auto-populate and include DOI and citation in the README file?

Yes, both of these are possible.
 
>     5. Q: Remove README from landing page. We anticipate there will be formatting issues and readability concerns, curators will _need_ to heavily copyedit the README text **because** it will be displayed front and center on the landing page. Sometimes these README files can be a giant wall of text that will bury the other metadata fields and (Funding, etc.)

We discussed this a lot in the curator meeting today. The README is meant to be the main file representing the dataset regardless of how it is accessed. We did not know the level of copy-editing you have already been doing, and did not intend for the README to need to be copy-edited, but it has been intended to be in the landing page for some time. For now, we will leave the README on the landing page, but restrict the size of what is shown, and have a “view more” button.
 
>     6. Q: Should there be a "Beta" label and/or feedback button for this feature? A link?

I thought I could answer this but now I'm not 100% sure which feature you mean? For the README generation as part of the submission, that should feature heavily in the submission feedback survey we are developing (#2699 )

> Will these blue boxes be rollout out too? Will this box disappear upon publication of the dataset? ![Screenshot 2023-08-25 at 6 47 11 PM](https://user-images.githubusercontent.com/76497320/263406804-02ee4c25-ea7f-4e90-8648-9ad7e8e5d7b1.png)

Yes and yes—these are just an altered design of the existing citation and sharing link sections, so they take up less space and have a built in copying function.
