### ISSUE TITLE
Handle READMEs that do not contain text

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2762]
If a legacy README does not contain textual content, shame on the author! 

In these cases, don't bother trying to display the README content.

Examples:
- https://datadryad.org/stash/dataset/doi:10.5061/dryad.pc866t1th
- https://datadryad.org/stash/dataset/doi:10.5061/dryad.djh9w0w4x

**Comment by ahamelers** [comment]
We've decided not to render previously uploaded README files on the landing or review pages for now, so this can wait for a later date.

If we want to attempt rendering previously uploaded files in future, rather than attempting to convert READMEs from incorrect formats or encodings, we might want to next limit ourselves to ONLY those already in UTF-8

**Comment by ahamelers** [comment]
I propose the following:

- On the landing page and review screen, attempt to render only 1) READMEs created through the new system and 2) README markdown files previously uploaded and already encoded in UTF 8
- On the "Prepare README" page, attempt to convert and load (for editing) anything uploaded as 'README.md' in any encoding.

I think we can safely ignore any non-UTF-8 encodings for the rendering. If any authors have a strong desire to see their READMEs rendered, they can create a new version and copy the content into the screens for the new process.
