### ISSUE TITLE
System does not recognize README file

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2764]
**DOI:** 10.5061/dryad.bcc2fqzfg
**Title:** Opposing patterns of altitude-driven pollinator turnover in the tropical and temperate Americas

The author emailed to say that she uploaded the revised README, but the system then said she had no README on the Review and Submit page. I forcibly edited the dataset (she left it In Progress) and verified this. I have also attempted the following, all of which returned the same "Include a README file" error:

- Erasing the existing content and importing from the README file she sent me, without applying any formatting (none used originally)
- Erasing the existing content and importing from the README file she sent me, and then applying Markdown formatting like headers
- Pasting the revised README from a text editor over the existing content
- Erasing the existing content, allowing the system to replace it with the template, and typing some content into the README
- Erasing the existing content, allowing the system to replace it with the template, and pasting in the revised README from a text editor

**Comment by ahamelers** [comment]
@bryanmgee Please correct me if I'm wrong. It looks like the README is overwritten and included just fine, but that there is something wrong with the actual check for the README content. 

I'd made myself the current editor of the dataset to verify this and changed the readme content. I will now set it back to you; hopefully you can overwrite what I did!

I think this problem is because of the age of the dataset—the old check, for before markdown READMEs were required, is looking for an included file with 'README' in the title. I think this was actually intended to be a more lax requirement to allow for .txt README files, but obviously it needs to be updated to allow for the new method!

**Comment by bryanmgee** [comment]
@ahamelers still no dice for me... I even discarded the changes and then went back in, and it's still giving me the error

**Comment by ahamelers** [comment]
Yes, you should be able to change the content, but you will still see the error and be unable to submit. I've put a fix for the error in a pull request for the next release. Is it needed more urgently than that?

**Comment by bryanmgee** [comment]
For this dataset, probably not, but I just got another email with an author experiencing the same issue, and they are in a much greater hurry, so if possible, it would be ideal to release before that
