### ISSUE TITLE
System not correctly updating status for some datasets

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2768]
Curators have identified two datasets where status changes are not being correctly logged by the system:

1. DOI: [10.5068/D1339F](https://datadryad.org/stash/ds_admin?q=%2210.5068%2FD1339F%22&sort=relevance&commit=Search&tenant=&editor_id=&curation_status=&publication_name=&sponsor_org=&utf8=%E2%9C%93). This dataset was initially curated on 8/23/23 by BG (metadata) and then remained dormant for several days (took a while to download and check 185 GB of files...). The last modified date (Aug 23, 2023, 1:56 PM) records this curation. Since 8/27/23, I have been trying to publish this dataset, but it constantly gets hung up on the pop-up window, even though other datasets can be published without issue in the same interval (i.e. not clearly a DataCite issue). However, it then adds/updates the publication date on the table view of the Admin Site, even though this is not logged in the Activity Log, and the DOI remains inactive.

2. DOI: [10.5061/dryad.zcrjdfnh5](https://datadryad.org/stash/ds_admin?q=%2210.5061%2Fdryad.zcrjdfnh5%22&sort=relevance&commit=Search&tenant=&editor_id=&curation_status=&publication_name=&sponsor_org=&utf8=%E2%9C%93). This dataset was initially curated on 8/23/23 by @lauradryad and returned to the author that day. The last modified date (Aug 23, 2023, 11:26 AM) records this action. In this case, the author actually returned the dataset within 48 hours (Aug 25, 2023, 10:20 AM), which is recorded in the Activity Log but not reflected on the table view, which still displays the status as 'Action Required' (should have been returned to 'Curation' in the old workflow, as indicated by the Activity Log).

It is interesting to note that the last modified timestamps of both are very close together, but a cursory examination of other datasets that have last modified timestamps in the same range and that were curated in some fashion did not identify any additional datasets with these issues.

**Comment by ryscher** [comment]
[10.5068/D1339F](https://datadryad.org/stash/ds_admin?q=%2210.5068%2FD1339F%22&sort=relevance&commit=Search&tenant=&editor_id=&curation_status=&publication_name=&sponsor_org=&utf8=%E2%9C%93). DataCite was giving us a `403 Forbidden` when trying to register the metadata. The root cause was an incorrect tenant setting. In ticket #2727, the tenant was changed from a UC tenant to a non-UC tenant, which does not work because of the legacy special handling for UC DOIs.

I returned the tenant to its original `ucla` setting and published the dataset.
