### ISSUE TITLE
Cannot delete a dataset in stage 

### ISSUE THREAD

**Issue by marisastrong** [CDL-Dryad/dryad-product-roadmap#2770]
**Bug description:**
Received an email 
 **Subject**:  "[stage] REMINDER: Dryad Submission "test ezid dataset "

**Body of Message**
Dear Marisa Strong,

Your Dryad data submission, “test ezid dataset”, is currently "In Progress". It has not yet been submitted for evaluation by a member of our curation team.

When you are prepared to submit this dataset for curation and publication, please follow these steps:

[Login to https://datadryad.org](https://datadryad.org/)
Click on "My datasets"
Locate your submission with the status "In Progress"
Click "Resume" to access your submission
Incorporate pending edits, if any
Click "Submit"
If you do not intend to proceed with the publication of this dataset, you may either select "Delete" from your dashboard if this option is available to you, or contact Dryad's Helpdesk at [dryad.helpdesk@mailinator.com](mailto:dryad.helpdesk@mailinator.com) to request that it is withdrawn.

I went to Stage  to delete the dataset and was unable to perform that action..  I also did not see a resume button.

<img width="1226" alt="Screen Shot 2023-09-01 at 12 20 20 PM" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/810543/fd560329-a5c3-456b-8b14-676fcc8da6f6">

**Steps to reproduce:**

**Expected behavior:**
Resume button should be available?

**Comment by ryscher** [comment]
I removed the offending state. It was caused by a curation trainee, who started to edit the dataset and then abandoned it. 

@jleighherzog Do you have suggestions about how to best avoid this situation? Only have curators train on datasets that were explicitly created for curation? Or should we allow users to regain control of their datasets? On stage, we have a mix of users, including prospective members who are testing the system for the first time, so we wouldn't want them to encounter this confusing behavior, especially because they wouldn't necessarily know that it is unexpected.

**Comment by jleighherzog** [comment]
@ryscher : Thanks for flagging this. Yes, trainees usually only access datasets that were specifically loaded to the test site for training/practice. And, they're instructed NOT to use live email addresses when practicing the upload of datasets (they can only use their own).
