### ISSUE TITLE
Replace Merritt ZIP files

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2787]
- [x] Test technologies for creation of ZIP files and select the one we will use
- [x] Create a process to make a ZIP file from a single S3 dataset on-demand
- [ ] Create a queue that will create ZIPs as users request them from Dryad
- [ ] Add a caching mechanism

**Comment by sfisher** [comment]
As I understand it, this initial pass with zip file creation is about figuring out how to approach this.  I keep wishing that we wouldn't have to end up standing up a new, beefy server; implementing a queuing system (since we don't have unlimited resources to create all zips for all people at once); making people wait and wait for zip creation; having gymnastics in our UI to tell people to wait and give them progress bars; polling for completion; starting downloads with Javascript, etc.  it seems to create a lot of extra complexity and resource usage and annoyance to me.

This is why I keep wishing for a client-side solution for getting a bundle of all files and make the user's computers take on the resourcing of bundling lots of files together for their own convenience instead of making limited server resources take on that task.  This might also mean that downloads could start immediately and the bundling happen on their own computers.

One problem is that I'm not sure if Javascript in the browser is really up to the task of doing all it needs to, at least not for all sizes of files.  But perhaps it's good enough and we could exclude some edge cases (such as extremely large packages).

I began examining Javascript for streaming and saving files and there are some APIs for doing some of this, though they're hard-ish to fit together for someone who is only moderately familiar with the JS world and also what is limited because of browser sandboxing.

Some things that might be helpful that I found:

- https://github.com/mafintosh/tar-stream  The tar stream library supposedly works with streams rather than just files.  So maybe it could take contents streaming from http requests (for each individual file) and mash them into one big file for a user to enjoy.  I started looking at tar rather than zip since I think it's a simpler use case than zip since tar files are less complicated than zip and don't have the same index-at-the-end things going on.  Maybe either would work.
- https://css-tricks.com/getting-started-with-the-file-system-access-api/ The file system access API in Javascript I believe allows saving a dynamically created file.  If done right, the user can be prompted with a save dialog, they can choose to save the file and it can be created dynamically.  IDK if this is compatible enough with most browsers people would be using now.
- https://github.com/CDL-Dryad/dryad-app/commit/c14fda8530868dcfa4c57dc92389a5b87c2568c5  I started playing with a file system picker and writing stuff dynamically but there were some problems producing empty files and that tar-stream didn't seem to be accepting the same kind of streams as others.
- https://web.dev/streams/ and lots of other content on the internet talks about Javascript streams. i tried some pipe things.  Linux/Unix makes pipes work easily, Javascript doesn't but there may be ways to do the `Read a chunk/Write a chunk` stream method, IDK.
  - https://developer.mozilla.org/en-US/docs/Web/API/Streams_API
  - https://medium.com/sessionstack-blog/how-javascript-works-streams-and-their-use-cases-79d127522166
  - There are tons of google results for streams.  There are also some older libraries for working with files and streaming, but I think many are saying to use some of the updated features in Javascript now instead of using them as of 2023.
- I also found that lots of the articles about streaming were very node.js and server-side oriented, but possibly some of it may work in a browser with some modifications.
- My thought was to just make individual requests to get presigned URLs for download and then just streaming each file into one container for the user to enjoy.
- While compressing data might be nice, I think mostly what people want is everything in one container that downloads with one request from them.  If files are already zipped by an author then they will likely not compress more, anyway, for large files.

I don't know if any of this helps in coming up with a really neat solution that avoids us having to do so much work and maintenance in the long term and pushes some of the work onto user's browsers rather than our servers.

**Comment by ahamelers** [comment]
As discussed, we should be able to do the client-side JSZip packaging for datasets under 10GB.

Here's a table of the sizes of submitted datasets in Dryad:

Size in GB | Count | Percentage
-- | -- | --
< 1 | 199470 | 95.98
1 - 10 | 2894 | 1.39
11 - 20 | 1189 | 0.57
21 - 30 | 881 | 0.42
31 - 40 | 614 | 0.30
41 - 50 | 344 | 0.17
51 - 100 | 1131 | 0.54
101 - 150 | 443 | 0.21
151 - 200 | 404 | 0.19
201 - 300 | 400 | 0.19
301 - 440 | 48 | 0.02

Unless I've done my queries or math totally wrong, it looks like more than 97% are less than 10 GB (with ~96% less than even 1 GB)

**Comment by ahamelers** [comment]
I've enabled javascript zip assembly for downloads from the web (from the landing page and the share link) for datasets smaller than 11GB.

We could also use this javascript method to allow users to select their own subset of files from a dataset to download as a package—it would be a negligible change to allow this.

If the dataset is 11GB or greater, or the browser is too old for the javascript method used ([service workers](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker)), the user must download the individual files. For very large datasets, each file is often a huge zip in itself anyway, so downloading the individual files makes sense.

Depending on the user's browser and OS and general computing capabilities, larger zip files might be possible with this method—I'm trying to test 50GB right now—but I think it's fine to set the limit at 10GB. In a few years we can switch to using [background fetch](https://developer.mozilla.org/en-US/docs/Web/API/Background_Fetch_API) and the [filesystem API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API), which are designed exactly for the purpose of downloading large files with javascript, but do not yet have wide browser coverage.

We are still discussing whether there is a need for a replacement for downloading the whole dataset package via the API, or whether it might be better to provide some documentation with on how users can programmatically create their own packages by iterating through our individual file download API.
