### ISSUE TITLE
AAAS API testing

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2804]
A potential bug from AAAS: 

```

What happens is that if we call the Dryad API from the REST 
client (Postman), it reports the execution was successful but
 the status remains the same and it does not get updated (we
provide update of curation status to ’submitted’, as per API 
documentation). On the other hand, once the same API gets 
called from the publishing platform service code, it returns 
error with no response body, just HTTP status 406. 

Please see the example of the request we tested for troubleshooting purposes.

PATCH https://datadryad.org/api/v2/datasets/doi%3A10.5061%2Fdryad.fn2z34v0m
BODY:
{
 "op":"replace",
 "path": "/curationStatus",
 "value": "submitted"
}

This one comes back as successful, but the curation status does not change and it’s still ‘In progress’.
```

**Comment by ahamelers** [comment]
This failing for them would explain all the trouble we've been having in #2701

**Comment by ryscher** [comment]
For the particular dataset mentioned above, the API call is failing, because there is no actual content in the dataset (neither metadata nor files). It appears that the dataset was created with at least metadata on 2023-04-05, since there are search terms available in the Identifier object (107356). However, the single Resource (228474) has all null values, and a later update date of 2023-08-01. Possibly the result of an API PUT call? The activity log shows that the user never came to Dryad to provide any files or other updates.

**Comment by ahamelers** [comment]
Had a call with AAAS and went over the process and the API calls needed. AAAS has already fixed their header issue. They had identified their current problem being that when they send the 'submitted' API call (when an article is accepted and they want to move the associated dataset out of PPR), they have been receiving errors because the dataset is often already 'submitted'. I checked their settings in our database and their journals are all default_to_ppr, but explained that the system does not prevent users from changing the PPR setting when they review the submission or after, and that is likely what is happening. AAAS will add a step to their process where they check the status of the dataset before sending the 'submitted' API call and only send it if necessary.
