### ISSUE TITLE
Download of large files

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#281]
Large files (>4GB) don't seem to be downloadable from Dryad.

For example, in the item below, only the README.txt and SCRIPTS.tar.gz can be downloaded from the landing page:
 https://dryad-dev.cdlib.org/stash/dataset/doi:10.5061/dryad.668g444?latest=true

The large files *can* be downloaded directly from Merritt:
https://merritt-stage.cdlib.org/m/ark%253A%252F99999%252Ffk48k8jp86/1

**Comment by sfisher** [comment]
It look as though this is being caused by the head request we are doing to set appropriate headers for the download we are streaming.  The connection is timing out while we are waiting for the head request which takes over a minute (change pwd below).

```curl --user dash_demo_user:mypass --head http://mrtexpress-stage.cdlib.org/dv/1/ark:/99999/fk48k8jp86/Asha_G.tar.gz```

I'll check with Merritt if there is a way to speed head requests.  Maybe we can use another method or not do head requests.
