### ISSUE TITLE
Investigate possibility of restricting automatically generated escapes (\) for filenames in README file

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#2813]
The Markdown editor adds escapes around underscores to prevent inadvertent italics, but these aren't the best aesthetic when opened in a plain text editor, especially around filenames, and some authors have asked about this. It would be good to investigate whether it is possible to restrict this auto-formatting for text strings that are recognized as filenames since we recommend the use of underscores to separate words in filenames in our help pages.

**Comment by ahamelers** [comment]
The README editor uses the CommonMark markdown standard which does encourage backslash escaping markdown control characters: https://spec.commonmark.org/0.30/#backslash-escapes

Whether emphasis control characters operate and need escaping within words ( as in a snake_case_filename) is highly dependent on which markdown standard is used and what rendering settings are applied to it.

**Comment by ahamelers** [comment]
@bryanmgee as the text editor is currently built, this is not something I can modify even with a plugin (I've opened a ticket with the creators of the editor, but it looks like no one has looked at issues there since February).

I could edit the markdown text at the point where it is saved as the .md file, and remove the blackslashes in front of underscores where not preceded or succeeded by whitespace. So when the plain text is downloaded the escaping would not appear. However, the escaping would still appear in the editor when viewed in the markdown tab. Is this an okay compromise, or would it be confusing?

**Comment by bryanmgee** [comment]
I believe that workaround would be acceptable; I think the core issue is that because most authors do not know what Markdown is, they also do not have Markdown programs, so they all open their files in a text editor and see it; I don't think many are using the Markdown tab in the editor or care about all the syntax in that specific tab.
