### ISSUE TITLE
Test CEDAR editor updates

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2830]
CEDAR has improved the accessibility of the metadata editor and [released a new version on npm](https://www.npmjs.com/package/cedar-embeddable-editor). We need to test these updates for the FAIR Workflows project.

- [x] Build the Webcomponent JS file as described on the npm page
- [x] Determine whether this JS file can be used as a replacement for our existing JS snapshot file
- [x] Re-evaluate the accessibility of the resultant editor
- [x] Report back to FAIR Workflows about the accessibility, and whether we can roll the editor out for production use (see #2144, #2079)

**Comment by ahamelers** [comment]
Update of issues from #2144 and #2079

*Fixed issues:*
- margin reset
- headings are now HTML heading elements
- keyboard focus seems fine
- tooltips are available for screen readers
- icon buttons have aria labels

*Issues fixed with our own CSS modifications:*
- contrast/size of error messages (and other text)
- made the modal close button sticky (helpful for mouse users, but probably not adequate for screen reader users)

*Remaining issues:*
- There still doesn't appear to be an "after-save" hook we can use to close the modal
- JSON copy button is hidden from screen reader users
