### ISSUE TITLE
Analyze fee waiver usage

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2835]
From the Cost Management meeting: Are we providing excess fee waivers? How many are we actually providing?

Compare fee waivers in the shopping carts with the [export of salesforce requests](https://docs.google.com/spreadsheets/d/1Jc9ASGBZPtgoIYtibKNp8YUN-cKzhvNSXcFu2sbxCwo/edit?usp=sharing). Are the shopping cart reports missing items?

**Comment by bryanmgee** [comment]
What I did is join two dataframes, one with all of the SF cases that were either fee waiver requests or void requests, and one with all of the shopping cart reports; these were both restricted to December 1, 2022–September 30, 2023, inclusive. I then filtered the SF cases to only ones that are listed as being approved requests. This returned 1 fee waiver that was approved but the dataset is displayed as 'stripe' for PaymentType (I think this was my bad, I may have verbally agreed to the waiver and then forgotten to change the status in the Admin Site, we'll see if the author follows up b/c the dataset was published only about 3 weeks ago, so they haven't passed the deadline for invoices). 

Probably more important are the 13 void requests that were approved but the datasets are displayed as 'stripe' for PaymentType (those are in the CSV file below) without any indication of a voided invoice. I can't identify any patterns or attributes about these that would explain why they aren't correctly labeled because I did see one in the larger dataset that is labeled as having an invoice voided.

[Mislabeled void requests.csv](https://github.com/CDL-Dryad/dryad-product-roadmap/files/12836225/Mislabeled.void.requests.csv)
