### ISSUE TITLE
Author initiated several Zenodo DOIs on dryad doi 10.5061/dryad.4xgxd25dp

### ISSUE THREAD

**Issue by lauradryad** [CDL-Dryad/dryad-product-roadmap#2933]
**Bug description:**

In dataset [10.5061/dryad.4xgxd25dp](https://datadryad.org/stash/dataset/doi:10.5061/dryad.4xgxd25dp), the author initially said that their software zenodo link didn't work after the dataset was published, so they went back to in to create a new version of the Dryad submission to sort out the Zenodo links; however, when they went back in, they moved files around several times, and now there are two Zenodo DOIs for each Software and Supplemental Info. I am unable to see what is in any of the Zenodo links with my permission, so I'm not sure where all the correct files are and which DOIs should be retained as Related Works. 

These are the files that should be in Zenodo as software and supp:
![image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/124197995/9a919e9f-ca4d-4fa1-a6f7-9533f2743405)

Here is the email I received from the author trying to explain what they did:
"In our previous submission, the software was uploaded on Zenodo through the Dryad platform, and a DOI (https://doi.org/10.5281/zenodo.10048860) was assigned to it. Similarly, the Supplemental information was also uploaded and another DOI (https://doi.org/10.5281/zenodo.10048867) was assigned.

Since the Dryad data was first published on November 1, the latter DOI hosting Supplemental information has been working. However, it seems that the former DOI hosting software has not been working. To fix this issue, we created a new version of Dryad where both software and Supplemental information were put together on the software category in your Upload Data page with the active DOI (https://doi.org/10.5281/zenodo.10048867). Then, we received this message from you asking to separate software and Supplemental information into their respective category in the Dryad platform. We have done so, assigning the same and active DOI (https://doi.org/10.5281/zenodo.10048867) for both software and Supplemental information. Eventually, in "Related works" box of our Dryad top page, two new DOIs are shown separately for software (https://doi.org/10.5281/zenodo.10070281) and Supplemental information (https://doi.org/10.5281/zenodo.10065328), both of which are inactive for now, together with the still active DOI (https://doi.org/10.5281/zenodo.10048867) which only provides Supplemental information.

We are quite confused with this issue, and kindly please help us. Please note that we licensed "MIT" and "Creative Commons Attribution 4.0 International" for our software and Supplemental information, respectively. We are open to changing the license if this matters. Thank you in advance."

and then shortly thereafter:

"Seems like our Dryad public view now shows two active DOIs for Software (https://doi.org/10.5281/zenodo.10049118) and Supplemental information (https://doi.org/10.5281/zenodo.10048867). However, our Dryad private view still shows three DOIs as mentioned in my previous email. "

**Steps to reproduce:**

The original Zenodo links that are in the currently published version of the dataset do appear to work (sw https://doi.org/10.5281/zenodo.10049118, supp https://doi.org/10.5281/zenodo.10048867), so I'm not sure why the author thought they didn't and rearranged them all, but now I don't know where the files are or how to link them properly to this submission. 

**Expected behavior:**

I'd like to figure out what is actually being hosted at each Zenodo DOI and how to unlink some of them so only one Supp and one Software DOI remain.

**Comment by lauradryad** [comment]
Is there any update on this one? The author is a little antsy about their paper coming out soon. Thanks!

**Comment by sfisher** [comment]
Hi @lauradryad ,

This user put in two related works from the currently published version of the dataset as a related work in the new version that is getting ready to be published.  This is not something the system did automatically, but is something the user or a curator did.

![Screenshot 2023-11-13 at 1 11 02 PM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/105433/877b7afe-608b-4d2f-a2cc-4a89104ef511)

See where it shows "added by: 0" on two of them?  That means they entered them in the form themselves and it was not added by the system for Zenodo automatically (items added for Zenodo automatically have a 1 there).

Related works not put in by the system will not be automatically managed by the system.  The assumption is that if someone types something into the system metadata entry form, they know what they're doing and intended to add that related work and we shouldn't randomly remove it or modify it.

This isn't a bug but is functioning as intended.

However, I've removed the two crazy links (two duplicates of the same link under both software and supplemental relations) that someone typed in manually.

To be clear, Zenodo DOIs will not work until publication and every version of a Zenodo dataset with changed files gets a new DOI.  That is why the other two links didn't work, since it wasn't published yet.

I've added some chages to the Ui to make that situation clearer and they are no longer linked (just text) if a version isn't published yet.
