### ISSUE TITLE
Versioning issue with file retrieval

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#2943]
In dataset doi:10.5061/dryad.1vhhmgqwm, the latest submitted version (November 2, resource 263045, version 9) contains a PDF file that cannot be downloaded through the UI. 

On investigation, I see that a "version 10" of the dataset was created and deleted twice. When I look at the files in S3, I see that the PDF is present in a directory marked as version 10 (m5ck5p9v|10|producer), even though there should not be a version 10. 

Is this related to #2940?

**Comment by sfisher** [comment]
There are no differences in the versions in the versions table, so I don't think it's related to 2940.  In most cases where something was patched up in Merritt we have mismatched merritt and dryad versions in the version table.

The fact that the version doesn't exist in Dryad seems weird since IDK how version 10 got submitted to Merritt unless there has been a long-standing problem where there were two submissions to Merritt that didn't get flagged correctly.  I'll look through history in Merritt to see if there were multiple submissions somewhere that were not flagged correctly.

**Comment by sfisher** [comment]
Ok.  This is fixed.  From examining the Merritt data, they had two versions deposited exactly the same time for V1 & V2 (same exact minute).  I think the user did this by machine-gunning the submit button or else going back and getting another submission in somehow. (The button for submitting disables after one click now.)

I fixed by shifting all merritt versions and leaving out version 2 (1, 3, 4, 5, 6, 7, 8, 9, 10).
