### ISSUE TITLE
Reviewer URL link directing to 404 error

### ISSUE THREAD

**Issue by jleighherzog** [CDL-Dryad/dryad-product-roadmap#2981]
**Priority**: High
**Impact**: URL may be broken for some datasets, needed for peer review

Received two notifications today that the Reviewer URLs for these datasets are directing to the error page (see below). 

DOI: 10.5061/dryad.0zpc8673t

DOI: 10.5061/dryad.bzkh189cw

They receive a 404 error. This is what I see: 

![Screenshot 2023-11-29 at 10 58 39 AM](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/76497320/82a5ac4a-4584-47ed-83ee-adceab675e82)

**Comment by ahamelers** [comment]
@jleighherzog probably best not to include active reviewer URLs in public github even if you're experiencing an issue with them 😄 

I was eventually able to recreate this error. It seems to be a speed issue—these datasets are small enough that the automatic download attempt happens before the downloading tool has actually loaded successfully.

I will put in a fix. In the meantime, weirdly, it should work if they visit the URL a second time in a row (please test this yourself)

**Comment by jleighherzog** [comment]
Refreshed my page and the auto-download was initiated — confirmed!

**Comment by bryanmgee** [comment]
@ahamelers unsure if this is the same issue, but we had an author email in to say that the PPR link worked for them but not for three other people who were using different OS and browsers: https://datadryad.org/stash/dataset/doi:10.5061/dryad.6q573n64s 

I did not have issues with the link in either Firefox (incognito) or Chrome (regular and incognito).

**Comment by ahamelers** [comment]
A confusing thing about this particular issue is that if you have already visited dataset landing pages in your browser, you will have no problems, as the downloading tool will have already successfully registered in your browser. It's only people who don't visit Dryad regularly, or who are trying lots of new browsers, or who have cleared their cache, that will see this issue—basically the opposite of every other problem on the internet! (@jleighherzog instead of having users load the same page twice, you could have them visit any random dataset landing page with a download link, and then try the reviwer link again, for the same beneficial effect)

It should be completely resolved after the release Tuesday 🤞
