### ISSUE TITLE
Investigate disabled Zenodo links in published datasets

### ISSUE THREAD

**Issue by bryanmgee** [CDL-Dryad/dryad-product-roadmap#3014]
We had a repeat author email HD saying that for many of their published datasets, the Zenodo links are not functional and display the "(to be published with dataset)" line, even though the listed link does go to a published, linked Zenodo landing page when you enter it into the search bar manually. These are not datasets where the author has versioned it but we didn't/have yet to approve the newest version, so the Zenodo stuff is already available and is not being versioned. 

> The following datasets have this problem (dataset owner is Cassandra Tucker, cc'd):
> https://doi.org/10.25338/B8Z052
> https://doi.org/10.25338/B8PD3Z
> https://doi.org/10.25338/B8V054
> https://doi.org/10.25338/B8WK9T
> https://doi.org/10.25338/B8GK93
> https://doi.org/10.25338/B8J641
> https://doi.org/10.25338/B8BS8J
> 
> This dataset does not have this problem, and correctly shows the clickable links for software/supplemental information:[ https://doi.org/10.25338/B81D19](https://doi.org/10.25338/B81D19).

As far as I was able to tell from a quick glance, all of the problem ones were published and then versioned to make minor metadata changes like adding the primary article DOI, but no changes were made to files. Since the changes were minor, when the dataset was republished, it was thus republished under the original publication date to avoid resetting the citation (this is the current curation workflow). Multiple curators have been involved in handling at least one from this set of dataset, so it doesn't appear related to a single curator doing something unusual either. My best guess is that it's related to how when only metadata are versioned, the updated version hasn't historically been pushed to Zenodo (e.g., if they update the Abstract), but this is only a guess.

**Comment by sfisher** [comment]
@ryscher This is based on a state where an item is fully published (both view and files flags are set, which is normal) and then later repeatedly "published" with only a view flag set for a later version.

This makes it seem as though that version does not have files showing.  I thought publishing again always marked both file and view flags.  IDK if this is hacked in or if the state is normal.

I can probably look into a way to avoid the problem with logic if it never has been published.

This got put in in the first place because some different authors were having problems when their files didn't work at Zenodo pre-publication from the links (which was expected).  I can see if there is an easy fix in the morning.
