### ISSUE TITLE
TinyMCE registration

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3028]
On v3 servers, TinyMCE is asking for our domain to be registered. Have we registered in the past?

![Image](https://github.com/CDL-Dryad/dryad-product-roadmap/assets/605143/a13e887f-3aa0-4039-878a-d2eea9b24653)

**Comment by ahamelers** [comment]
I believe this is related to the API key we have for TinyMCE that we discussed recently. I have no information about how this API Key was registered and who registered it, or has administrative access. There is no information in the Dryad 1password or in my email records about any TinyMCE account. Could others please search their records? @sfisher @marisastrong

**Comment by sfisher** [comment]
I registered at TinyMCE account under my email since it asked for someone's email. It was free to register and you are only asked to pay for upgraded functionality such as converting Word docs and some other stuff.

Someone at Dryad may want to register and get their own API key and put it into the configuration.  You'll also get occasional annoying emails about how wonderful TinyMCE is and how you can buy upgrades or you may also get emailed security alerts, I think.

There was also a page I found on the internet that tells how to make this notification hidden by changing some CSS or Javascript or something.  I don't believe being unregistered changes functionality that we use.

**Comment by ahamelers** [comment]
@ryscher I've created an account with the devs@datadryad.org email address, login information saved in the Dryad 1password. Making a pull request to use the new key in the project. In future the account can be modified by anyone with the login to add more domains or pay for features/views.
