### ISSUE TITLE
Menus on v3 servers

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3030]
On the v3 servers, the JS menus do not work correctly on the homepage, but they work on the other pages.

**Comment by ahamelers** [comment]
This seems to be related to the loading of the content on the bottom of the screen.

<img width="1237" alt="Screenshot 2024-01-03 at 12 18 54" src="https://github.com/CDL-Dryad/dryad-product-roadmap/assets/1749394/b4c4ca88-9fa6-4f09-a5c3-6a0b2f0abaf2">

When the 'latest news' section finishes loading, the menus work as normal. This is probably due to the order in which the various javascripts are loaded, which needs to be modified. Also, the loading of the content from the wordpress RSS seems to take a particularly long time on this page on this server (the same content loads quite quickly on the "What we do" page)

**Comment by ahamelers** [comment]
This happens on the "My datasets" page as well, even on the existing servers, if the user's dataset list takes a long time to load
