### ISSUE TITLE
Disable error notifications (emails and display on My Datasets) when error is due to Merritt ingest

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#310]
1) No longer send error email to user
2) Change up error display on "My Datasets" to display under Submitted with "Update" disabled 
3) Change status to say "Processing" so that it is distinct from "In Progress" and we know that it is an error on our end

**Comment by briri** [comment]
Removed the error submission email to the dataset owner (system still sends out an error report to the devs).

Updated the dashboard page so that datasets with a submission error appear in the 'Submitted' section. See the 'Box, Google and Dropbox' line in the screenshot below

<img width="1266" alt="Screen Shot 2019-06-03 at 11 22 17 AM" src="https://user-images.githubusercontent.com/1204467/58824884-09880600-85f2-11e9-8bcd-b11bed16ccca.png">
