### ISSUE TITLE
Handle files uploaded via URL in new storage

### ISSUE THREAD

**Issue by ahamelers** [CDL-Dryad/dryad-product-roadmap#3126]
From https://github.com/CDL-Dryad/dryad-app/pull/1498

Files that are "uploaded" via URL need to be loaded to the new storage

**Comment by ryscher** [comment]
Currently, for files that have been uploaded to the temporary storage, `SubmissionJob.do_submit!` handles the process of moving them to the permanent storage. I assume we can handle the URL-based files in the same location, since each `SubmissionJob` is already in its own thread. We know that a file is URL-based instead of a direct upload in two ways:
1. There is no corresponding file in the temporary storage
2. The file object (f) contains a `url`.

**Comment by ahamelers** [comment]
I've got code for this, but it will have crazy merge conflicts with https://github.com/CDL-Dryad/dryad-app/pull/1504 and https://github.com/CDL-Dryad/dryad-app/pull/1509, so I'll wait to make a PR until those are tested and approved.

**Comment by ryscher** [comment]
Here are some sample files I tested with, which may be useful in future testing....

Simple images:
- https://web.ics.purdue.edu/~gchopra/class/public/pages/webdesign/example/prettypicture.jpg
- https://www.columbia.edu/~fdc/picture-of-something.jpg
Dataset:
- https://www.stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2021-financial-year-provisional/Download-data/annual-enterprise-survey-2021-financial-year-provisional-csv.csv
Dryad file (with no file extension), currently fails due to #2932:
- https://datadryad.org/stash/downloads/file_stream/430659
Larger (100MB) dataset:
- https://www3.stats.govt.nz/2018census/Age-sex-by-ethnic-group-grouped-total-responses-census-usually-resident-population-counts-2006-2013-2018-Censuses-RC-TA-SA2-DHB.zip?_ga=2.267839754.560685599.1707755819-773418509.1707755819
Large Friendster archive (9GB):
- https://snap.stanford.edu/data/bigdata/communities/com-friendster.ungraph.txt.gz
Image with no file extension in URL:
- https://earimediaprodweb.azurewebsites.net/Api/v1/Multimedia/a6cb4376-7c24-4a31-aac8-045532e777c4/Rendition/low-res/Content/Public
