### ISSUE TITLE
Frictionless not running on v3

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3146]
On the v3 servers, Frictionless is not completing. Likely a permissions issue.

**Comment by ahamelers** [comment]
Truly the frictionless lambda is never being triggered, it appears the Axios POST request to the frictionless triggering URL is failing.

**Comment by ahamelers** [comment]
It looks like it's an OpenSSL permissions issue 

```
OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (Hostname mismatch)):
  
app/models/stash_engine/api_token.rb:54:in `block in new_token'
app/models/stash_engine/api_token.rb:48:in `new_token'
app/models/stash_engine/api_token.rb:31:in `token'
app/models/stash_engine/generic_file.rb:221:in `trigger_frictionless'
app/controllers/stash_engine/generic_files_controller.rb:106:in `block in trigger_frictionless'
app/controllers/stash_engine/generic_files_controller.rb:105:in `map'
app/controllers/stash_engine/generic_files_controller.rb:105:in `trigger_frictionless'
```

**Comment by sfisher** [comment]
As I recall, the code that triggers the lambda tries to get a current API token to pass into the lambda.  The lambda uses the token on completion to update the frictionless information through our API.

This error seems to be triggered when we are trying to get an API token from Dryad's own API.  It uses the external http interface to get the OAuth token by http requests as any other external client would (rather than digging into Gatekeeper internals to produce a token).

Check that the OAuth flow works for the key/secret to get a token from the Dryad API.  This may be because the Dryad API doesn't verify with SSL for some reason.  There are probably also ways to make SSL less strict for an http request that you know is to a known good server. We had to do this with Merritt in the past when they were self-signing certificates or their cert wasn't part of the normal trusted certs.  I think you can maybe also load additional certificates for openssl or an http client to trust manually.

**Comment by ryscher** [comment]
https://github.com/CDL-Dryad/dryad-app/pull/1513 seems to have fixed the problem. Frictionless is again working on v3-stage.
