### ISSUE TITLE
README undo

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3170]
In the README editor, the Undo button (or keyboard shortcut) removes the previous action, as expected. However, if you have just started to edit the README and there haven't been many changes since the last version, Undo will reverse the original insertion of text into the pane, and you will be left with a blank editor, which is very confusing.

**Comment by ryscher** [comment]
This is related to the last bullet in #2972, but may be a different issue.

**Comment by ahamelers** [comment]
This is related to https://github.com/CDL-Dryad/dryad-app/pull/1428 and https://github.com/CDL-Dryad/dryad-app/pull/1519

Initially we loaded the editor with a `defaultValue`. That meant this issue did not happen, and it made checking and saving changes a bit less complicated. But then we identified the need to check all content before allowing it to load in the editor, because some content would break the editor otherwise.

In order to go back to loading a `defaultValue` to the editor, I'd need to find some way to check the content without first loading the editor's markdown parser and serializer (which is what we currently use for the checks)

**Comment by ahamelers** [comment]
I spent a bunch of time looking at and working with other markdown parsers, could not force one to meet the requirements of the site, and then figured out I can (very easily) attack the issue from the other side by flushing the history, so the initial value loaded becomes the first state of the history, rather than the blank page.
