### ISSUE TITLE
Large file copy and disk space

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#3212]
We occasionally receive "out of disk space" errors when large files are downloaded from an external URL.

This error stems from the section in `submission_job.rb` that attempts to copy a URL to the permanent store. To reproduce the problem in a Rails console:
```
u = "<URL of some large file>"
permanent_bucket = APP_CONFIG[:s3][:merritt_bucket]
s3_perm = Stash::Aws::S3.new(s3_bucket_name: permanent_bucket)
permanent_key="test/large_file_test.tar.gz"
URI.parse(u).open do |f|
  s3_perm.put_stream(s3_key: permanent_key, stream: f) 
end
```
Then watch in another shell while the disk space gets lower until it either runs out of space or the entire file is transferred.

**Comment by ryscher** [comment]
This problem is currently affecting 10.5061/dryad.q2bvq83sk

**Comment by ryscher** [comment]
I've done a lot of testing with various options on the `URI.parse(u).open`, and it always seems to download the entire file (until disk space runs out), even though documentation would suggest otherwise. Is there some kind of system option I'm missing? Or do we need to shift to a more explicit use of AWS multipart upload?

**Comment by ahamelers** [comment]
@ryscher I am currently finding the same, and it's frustrating because this is somewhat contraindicated by the documentation.

It looks like this is a variation based on the size of the download—with ruby's `open` the result is meant to be "rewindable", so for smaller sized files the response is StringIO, but for large files it creates a Tempfile for caching, whether we want it to or not.

I've found a gem ( https://github.com/janko/down / https://rubygems.org/gems/down/ ) which would allow us to disable caching and work with streams exclusively: https://github.com/janko/down/tree/master?tab=readme-ov-file#caching

I'll install this and see if it fixes our problems.

**Comment by ahamelers** [comment]
It looks like this gem is already in the project—with a note that we "don't know where it's used"! 😆 I'll use it and check the results

**Comment by sfisher** [comment]
It's obnoxious how it writes things to disk.  I know I'd looked at `down` in the past and it may fix some issues.  I think it gives you three backends for downloading stuff (maybe standard http, http.rb gem or wget?).

I know in the zenodo streaming code I got streaming working rather manually by doing some trickery with threading and threading (one input thread and one output thread) and a pattern like "read a chunk from input thread and source" and "write that chunk to output thread and destination".  I think it also has some stuff for calculating digests (which you can update chunk by chunk without reading the whole file to disk or memory).

But I think there were also a bunch of limitations with the rewinding stuff.  Some http request types worked and some did not ?  Also if an error occurred it would have to start the whole process over since there wasn't a way to rewind and just submit the errored chunks.

There are also ways to do http range requests to only load in byte ranges, though I think there were some versions of http or servers that support it and some don't.

Anyway, it gets tricky to try to do everything by stream without writing to disk.  I hope the down library work for what you need. I ended up settling on the `http.rb` gem a lot of places since it was flexible and allowed working with streams somewhat easily.

The page at https://janko.io/httprb-is-great/ has lots of examples for using that gem for more advanced stuff which may be harder or impossible to do with other gems like httparty or restclient or other stuff.

**Comment by ahamelers** [comment]
Thanks @sfisher ! I was able to get things working to my satisfaction with `down`. Amusingly, the author of that gem is also the author of the http.rb post you linked!

I know in the code for this project we're doing a lot of similar things in slightly different ways; a general clean up and refactoring is probably called for someday.
