### ISSUE TITLE
Correct overly-conservative embargoes

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#400]
Due to inconsistencies in the original Dryad metadata, some migrated items have embargoes that they should not have.

When the embargo date has been removed, but there is still an embargo type, the migration code assumes that an embargo should be in place. This is rarely (never?) the case. 

Review how current Dryad makes the decision to embargo something (is it always based on the presence of a date?), and update the migrated items to remove any erroneous embargoes.

**Comment by ryscher** [comment]
Might be able to leverage the publication updater code:
stash_datacite/lib/tasks/publication_updater.rake

**Comment by sfisher** [comment]
The things I see in the states that I find weird are in almost all datasets when you look how the curation states have changed, for example, this one:

http://dryadx2-prd.cdlib.org/stash/ds_admin/activity_log/572?utf8=%E2%9C%93

I don't really understand why stuff is going into multiple "published" states in a row and then back into "embargo" states.

If something is added to the record just to make a comment it should usually be the same state as the last state instead of changing to "published" just to make a comment.

Also there are lots of "publiction date has not yet been reached" which I know about because there were problems with the updaters and I asked Brian to fix.

In the end, the only state that matters is really the terminal state, since it influences if things are shown to users, etc and also what actions are possible.

If we're confident that terminal states are all correct we can either ignore all the obvious trashy states or go back in and clean them up later so it doesn't look so bad.

The main thing I worry about is that it seems like there was a lot of chaos around states and it doesn't fill me with a lot of confidence that all of the terminal states are correct as they should be.

If they're not correct it may mean some people are seeing things that should be private.  Or on the other hand, some things may be private that really should be open to the public.

**Comment by ryscher** [comment]
The original set of issues has been corrected. However, it appears that a new set of issues was introduced by the "Embargo Datasets CRON". I believe that everything this script set to embargo is incorrect and should be reversed. I am reviewing the list of items and the script itself before I revert them all.

**Comment by ryscher** [comment]
Fixed in https://github.com/CDL-Dryad/stash/pull/277 and https://github.com/CDL-Dryad/stash/pull/279
