### ISSUE TITLE
Error: out of space, I think from publication updater

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#412]
I got this email from our error notifier.  Do we need to add more space?  Or do something to make the query more efficient?  That is a crazy list in the IN clause.  It is attached because the query was too big for github to keep output for.

[out_of_space_error.txt](https://github.com/CDL-Dryad/dryad-product-roadmap/files/3469300/out_of_space_error.txt)

**Comment by briri** [comment]
👎 that's not good. might need to reevaluate the query on that one.

It looks very similar to the `build_table` one that drives the Admin curation page. The code is located here: https://github.com/CDL-Dryad/stash/blob/master/stash_datacite/lib/tasks/publication_updater.rake#L10

might also be worth dropping that query into SequelPro (or similar tool) and analyze its performance. Maybe adding a few indexes would help.

**Comment by briri** [comment]
the line its referring to at the very bottom of that error report is for the new Kaminari pagination line :/

https://github.com/CDL-Dryad/stash/blob/41e9d1abaf2382750de10077ea89b6ec551038d3/stash_engine/app/controllers/stash_engine/admin_datasets_controller.rb#L28

**Comment by briri** [comment]
Once this has been properly addressed we can revert https://github.com/CDL-Dryad/stash/pull/223 which applied a bandaid to restrict the default query

**Comment by briri** [comment]
the updater query is using the same scopes that our curation page uses, so I think whatever optimizations we make for #415 will also resolve this one.

**Comment by briri** [comment]
This may be due to the fact that when I ran the pub updater on stage it started processing every single dataset due to the fact that they all have the same updated_at date and that date falls within the past 6 months. 

We are not likely to ever have that many records to deal with. Once we determine a way to restrict this (e.g. adding a `AND stash_engine_resources.id > 12000` or something like that) we can rerun the pub updater and see how it performs.
