### ISSUE TITLE
Finishing touches for migrate button

### ISSUE THREAD

**Issue by daisieh** [CDL-Dryad/dryad-product-roadmap#49]
- [x] Formatting of the UI
- [x] Error messages for wrong code
- [x] Add "No" button for no migration
- [x] If "No" or migration successful, make message disappear from dashboard.
- [x] Add option to send code to new email

**Comment by dlowenberg** [comment]
Just looked through it - it's coming along great! A couple of suggestions:
- Could move the "no" button closer to the "yes migrate" button so they are more side by side
- Text at the top of the page for the migration could be tweaked to "...An email containing a six-digit code will be sent shortly. If you have any questions please get in touch at help@datadryad.org." (Just to give some help in case of error)
- Is it possible to make the "send code" or "migrate data" blue buttons a little bit smaller so they don't go the full width of the question? more like little boxes?

Otherwise it looks great and the functionality totally works for me when I test! If you have questions about any of the formatting stuff I'm sure @sfisher could help. Awesome work!

**Comment by dlowenberg** [comment]
@sfisher looping you in to finish out this ticket - comments above!
