### ISSUE TITLE
Activity log not always accurately recording the activity or who made the change

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#536]
There are cases where curators make a change in on the dataset or a status change and the activity log does not properly record, or, it shows that the author did that when it was the curator. Ex: 10.5061/dryad.9kd51c5c7, 10.5061/dryad.kkwh70s12, 10.5061/dryad.4mw6m906b.

**Comment by ecclary** [comment]
The issue seems to occur when curators edit an item with the status 'Submitted'. 
After changes are submitted, while the item is 'InProgress', the activity log does display the name of the curator who took the action.  But, when the change has been saved in the database, and we are able to access the item again, the activity log indicates that the action was taken by the submitting author. 

If an item has status 'Curation', the system logs the correct name in the 'Action taken by' field both while the item is in 'In Progress' and after the change has been saved in the database.
![01-curator-edit-status-submitted](https://user-images.githubusercontent.com/18015884/65916275-100d6b00-e3a3-11e9-9cd5-59e2d385361b.png)
![02-edit-saved-log-incorrect](https://user-images.githubusercontent.com/18015884/65916276-100d6b00-e3a3-11e9-92d6-071dc7177656.png)
![03-curator-edit-status-curation](https://user-images.githubusercontent.com/18015884/65916277-100d6b00-e3a3-11e9-8de4-e8e3ee28b89f.png)
![04-edit-saved-log-correct](https://user-images.githubusercontent.com/18015884/65916278-100d6b00-e3a3-11e9-91a2-cab575a4e4b4.png)

**Comment by ryscher** [comment]
Fixed by adding more transition steps and clarifying steps created by the Dryad System.
