### ISSUE TITLE
Clean-up MDC: Sending of latest reports to DataCite (DataCite Dependency)

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#541]
Martin re-submitted for us through 2018 after fixing and asks that we adjust for future reports: "The problem was that you submitted reports that didn't validate against the JSON Schema. For the simple reason that all keys in the JSON should use a hyphen instead of an underscore. So for example report-datasets instead of report_datasets."

- [x] send reports for 2019
  - [x] Combined reports through August
  - [x] Combine half of sept old Dryad with Dash
  - [x] End of September from the new system
  - [x] October reports from new system
- [ ] pull back from EventData for all datasets
- [x] Correct submission problems that have kept our current reports from being accepted (call with Kristian tomorrow)

- [ ] Report sending weekly
  - [ ] Revise sending to DataCite to weekly run
  - [ ] Change to sending two reports (end of last month, first of this month) if needed
  - [ ] Write new python code to compress and send reports as compressed

PS.  Kristian gave this link for validating a report.  https://gist.github.com/kjgarza/5a6f8537a05cce54859f7f05d53b5740 .  This may be helpful to be sure it's OK, though he said that what we sent validated but still didn't show up in stats and they will get to investigating when they can get back to it.

PPS.  A bunch don't have accurate IP addresses from certain time ranges when logging was haywire in old dryad.  This is from historical data form old Dryad and so we just don't have that data.  No IP Addresses mean we can't classify these by country and also may eliminate some items as duplicates of IP address `::1` or something like that.  Country code guessing by IP may not work for every IP, either.  Some items for some reports don't have counts by country-code (or empty hashes) because of this.  Kristian didn't really seem that concerned.  Not sure if country-codes will be part of this problem or not.

**Comment by sfisher** [comment]
It looks like the only one using an underscore (at least in the ones I checked is "report_datasets".

```
$ egrep '"[a-z]+_.+":' 2018-11_pretty.json
  "report_datasets": [
```

**Comment by sfisher** [comment]
I submitted all the datasets through august on Friday.  working on pulling back.

**Comment by sfisher** [comment]
I have resent all the missing reports to DataCite for MDC.  These are the latest results.

https://docs.google.com/spreadsheets/d/1ILpWZHxx7aYEUG-QGpPPevYHs862n4NvZhJuEH6AcX8/edit?usp=sharing

I'm still not seeing any updates to the number of pages of results after submitting them again.  I'll let Kristian know.

**Comment by sfisher** [comment]
I re-checked all the months that I resubmitted before the break.  They are still not showing up.

I believe if we are just going to go ahead with automated processing and putting the basics into our database for our stats display it will be a somewhat different process that what we'd use with DataCite.

DataCite keeps reports for everything but when I process I just sum the output of our json files into our database, so the workflow will be quite different than if we are submitting to DataCite since we never store the stats for individual months, just the totals.

I'll move this ticket back to our backlog and put in a new ticket for what I need to do in order to hack around the stat problems until DataCite can get things working.

**Comment by ryscher** [comment]
Closing because we're trying to move away from this old fragile system to the brand new DataCite Widget, so we don't want to invest more time into the old system.
