### ISSUE TITLE
New Tenant: KAUST

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#553]
![KAUST University Library Logo - transparent background](https://user-images.githubusercontent.com/25755963/66825285-dbe78d80-eefe-11e9-8df2-7981c90f2e1f.png)

**Comment by marisastrong** [comment]
kaust metadata file can  be found on either of the UI servers in dryad/local/shibboleth/etc/shibboleth dir - you'll see a file with KAUST in it.

**Comment by marisastrong** [comment]
this is a great ticket for a template!

**Comment by ryscher** [comment]
I can make a template.

@marisastrong I have this set up now, but I can't fully test it on dev. I manually added the extra KAUST file to the dev shibboleth config, and the dev server does now correctly redirect to KAUST, but the message I receive is "Unsupported Request. The application you have accessed is not registered for use with this service." I assume this is because the server on the KAUST end isn't expecting a request from our dev server? So it should work on production, correct?

**Comment by marisastrong** [comment]
KAUST is reporting an error when trying to authenticate to Dryad.  

opensaml::FatalProfileException: A valid authentication statement was not found in the incoming message.
Non-specific. You need to check the log for specific information about why the incoming assertion was invalid.

![KAUST_Error_FatalException](https://user-images.githubusercontent.com/810543/170531840-7ac9421a-1b76-4b07-8571-b29963ccdff3.png)

opensaml::FatalProfileException: A valid authentication statement was not found in the incoming message.
Non-specific. You need to check the log for specific information about why the incoming assertion was invalid.

**2022-05-26 00:06:29**|Shibboleth-TRANSACTION.AuthnRequest|||https://waseet.kaust.edu.sa/idp/shibboleth||||||urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect||||||
**2022-05-26 00:06:32**|Shibboleth-TRANSACTION.Login|||https://waseet.kaust.edu.sa/idp/shibboleth||||||urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST|opensaml::FatalProfileException|urn:oasis:names:tc:SAML:2.0:status:Success|||Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0|172.30.11.78

from shibd.log
**2022-05-26 00:02:12**|Shibboleth-TRANSACTION.Login|||https://waseet.kaust.edu.sa/idp/shibboleth||||||urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST|opensaml::SecurityPolicyException||||Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0|172.30.11.78
**2022-05-26 00:02:12** ERROR OpenSAML.SecurityPolicyRule.MessageFlow [23] [default]: replay detected of message ID (_697c6850b572913f83145f6c5ba0218b)
**2022-05-26 00:02:12** WARN Shibboleth.SSO.SAML2 [23] [default]: error processing incoming assertion: Rejecting replayed message ID (_697c6850b572913f83145f6c5ba0218b).
**2022-05-26 00:06:32** ERROR Shibboleth.SSO.SAML2 [14] [default]: failed to decrypt assertion: Unable to resolve any key decryption keys.
**2022-05-26 00:06:32** WARN Shibboleth.SSO.SAML2 [14] [default]: error processing incoming assertion: A valid authentication statement was not found in the incoming message.

**Comment by marisastrong** [comment]
A few errors are seen in the logs
SecurityPolicyRule.MessageFlow/Exception - this could be due to the time not being synchronized between the IdP and the SP.  All servers using SAML MUST maintain accurate time.  Refer to the OS to sync up time to a reliable source

FatalProfileException 
Unable to resolve any key decryption keys

- The SP received encrypted XML (usually an EncryptedAssertion) and couldn't decrypt it. The SP's metadata probably doesn't contain the same public key(s) the SP is configured to use (or the credentials didn't load).
- Service Provider complains Unable to resolve any key decryption keys after authentication
This means that the Service Provider uses a different pair of X.509 certificate/key than was used to register the Service Provider with the Resource Registry. Please compare the certificate used by the Service Provider with the certificate that you used to create the Resource Description. Most likely, they are not the same.

confirmed the sp-cert.pem is the same cert configued in shibboleth2.xml, exists in the datadryad.org SP metadata and is valid.
