### ISSUE TITLE
Differentiating and handling "in progress"

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#568]
Step 1: change UI status for in progress to show as "archiving" when it's being sent to Merritt, keep "in progress" for when it's pre-submit

Step 2: implement email to corresponding author three days after status "in-progress", and seven days after that. DL to come up with email text.

**Comment by ryscher** [comment]
Most of these cases are items that were left with `resource_state=in_progress`. This can mean there was an issue with Merritt processing. Should we provide a way for curators to override this?

**Comment by sfisher** [comment]
A query like this may be helpful for items like these.

```
SELECT ids.id as identifier_id, ids.identifier, res.id as resource_id, res.user_id, res.current_editor_id, res_state.`resource_state`, rqs.state
FROM stash_engine_identifiers ids
JOIN stash_engine_resources res
ON ids.id = res.identifier_id
JOIN stash_engine_resource_states res_state
ON res.id = res_state.resource_id
LEFT JOIN stash_engine_repo_queue_states rqs
ON res.id = rqs.resource_id
WHERE ids.identifier = '10.5061/dryad.1v2j41v';
```

It looks like all but the last are in a state where the user began re-editing a new version of the dataset after they have already submitted one.  (The resource_ids for the in-progress version is different than the other resource_ids, ie. a new version.)  We don't allow simultaneous editing of a dataset since it can be a recipe for chaos to have two people changing things at once and destroying each other's work.  I believe this is the same issue that Ryan put the `Preview` link in for as a first step to encourage people *not* to edit their datasets again and then just walk away from them in order to see a preview.

I can imagine that curators might want to edit, anyway, and take over and modify whatever the user is trying to do (or has abandoned) and then we might lock the user out of their own edits, instead, because the curator has determined they're not actually doing anything useful.

Or maybe there is another workflow that should take place, like a user cannot begin re-editing their own work except in certain circumstances such as once it has been turned over to a curator.  The workflow details need to be thought through with more specific details.

**Comment by ryscher** [comment]
I've fixed the individual items noted at the start of this ticket. It now seems that the underlying problem for all of them is a resource that was created but never submitted to Merritt. 

Possible ways to prevent this:
- Allows curators to take over as editor for any unsubmitted resource that has not been edited within the past X hours
- Improve the display on the user dashboard to indicate that they must finish their resource in progress before it can be curated
