### ISSUE TITLE
Deleting large files causes new versions to be unusable

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#571]
Since users can't upload more than 10GB at a time through the UI, they sometimes try to upload their files in multiple versions of the dataset. However, some users don't understand how the versioning works, so instead of simply adding new files, they may delete all of the files from their first version. 

This makes the display confusing. But more importantly, it causes some problem that causes new versions to get stuck in Merritt processing, and makes them unusable.

For an example, see 10.5061/dryad.rfj6q576j

**Comment by sfisher** [comment]
Hi Ryan,

Can you say more about what happened with this one?  I understand people being confused, but do you know how this is causing any technical problems with Merritt?  I'm not at all convinced they are problems with Merritt or that the latest version of this was ever submitted to Merritt at all.  There are no logs of it being submitted to Merritt in the `stash_engine_submission_logs` table either.  I could search through, our server logs, also, but I figured you might know.

Most likely early in the history, this is one of the "deleted the same file multiple times" ones I probably put in the "rejected_shutting_down" and then re-enqueued after cleaning up the multiple deletions of the same files.  It kind of looks like from the status that it went through Merritt without any problems for that version which I fixed the multiple deletions for.

The thing I find very confusing is the last version (resource_id 39864, which in theory has been successfully submitted to Merritt (ie `submitted`), but never actually was enqueued to be submitted, so I don't know how it would've ever gotten stored in Merritt.  It seems like you were a "guest editor" of this one since your user_id is listed as the "current editor."  Is this something you actually clicked "submit" on?

Or is this something you went into the database and change statuses manually?  Since I don't know how it would've gotten into the submitted state when it doesn't ever seem to have actually been enqueued or logged.

```
SELECT ids.id as identifier_id, ids.identifier, res.id as resource_id, res.user_id, res.current_editor_id, res_state.`resource_state`, rqs.state
FROM stash_engine_identifiers ids
JOIN stash_engine_resources res
ON ids.id = res.identifier_id
JOIN stash_engine_resource_states res_state
ON res.id = res_state.resource_id
LEFT JOIN stash_engine_repo_queue_states rqs
ON res.id = rqs.resource_id
WHERE ids.identifier = '10.5061/dryad.rfj6q576j';
```

```
identifier_id	identifier	resource_id	user_id	current_editor_id	resource_state	state
35925	10.5061/dryad.rfj6q576j	39256	23450	23450	submitted	enqueued
35925	10.5061/dryad.rfj6q576j	39256	23450	23450	submitted	processing
35925	10.5061/dryad.rfj6q576j	39256	23450	23450	submitted	completed
35925	10.5061/dryad.rfj6q576j	39256	23450	23450	submitted	completed
35925	10.5061/dryad.rfj6q576j	39753	23450	23450	submitted	enqueued
35925	10.5061/dryad.rfj6q576j	39753	23450	23450	submitted	rejected_shutting_down
35925	10.5061/dryad.rfj6q576j	39753	23450	23450	submitted	enqueued
35925	10.5061/dryad.rfj6q576j	39753	23450	23450	submitted	processing
35925	10.5061/dryad.rfj6q576j	39753	23450	23450	submitted	completed
35925	10.5061/dryad.rfj6q576j	39753	23450	23450	submitted	completed
35925	10.5061/dryad.rfj6q576j	39864	23450	14149	submitted	NULL
```
