### ISSUE TITLE
Monitoring the shibd service

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#578]
We should be notified when shibd is not running, either via Nagios or other monitoring service.

Figure out how to test it, give the information to Mark who has access to nagio set up

**Comment by marisastrong** [comment]
https://dryad-stg.cdlib.org/Shibboleth.sso/Status could provide what we need.

https://wiki.shibboleth.net/confluence/display/SP3/Status+Handler

**Comment by sfisher** [comment]
Thanks for this info, @marisastrong.  I started looking into this but haven't been able to get a status response (testing on stage) and not exactly sure what changes need to take place in both Apache and Shibboleth configs.  The documentation indicates with default settings it may be opened up to `127.0.0.1` or `localhost` for path `/Shibboleth.sso/Status`.

`dryad@uc3-dryaduix2-stg-2a:~/local/shibboleth-sp/etc/shibboleth\shibboleth2.xml` seems to contain the setup for Shibboleth and the Status handler.   It looks like there is an access control list of IP addresses in there.  I assume we may also need to be sure Apache is set up right to allow access for any Nagios script.  Also, perhaps we need to change something in our Apache to allow it?  Not sure.

@mreyescdl We would really like to add Nagios monitoring to our Shibboleth-sp daemon to be sure it doesn't randomly get killed since that has happened to us a couple times in recent weeks.  It looks like all this setup is likely controlled by configuration files under puppet control.

Is configuring and adding Nagios monitoring for the shibboleth-sp daemon something you can look at and take on?  I could try some additional configuration to see if I could figure something out, but it's hard because puppet may wipe out changes.

Let me know what you think or how you'd prefer to proceed. We'd really like to get some kind of Shibboleth monitoring into Nagios if we can and Daniella put it in our queue for working on for the next two weeks.

**Comment by marisastrong** [comment]
@mreyescdl will put in a status check to check Shibboleth status.  If shibboleth is up we should see this:

```
dryad@uc3-dryaduix2-prd-2a:~/init.d$ ./shibd.dryad status
shibd (pid 2896) is running...
```

if it's down we can detect this:
```
ryad@uc3-dryaduix2-prd-2a:~/init.d$ ./shibd.dryad status
shibd is stopped
```
Will be tested on stage first and if all is good will put into production early next week. (no prod deploys on fridays :-)
