### ISSUE TITLE
Add status to CDL System Status page

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#602]
Marisa noted we are not on the CDL system status page at 

https://cdlib.org/contact/system-status/ .

- [x] put in request to [website.requests](mailto:website.requests@cdlib.org) to update the Service name to be Dryad
- [x] include a Nagios check for the service that can be referenced by the cdl status page page
- [x] monitor the access logs before shutting the server
- [ ] turn off nagios monitoring and update the CDL System Status Page once we decommission servers

@ryscher currently monitors the service via his AWS environment and alerts are posted to the slack channel.  

Related to https://github.com/CDL-Dryad/dryad-product-roadmap/issues/600

**Comment by marisastrong** [comment]
CDLSYS Issue Number: | 13312
Updates to the datadryad-prod Service escalation in Nagios.

for the 1st hour of checks(1), please change the Notification Period to 7x24.
For the 2nd hour of checks (4), please change the Notification Period to 7x24. Upon review, IAS is not being notified via text for the datadryad-prod service so that will remain the same (i.e. we do not want IAS to be alerted via text)
