### ISSUE TITLE
Clarify publication options for data associated with manuscripts in progress

### ISSUE THREAD

**Issue by elizabethdryad** [CDL-Dryad/dryad-product-roadmap#630]
We are receiving a few help tickets per week from authors who are confused about what happens/happened to their dataset after submission. Some people are upset that their dataset was published; they thought it would be kept private until their paper was accepted (or published).

Some existing tickets should help: https://github.com/CDL-Dryad/dryad-product-roadmap/issues/627, https://github.com/CDL-Dryad/dryad-product-roadmap/issues/622, https://github.com/CDL-Dryad/dryad-product-roadmap/issues/615, but it might be better to provide some explicit publication options when users are submitting data associated with a manuscript in progress, e.g.:
1) Please curate and publish my dataset ASAP
2) Please curate my dataset ASAP but do not publish it until the associated article is published
3) Please hold my dataset Private for Peer Review until the associated paper is accepted

Those seem to be the 3 situations we need to accommodate. However, with options 2 and 3, if the journal is not integrated we won't necessarily know when the article is accepted and/or published. So we need to instruct the author that they'll have to inform us of these events.

**Comment by ryscher** [comment]
@jleighherzog @bryanmgee -- is this still an issue?

**Comment by bryanmgee** [comment]
@ryscher @jleighherzog Yes this still comes up, and it is likely a bigger problem than we realize because our turnaround has improved so much that I'm seeing a higher incidence of sponsored datasets that are subsequently rejected by the sponsoring journal after dataset publication and because the majority of authors may not realize what "published" means and so do not realize that the data are public even though they don't want them to be. Maybe 1 in 6 or 7 datasets that are Submitted now come with a nearly empty Activity Log (i.e. nothing between initial creation and being picked up), and I suspect most are for MS that are not yet accepted

**Comment by ryscher** [comment]
@bryanmgee @ahamelers I am closing this, since I believe all off the underlying issues have been addressed by recent changes to the PPR selection and the user dashboard.
