### ISSUE TITLE
New Tenant: University of New South Wales, Sydney

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#633]
![unsw](https://user-images.githubusercontent.com/25755963/72850148-4e35df80-3c5d-11ea-8ea1-ddfb48568c6b.png)

Success testing shibboleth

**Comment by sfisher** [comment]
![Screen Shot 2020-01-27 at 2 51 18 PM](https://user-images.githubusercontent.com/105433/73221544-03610f80-4116-11ea-9774-009632c4ab2c.png)

This is what their logo looks like (above).  I deployed to dryad-dev.cdlib.org, so I hope that lets them login there to test .  We can deploy to stage, also, if that's a better place for them to test.

Their icon looks a little small because the shield thing is so much bigger than the UNSW SYDNEY and it fits in a certain height.
