### ISSUE TITLE
New Tenant: Ohio State University

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#634]
[SVG logo can't upload here]

In Research & Scholarship category of InCommon - successful in testing

**Comment by sfisher** [comment]
![Screen Shot 2020-01-27 at 2 50 41 PM](https://user-images.githubusercontent.com/105433/73221721-6e124b00-4116-11ea-8ed1-ff6eccc22c2a.png)

Ohio state as seen on development (see above).  It also looks a bit small because maybe because they either have the whitespace around it in the image, or maybe just because they're fitting more text into a certain height.  Could also deploy on stage.
