### ISSUE TITLE
New Tenant: Univ Rhode Island

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#666]
Reminder to add to list of "Our Members"
Reminder to add to list of schools in drop down for login

**Comment by marisastrong** [comment]
Ongoing testing with Univ of Rhode Island Shibboleth integration.  URI utilizes Active Directory Federated Service (ADFS) (i.e. not a member of InCommon) and must be configured manually into the Shibboleth SP.  There are a couple of issues we are working through.  

1) eppn is currently not being sent from URI ADFS so awaiting information from Microsoft support.  This is a requirement in order for us to add them as a tenant as our Shibboleth SP requires this attribute.

2) Testing.  We have 2 options.

1. use our printenv script to verify appropriate attributes are being returned.  Once this is successful, we can add URI as a tenant within the application.
2. URI can be configured into our stage application which allows them to test however they need to set up a sandbox ORCID account to login to ORCID then be prompted to sign in via URI's SSO.  If there are issues with attributes, I dont think we have visibility into the errors returned for troubleshooting hence option 1 is preferred.

**Comment by marisastrong** [comment]
Attended a call with URI & UCOP ITS to continue assisting URI Identity Management team wrt to adding eppn.  A few cautious steps need to occur on URI end to support defining and populating eppn before they can send to us.  They have a plan and are running with it.

**Comment by marisastrong** [comment]
URI appears to have successfully made changes on their end to send the proper attributes to the Dryad SP.  
- [ ] update stage to configure the application with URI tenant for testing - entityID="https://sts.windows.net/426d2a8d-9ccd-4255-893d-0686a32c168d
- [ ] copy URI metadata to the 2c and update the shibboleth2.xml file to reference their metadata (they are not in InCommon metadata file so we need to manage their metadata separately).
- [ ] check in these new files into puppet
- [ ] Once stage application and servers are configured, perform a test with URI to ensure authentication is working
- [ ] configure prod system with these same steps.

**Comment by sfisher** [comment]
OK, I put the configuration in on stage and it seems like it has some problems.

![Screen Shot 2020-06-15 at 5 41 22 PM](https://user-images.githubusercontent.com/105433/84719201-8ea93900-af2f-11ea-9358-7c011ab32fa4.png)
![Screen Shot 2020-06-15 at 5 40 36 PM](https://user-images.githubusercontent.com/105433/84719206-8fda6600-af2f-11ea-965d-22f1f777bf56.png)

**Comment by marisastrong** [comment]
trailing / was the issue so resolved.  

URI has done a test in stage with the tenant configured in the Dryad app, however because they were already logged into their IdP / SSO in their browser, after selecting URI in the dropdown they were not redirected to authenticate to their SSO and went straight to the my datasets page.  I asked for one more test to be done with clearing cache.

I have prepared the files in the production environment for when we are ready to deploy the app configured with URI in prod env so should make for a short turnaround.

**Comment by sfisher** [comment]
HI @marisastrong .  It probably redirected and validated in the background and just wasn't visible because of the way shibboleth or identity providers work with not asking for login again if you're logged into it recently.

If they want to be prompted for login from their IDP I probably need to reset their tenant_id in their user account.  I looks like Michael Khalfayan logged in and was authenticated through university of rhode island.  I reset his tenant to NULL for his user, so this should force a prompt for validation on his next login.

**Comment by marisastrong** [comment]
for prod deploy, need to do the following on each server:

- [ ] turn off puppet for shibboleth2.xml file
- [ ] copy shibboleth2.xml.URI file to shibboleth2.xml
- [ ] rename Non-InCommon-Members-metadata.xml.URI to Non-InCommon-Members-metadata.xm
- restart shibboleth
