### ISSUE TITLE
Move dryad-config secrets to Rails 5 secret system

### ISSUE THREAD

**Issue by ryscher** [CDL-Dryad/dryad-product-roadmap#774]
See documentation of new secrets system at - https://medium.com/cedarcode/rails-5-2-credentials-9b3324851336

Tasks:
- [x] determine which config params are truly secrets, and move these into the Rails 5 secret file
- [x] set up all servers to use the proper environment variables for decoding the secret file
- [x] move the remaining configs into regular config files in the dryad-app repo
- [ ] archive the dryad-config repo (will do after all servers are deployed with new info)

**Comment by sfisher** [comment]
Hey Ryan,

Have you been following the work Terry and Brian Riley have been doing to use Amazon's services to store secrets?  I'm just curious how much "The Rails Way" and "The AWS/Terry Way" interact.  Brian and Terry created a gem or something to deal with Amazon secrets, which I assume may mesh with the "Rails 5 Way" but I'd hate for you to do lots of work on this if it turns out to be extra work compared to the direction they want to push all the services.

**Comment by marisastrong** [comment]
Hi Scott et al,

Thanks for flagging this and pointing out the alternative approach for securing credentials.

Advantages of using the AWS SSM model is that it does not allow cross domain access (dev can't access stage, stage can't access prod).  It also allows for runtime modifications.   Using SSM provides definitie location for credentials.

We discussed also moving tenants into SSM in the longer term.

Having all the of UC3 services use a similar approach is a goal as well.
________________________________
