### ISSUE TITLE
Ensure all varchar/text fields that allow user input support UTF8MB4

### ISSUE THREAD

**Issue by sfisher** [CDL-Dryad/dryad-product-roadmap#791]
Related to the database, we had to do special tricks to get UTF8-MB4 (4 byte UTF8) to work since by default MySQL does 3-byte.  That makes lots of characters and emoji fail.

Those fields probably should support utf8-mb4 and also have a collation that makes sense for them which I think is how matches happen in queries.  (sometimes we may want to be case insensitive and sometimes not such as filenames)

I think that the poop emoji is one of the ones that fails as well as some asian characters and some other things.

We have some things set in our database connection to use it, but maybe Rails 5 has finally done something to get saner defaults or has a way to do this better now.

**Comment by ryscher** [comment]
Current status:
- For new installations of Dryad, all tables/columns are created with the correct settings (my development VM is correct, which is why I didn't originally notice many problems).
- The dev/stage/prod servers have many fields that use incorrect settings.
- I have tested the process to convert these fields using the stage server.
- Since the conversion process involves fairly broad changes to the databases, I want to take some extra precautions with it, so I will wait until after the holidays to complete it.

**Comment by ryscher** [comment]
Added a ticket for Merritt at https://github.com/CDLUC3/mrt-doc/issues/552
