### ISSUE TITLE
Import Metadata failing for dataset submissions

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#829]
**Bug description:**
Import metadata is failing with dataset submissions, even when acceptance notices received for a dataset.

**Steps to reproduce:**
Search for dataset: 
10.5061/dryad.t4b8gtj07
Attempt to import metadata 
Metadata fails with error message _"We could not find metadata to import for this manuscript. Please enter your metadata below."_

**Expected behavior:**
If Journal Name is selected and a correct manuscript # is entered, the metadata should import 

**Note** 
We have received notification from submitters that metadata import is failing and confirmed by two curators.
Have reported issues with Functional Ecology (FE-2020-00575) and Journal of Animal Ecology (JAE-2020-00503) however have tested other datasets associated with different journals, so appears to be global, not specific to any one journal.

**Comment by ryscher** [comment]
I was able to import metadata for:
- Functional Ecology (FE-2020-00575) 
- Journal of Animal Ecology (JAE-2020-00503)
- Journal of Paleontology (JPA-RA-2020-0009  OR  2020-0009)

Without watching someone use the UI, it is difficult to diagnose the problem. I suspect that the problem is encountered when the user types (or pastes) the full journal name, and does not select the journal name from the autocomplete box. This is a quirk of our UI that is relatively tricky to change.
