### ISSUE TITLE
Related Works: Update metadata for all prior related works

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#837]
https://docs.google.com/spreadsheets/d/1tv-P0sl3Q-zN5K_EZ4VbGw-cWwE62-pGvLhFXnYsqQY/edit#gid=1369847420

- Add functionality to "display" or "not display" for things that we do not want to show on the landing page (designated by either "no" on 1400 tab or not highlighted on the small tab)

**DOI Tab**
- Update Related Work "type" for UI (column E)

**1400 Clean Up Tab**
- If "no" in Column D, do not display
- Otherwise, update with Column E "Related Work Type", as well as the identifier in Column F

**Small Clean Up Tab**
- If highlighted, update identifier, related identifier type, and type of identifier

**For all clean up**
- For anything being updated, use relationtype that is now in the system (over ride what the author stated was the relation type)

**Comment by ryscher** [comment]
As these relationships are changed, we need to change the code that relies on the relationship types. I ran into this issue a bit in https://github.com/CDL-Dryad/dryad-app/pull/234. Some places that reference `issupplementto`, and may need to change:

lib/tasks/stash_datacite_tasks.rake
lib/tasks/publication_updater.rake
stash/stash_engine/lib/tasks/link_out.rake
stash/stash_engine/app/models/stash_engine/identifier.rb
stash/stash_engine/app/views/stash_engine/publication_updater/_proposed_change_line.html.erb
stash/stash_datacite/lib/stash/indexer/indexing_resource.rb
stash/stash_datacite/lib/stash/import/crossref.rb
stash/stash_datacite/app/models/stash_datacite/related_identifier.rb
stash/stash_datacite/app/controllers/stash_datacite/metadata_entry_pages_controller.rb
stash/stash_datacite/app/controllers/stash_datacite/publications_controller.rb
spec/factories/stash_datacite/related_identifiers.rb
spec/lib/stash_datacite/crossref_spec.rb
spec/lib/stash_datacite/indexing_resource_spec.rb
spec/models/stash_engine/proposed_change_spec.rb
spec/models/stash_engine/identifier_spec.rb
spec/models/stash_datacite/completions_spec.rb

**Comment by sfisher** [comment]
I think I'm fixing the proposed changes stuff now and the magic-fill by doi.  But yeah, basically we probably should look through all the code if it needs to reflect the new UI practices which are basically that we now only have 2 related identifier types (URL and DOI) and they should all be formatted as URLs to be valid.

Also the relationship type is now always tied to the the Work type (ie article, dataset, etc) with a pre-defined relation.  Also adding flags for validated means that it will not be flagged to users and curators.

If someone puts in the old data it still displays (the old way), but then people will freak out because it's not the pretty new way with very limited functionality for related works.
