### ISSUE TITLE
Import Metadata throwing error: unable to import metadata

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#890]
**Bug description:**
Import metadata button is not importing article metadata for multiple journals and associated manuscripts. Tested with RSOS, eLife, and People and Nature manuscripts where metadata emails have been received

People and Nature: PAN-20-08-189
eLife: 15-11-2019-RA-eLife-53664
RSOS:  RSOS-191511

**Steps to reproduce:**
Create a new dataset
Enter in a journal name (from dropdown) and manuscript where metadata has been submitted to dryad.journal.submit@gmail.com
Click Import metadata button
See error: We could not find metadata to import for this manuscript. Please enter your metadata below.

**Expected behavior:**
When user creates new dataset, enters in a journal name (from dropdown),enters a legitimate ms# and clicks import metadata button, the import should work without error 

**Note:** User emailed HelpDesk (FB 55588) stating that import was not functioning. Tested and confirmed as superuser.

**Comment by dfagandryad** [comment]
This is likely happening for at least some of these items because the  journal-submit webapp appears to be down, and emails from the last few days are stuck in journal-submit:

Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.18 (Ubuntu) Server at v1.datadryad.org Port 443

**Comment by ryscher** [comment]
I have restarted the V1 server, and this functionality is working again.
