### ISSUE TITLE
Harvey Mudd user gets error trying to SSO

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#914]
User tried doing SSO from Dryad page and it gave her this error when clicking on Harvey Mudd from dropdown:

Unknown or Unusable Identity Provider

The identity provider supplying your login credentials is not authorized for use with this service or does not support the necessary capabilities.

To report this problem, please contact the site administrator at uc3@ucop.edu.

Please include the following error message in any email:

Identity provider lookup failed at (https://datadryad.org/Shibboleth.sso/Login)

EntityID: https://login.hmc.edu/idp/shibboleth

opensaml::saml2md::MetadataException: Unable to locate metadata for identity provider (https://login.hmc.edu/idp/shibboleth)

**Comment by sfisher** [comment]
The entityID we have configured now doesn't match the one in the InCommon config file at  /apps/dryad/local/shibboleth-sp/var/InCommon-metadata.xml .  We have configured `https://login.hmc.edu/idp/shibboleth` but this file lists `https://identity.hmc.edu/idp`.  Very weird.

I know I tested that I at least got to a login screen with these on stage, so probably either the stage one is different or has changed (since I pulled that URL from that file).

I'll investigate both environments and update our config.

**Comment by sfisher** [comment]
I updated their entity id with the new one and now get a login page again.  The user should try logging in again (since I can't test actual login, just that shibboleth redirects to login).  Maybe Harvey Mudd outsourced their shibboleth to someone else?  I notice it now says "RapidIdentity" at the top.

![Screen Shot 2020-10-15 at 10 32 34 AM](https://user-images.githubusercontent.com/105433/96165790-f36ea300-0ed1-11eb-9265-ee3ede199804.png)
