### ISSUE TITLE
Activity Log & Admin Layer displaying different statuses for same dataset

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#917]
Inconsistent statuses across a dataset displaying for curators...

Dataset is published, activity log says it published, but the admin layer displays status "embargo"
OR
Dataset is in curation status, activity log says curation, but admin layer displays Embargoed or AAR

Examples (though they have now been manually adjusted):
10.5061/dryad.kp32qr6
10.5061/dryad.hmgqnk9f5
10.5061/dryad.rv15dv469
10.7280/D14T2K
10.6086/D14X10
10.5061/dryad.xsj3tx9bf

**Comment by sfisher** [comment]
There are a few things here.  There can be a *version* that is published despite another *version* going into curation later.  However I think the curator interface shows only the curation states (not if any version has been published).  It is perfectly acceptable for a dataset to be already published and another version to be in curation or similar states.

As far as I can tell, this is caused by curators holding obsolete versions open and doing things such as clicking "publish" on them after later versions have been created and had other states applied.  It is then "publishing" an earlier version and the later one is not published but keeps its current curation status.

Certain states are only allowed after certain other states, so always applying the state to the latest version could be problematic.  It's not clear that applying the state to the end of all states will always be the correct action, even if it's an allowed state--since that is guessing at the curator's intention while they're looking at obsolete data.

The solution is probably that any actions applied against an obsolete version (where other curation has happened after that version) needs to be blocked and the curation should only happen agains the current non-in-progress (user editing) version.

This problem is really more or less the same as ticket #813 .
