### ISSUE TITLE
Newly uploaded dataset files will not download as data package or individually 

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#946]
**Bug description:**
For dataset doi:10.6071/M34T1Z newly uploaded files 11/13/20 are not being downloaded via "Download dataset."  When you click "Download Dataset" the prior data file 4/9/20 is downloaded instead. 

When you try to individually download the files by clicking directly on the file the browser throws an error "Something went wrong, check logs for more information." When you try right clicking "save as," the file download fails with an error "server problem."

**Steps to reproduce:**
Navigate to dataset, try to click on any of the November 13, 2020 files and try to download the files via the steps above

**Expected behavior:**
The new files should download as a package when the "Download Dataset" button is clicked and the files should be individually downloadable

**Comment by elopatin-uc3** [comment]
@sfisher @terrywbrady there is a `%` sign in the name of one of the object's files (both versions):
`pherrel%916oh.xls`

The related presign error is:
~~~
An ArgumentError occurred in file#presign:

  invalid byte sequence in UTF-8
  app/controllers/file_controller.rb:155:in `match'


-------------------------------
Request:
-------------------------------

  * URL        : http://merritt.cdlib.org/api/presign-file/ark%3A%2F13030%2Fm5256kp0/1/producer%2Fpherrel%25916oh.xls
  * HTTP Method: GET
  * IP address : xxx.xxx.xxx.xxx
  * Parameters : {"controller"=>"file", "action"=>"presign", "object"=>"ark:/13030/m5256kp0", "version"=>"1", "file"=>"producer/pherrel%916oh.xls"}
  * Timestamp  : 2020-11-13 21:54:50 UTC
  * Server : uc3-mrtui02x2-prd
    * Rails root : /apps/dpr2/apps/ui/releases/20200915230302
  * Process: 9944

**Comment by ryscher** [comment]
These are two separate issues. 
1) The issue that Lori mentioned with doi:10.6071/M34T1Z -- I'm not sure what is wrong with this one yet... will require some investigation.
2) The issue that @elopatin-uc3 mentioned is associated with doi:10.5061/dryad.1956 -- This is one of the broken items I've been cleaning up today. I'm not certain what caused the original problem, but I have this item working in Dryad now, since I re-uploaded the file without the %. Unfortunately, Merritt now has both versions of the file. This isn't terrible from Dryad's standpoint, but Merritt may want to clean it up.

**Comment by elopatin-uc3** [comment]
Thanks for the clarification @ryscher. Apologies for the mixup.

**Comment by sfisher** [comment]
I don't know if there was some manual fixing done on this dataset but the versions were wrong in our database.  Merritt had one more version than we showed in our database.

The last version number was incorrect, so I edited our database to reflect the changed numbering in Merritt and it fixes the download issues.

**Comment by LoriEP** [comment]
Thank you @sfisher
