### ISSUE TITLE
Please adjust payment sponsorship for dataset doi: 10.5061/dryad.02v6wwq23

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#961]
**Request** dataset is affiliated with UC Santa Cruz but submitter's account is not affiliated properly, please adjust payment so that invoice is not generated

**Comment by ryscher** [comment]
Added tenant `ucsc` to user and to payment info on the dataset/identifier.

**Comment by LoriEP** [comment]
Thank you! and thank you for doing the extra step of adding the tenant.

**Comment by sfisher** [comment]
We need to be careful about changing tenants on existing datasets because it will make some turn into a time bomb for failures in the future when they are updated if they use a separate Merritt collection and also if they use a separate DOI minting service (EZID) and shoulder.

The first problem will be taken care of shortly when Merritt moves all the UC content into one collection (Dryad) and then updates to datasets will still work even if they've had their tenant changed.

The second problem is moving DataCite DOI to an EZID DOI with a different shoulder.  This will only work if it hasn't been published yet.    The steps would be 1) Mint a new EZID DOI for the appropriate tenant,  2) Update the metadata for that DOI, 3) Go into the database and replace the identifier in the identifiers table from the old DataCite DOI with the new EZID DOI, 4) withdraw the DataCite DOI that was created originally.

This obviously is going to be problematic if a dataset is published since it will make DOIs unstable, which defeats the whole point of DOIs.

The big problem is that the DataCite account cannot update other account's DOIs and the EZID account cannot update other account's DOIs either so all future updates will fail if changing the tenant without also changing the DOI to something that can be updated.

**Comment by ryscher** [comment]
Sorry for the extra stress @sfisher -- I know that changing the tenant of a dataset is a huge problem. So I didn't change the tenant for these. I changed the tenant for the user (which will affect their future datasets), and the payment info for the dataset (which only affects payments, not anything else related to the tenant). The tenant on the dataset itself (i.e., `stash_engine_resources.tenant`) has not changed.

**Comment by sfisher** [comment]
Thanks, @ryscher .  Makes sense.

I wish we had never allowed "vanity" EZID prefixes or shoulders and just made everyone use the same one because that would make our lives a lot easier about now with flexibility in moving things around.
