### ISSUE TITLE
Import metadata failing for multiple journals with acceptance notices

### ISSUE THREAD

**Issue by LoriEP** [CDL-Dryad/dryad-product-roadmap#963]
**Bug description:**
Import metadata failing.
Author reported that they could not import metadata for Paleobiology, ms # PAB-OR-2020-0028. Verified acceptance notice received and that import fails.

Tested multiple other journal and ms # combinations with acceptance notices, all fail. 

**Steps to reproduce:**
Create new dataset
Enter in journal name and manuscript number for an accepted article with acceptance notice received 
Click 'Import metadata'
See error message: "We could not find metadata to import for this manuscript. Please enter your metadata below."

**Expected behavior:**
If acceptance notice received and Journal Name and Manuscript number are entered correctly, metadata should import

**Comment by ryscher** [comment]
Journal email had not been processed for a month due to the permissions/password changing on the email account. I reset the password, re-authorized the Dryad application with Google OAUTH, and processed the 4000 messages that had accumulated. The example above now works, and all other manuscript numbers should work as well.
