### ISSUE TITLE
New Tenant: Desert Research Institute

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#985]
![DRI-logo-transparentback](https://user-images.githubusercontent.com/25755963/109859698-2069eb00-7c12-11eb-9c52-7e0049bc8b80.png)

**Comment by marisastrong** [comment]
For SSO authentication, DRI has been configured as [Non-Federated-Members institutions](https://confluence.ucop.edu/display/UC3/Shibboleth+Code+Notes#ShibbolethCodeNotes-Non-FederationMetadata) since their IdP does not belong to InCommon, thereby is not included in the InCommon metadata that is downloaded daily.  

DRI IdP uses Okta for authentication.  Currently the IdP metadata produced by the Okta configuraiton tools do not include a 
```xml
<shibmd:Scope regexp="false">dri.edu</shibmd:Scope>
```
It has been added manually to the [DRI Idp metadata provided](https://nshe-dri.okta.com/app/exkh1l6ocbKBRm4RB1t7/sso/saml/metadata).  

```xml
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:shibmd="urn:mace:shibboleth:metadata:1.0" entityID="http://www.okta.com/exkh1l6ocbKBRm4RB1t7">
        <md:IDPSSODescriptor WantAuthnRequestsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <md:Extensions>
      <mdui:UIInfo xmlns:mdui="urn:oasis:names:tc:SAML:metadata:ui">
        <mdui:DisplayName xml:lang="en">Desert Research Institute</mdui:DisplayName>
      </mdui:UIInfo>
      <shibmd:Scope regexp="false">dri.edu</shibmd:Scope>
    </md:Extensions>
```

Additionally the attribute-mapping.xml file was updated to include the ScopedAttributeDecoder to properly receive the eppn attribute via Shibboleth SP.

```xml
    <Attribute name="urn:mace:dir:attribute-def:eduPersonPrincipalName" id="eppn"/>
    <Attribute name="eppn" id="eppn">
        <AttributeDecoder xsi:type="ScopedAttributeDecoder"/>
    </Attribute>
    <Attribute name="urn:oid:1.3.6.1.4.1.5923.1.1.1.6" id="eppn">
        <AttributeDecoder xsi:type="ScopedAttributeDecoder"/>
    </Attribute>
```

Applying this change to both instances in stage, puppetizing, restarting Shib and then will apply to production.

**Comment by marisastrong** [comment]
https://www.pivotaltracker.com/story/show/177231560

**Comment by sfisher** [comment]
Thank you, Marisa.  👍  🎈
