### ISSUE TITLE
Update tenant for user before they're charged: Paul Ponganis (UCSD)

### ISSUE THREAD

**Issue by dlowenberg** [CDL-Dryad/dryad-product-roadmap#990]
pponganis@ucsd.edu
https://orcid.org/0000-0002-1556-770X

dataset is something with the word penguins or emperor penguins - if we can change this to UCSD that would be great thanks

**Comment by sfisher** [comment]
OK.  I updated this.  The thing is that UCSD uses EZID and Dryad doesn't so updates can be problematic since different DOI accounts/services (EZID vs DataCite) cannot update each other.  I don't think it is published yet, so I hope switching the DOI to an EZID one for UCSD will work. 🤞 

If it breaks horrendously at some point then the original DOI from Dryad was 10.5061/dryad.3tx95x6f5 and the new one from EZID is 10.6076/D1H01Z .  Even though these might not be used yet, they get set up when people start their datasets in one way or another.  If we have troubles down the road then we will need to switch these back, though I *think* we might be ok here. 🤞 🤞 🤞 🤞 🤞 🤞 🤞 🤞 

We will soon have all storage in one Merritt collection.  If we want freedom to move stuff around between most UC collection and Dryad then it would be awesome not to use special EZID for the campuses, though maybe not practical since we can't change their old DOIs to Dryad shoulder without breaking their old persistent ids (afaik).  So it would mean splitting old and new identifiers between EZID and DataCite for campuses, which is obnoxious.
